package com.tokopedia.hotel.common.analytics

const val SCREEN_NAME = "screenName"
const val CURRENT_SITE = "currentSite"
const val CLIENT_ID = "clientId"
const val SESSION_IRIS = "sessionIris"
const val USER_ID = "userId"
const val BUSINESS_UNIT = "businessUnit"

const val PROMO_VIEW = "promoView"
const val PROMO_CLICK = "promoClick"
const val CLICK_HOTEL = "clickHotel"
const val VIEW_PRODUCT = "viewProduct"
const val PRODUCT_VIEW = "productView"
const val PRODUCT_CLICK = "productClick"
const val ADD_TO_CART = "addToCart"
const val CHECKOUT = "checkout"
const val VIEW_HOTEL_IRIS = "viewHotelIris"

const val DIGITAL_NATIVE = "digital - native"

const val TOKOPEDIA_DIGITAL_HOTEL = "tokopediadigitalhotel"

const val BANNER_IMPRESSION = "banner impression"
const val VIDEO_BANNER_IMPRESSION = "view travel video"
const val ACTION_LAST_SEARCH_IMPRESSION = "view last search impression"
const val ACTION_LAST_SEARCH_CLICK = "click last search"
const val ACTION_CLICK_CHANGE_SEARCH = "click change on search result page"
const val ACTION_SAVE_CHANGE_SEARCH = "click search hotel on change search page"
const val CLICK_BANNER = "click banner"
const val CLICK_VIDEO_BANNER = "click travel video"
const val SELECT_DESTINATION = "select destination"
const val CLICK_WIDGET_SELECT_DESTINATION = "click widget select destination"
const val SELECT_STAY_DATE = "select stay date"
const val SELECT_ROOM_GUEST = "select room guest"
const val SEARCH_HOTEL = "search hotel"
const val VIEW_HOTEL_LIST_IMPRESSION = "view hotel list impression"
const val VIEW_FULL_MAP = "view full map"
const val VIEW_CLOSE_MAP = "close map"
const val VIEW_MAP_ON_SRP = "view map on srp"
const val CLICK_MY_LOCATION = "click my location"
const val CLICK_SEARCH_NEAR_LOCATION = "click cari di sekitar sini"
const val SEE_HOTEL_NOT_FOUND = "see hotel not found"
const val CHOOSE_HOTEL = "choose hotel"
const val CHOOSE_HOTEL_FROM_MAP = "choose hotel on map mode"
const val USER_CLICK_FILTER = "user click filter"
const val USER_CLICK_SORT = "user click sort"
const val VIEW_HOTEL_PDP = "view hotel pdp"
const val CLICK_HOTEL_PHOTO = "click hotel photo"
const val CLICK_HOTEL_REVIEWS = "click hotel reviews"
const val CHOOSE_VIEW_ROOM = "choose view room"
const val VIEW_ROOM_LIST = "view room list"
const val VIEW_ROOM_DETAILS = "view room details"
const val CHOOSE_ROOM = "choose room"
const val CLICK_ROOM_PHOTO_ON_ROOM_LIST = "click room photo on room list"
const val CLICK_ROOM_DETAILS = "click room details"
const val CLICK_ROOM_PHOTO_ON_ROOM_PDP = "click room photo on room pdp"
const val CHOOSE_ROOM_DETAILS_PDP = "choose room details pdp"
const val CLICK_NEXT = "click next"
const val CLICK_CHECKOUT = "click checkout"
const val APPLY_PROMO = "apply promo"
const val STEP_LABEL = "step"
const val OPTION_LABEL = "option"
const val VIEW_CANCELLATION_PAGE = "view cancellation page"
const val CLICK_NEXT_ON_CANCELLATION_PAGE = "click next on cancellation page"
const val CLICK_SUBMIT_CANCELLATION = "click submit cancellation"
const val VIEW_CANCELLATION_STATUS = "view cancellation status"
const val CLICK_ON_CANCELLATION_RESULT_PAGE = "click on cancellation result page"
const val CLICK_QUICK_FILTER_ON_SRP = "click quick filter on search result page"
const val CLICK_USER_CLICK_FILTER = "user click filter"
const val CLICK_SHARE_ICON = "click share url"

const val HOTEL_LABEL = "hotel"
const val TRAVELENTERTAINMENT_LABEL = "travel & entertainment"
const val ECOMMERCE_LABEL = "ecommerce"
const val PRODUCTS_LABEL = "products"
const val PROMOTIONS_LABEL = "promotions"
const val ADD_LABEL = "add"
const val CLICK_LABEL = "click"
const val ID_LABEL = "id"
const val NAME_LABEL = "name"
const val POSITION_LABEL = "position"
const val CREATIVE_LABEL = "creative"
const val SLASH_HOTEL_LABEL = "/hotel"
const val SLASH_HOTEL_SLASH_LABEL = "/hotel/"
const val IMPRESSIONS_LABEL = "impressions"
const val CURRENCY_LABEL = "currencyCode"
const val PRICE_LABEL = "price"
const val DETAIL_LABEL = "detail"
const val ACTION_FIELD_LABEL = "actionField"
const val LIST_LABEL = "list"
const val IDR_LABEL = "IDR"
const val VARIANT_LABEL = "variant"
const val CATEGORY_LABEL = "category"
const val QUANTITY_LABEL = "quantity"
const val HOTEL_CONTENT_LABEL = "Hotel"
const val ONE_LABEL = "1"
const val LABEL_VIDEO_BANNER = "travel video"

const val REGION_LABEL = "region"
const val LAST_SEARCH_LABEL = "last search"

const val LABEL_HOTEL_SEARCH_MAP = "search by map"

const val SCREEN_NAME_CHECKOUT_PROMO = "/hotel/checkoutpromo"