package com.tokopedia.play.broadcaster.setup.cover

sealed interface PlayBroSetupCoverEvent {

    data class SubmitCoverEvent(
        val isLoading: Boolean,
        val throwable: Throwable? = null,
    ) : PlayBroSetupCoverEvent

    data class ButtonSetupCoverEvent(
        val isEnabled: Boolean,
        val showDelete: Boolean = false
    ) : PlayBroSetupCoverEvent

    data class ErrorAutoGeneratedCover(
        val throwable: Throwable?,
        val onRetry: (() -> Unit)? = null,
    ) : PlayBroSetupCoverEvent
}
