package com.tokopedia.play.broadcaster.setup.cover

import com.tokopedia.play.broadcaster.ui.model.setup.AutoGeneratedCoverUIModel

data class PlayBroSetupCoverUiState(
    val autoGeneratedCover: List<AutoGeneratedCoverUIModel>,
) {
    companion object {
        val Empty: PlayBroSetupCoverUiState
            get() = PlayBroSetupCoverUiState(
                autoGeneratedCover = emptyList()
            )
    }
}

