package com.tokopedia.play.broadcaster.setup.cover

import com.tokopedia.play.broadcaster.ui.model.PlayCoverUiModel
import com.tokopedia.play.broadcaster.ui.model.campaign.ProductTagSectionUiModel
import com.tokopedia.play.broadcaster.ui.model.setup.AutoGeneratedCoverUIModel

sealed interface PlayBroSetupCoverAction {
    data class SetUploadImageCover(
        val cover: PlayCoverUiModel
    ) : PlayBroSetupCoverAction

    data class SelectAutoGeneratedCover(
        val data: AutoGeneratedCoverUIModel, val position: Int
    ) : PlayBroSetupCoverAction

    object UnSelectAutoGeneratedCover : PlayBroSetupCoverAction

    object GetAutoGeneratedImageCoverPreview : PlayBroSetupCoverAction

    object SetUploadAutoGeneratedCover : PlayBroSetupCoverAction

    object CheckButtonState : PlayBroSetupCoverAction

    object RemoveStateAutoGeneratedCover : PlayBroSetupCoverAction
}
