package com.tokopedia.play.broadcaster.ui.model.setup

/**
 * Created by fachrizalmrsln on 16/01/23
 */
data class AutoGeneratedCoverIUModel(
    val id: String = "",
    val background: String = "",
    val imageUrl: String = "",
    val isChecked: Boolean = false,
)
