package com.tokopedia.play.broadcaster.ui.model.setup

/**
 * Created by fachrizalmrsln on 16/01/23
 */
data class AutoGeneratedCoverUIModel(
    val imageUrl: String = "",
    val isChecked: Boolean = false,
    val channelTitle: String = "",
    val channelAuthor: String = "",
)
