package com.tokopedia.seller_migration_common.constants

object SellerMigrationConstants {
    const val KEY_SHOULD_DISMISS_AFTER_RESTORE = "dismiss_after_restore"

    const val ACCOUNT_SELLER_MIGRATION_IMAGE_LINK = "https://ecs7.tokopedia.net/other/seller_migration_account.png"
    const val SELLER_MIGRATION_SHOP_PAGE_TAB_FEED_LINK = "https://ecs7.tokopedia.net/android/merchant/seller_migrationv2/Frame@2x.png"
    const val SELLER_MIGRATION_FRAGMENT_BANNER_LINK = "https://ecs7.tokopedia.net/android/seller_migration_fragment_banner.png"
    const val SELLER_MIGRATION_POST_FEED_BANNER_LINK = "https://ecs7.tokopedia.net/android/merchant/seller_migration/seller_migration_post_feed.png"
    const val PACKAGE_SELLER_APP = "com.tokopedia.sellerapp"
    const val APPLINK_PLAYSTORE = "market://details?id="
    const val URL_PLAYSTORE = "https://play.google.com/store/apps/details?id="
    const val APP_ENABLE_SELLER_MIGRATION = "android_mainapp_enable_seller_migration"
    const val APP_DATE_SELLER_MIGRATION = "android_mainapp_seller_migration_date"
    const val SELLER_MIGRATION_KEY_AUTO_LOGIN = "is_auto_login"
    const val SELLER_MIGRATION_KEY_AUTO_ANCHOR_ACCOUNT_SHOP = "is_auto_anchor"

    const val URL_PROMO_ICON = "https://ecs7.tokopedia.net/android/sellermigration/ic_promo.png"
    const val URL_PLAY_ICON = "https://ecs7.tokopedia.net/android/sellermigration/ic_tokopedia_play.png"
    const val URL_STATISTICS_ICON = "https://ecs7.tokopedia.net/android/sellermigration/ic_statistics_review.png"
    const val URL_FINANCE_ICON = "https://ecs7.tokopedia.net/android/sellermigration/ic_saldo_prio.png"
    const val URL_FEATURED_PRODUCT_ICON = "https://ecs7.tokopedia.net/android/sellermigration/ic_featured_product.png"
    const val URL_MULTI_EDIT_ICON = "https://ecs7.tokopedia.net/android/sellermigration/ic_multi_edit.png"
    const val URL_CASHBACK_ICON = "https://ecs7.tokopedia.net/android/sellermigration/ic_manage_cashback.png"
    const val URL_VARIANT_ICON = "https://ecs7.tokopedia.net/android/sellermigration/ic_variant.png"
    const val URL_ATTACH_VOUCHER_ICON = "https://ecs7.tokopedia.net/android/sellermigration/ic_attach_voucher.png"
    const val URL_TEMPLATE_CHAT_ICON = "https://ecs7.tokopedia.net/android/sellermigration/ic_template_chat.png"
    const val URL_SMART_REPLY_DISCUSSION_ICON = "https://ecs7.tokopedia.net/android/sellermigration/ic_discussion_smart_reply.png"
    const val URL_SELLER_INSIGHT_ICON = "https://ecs7.tokopedia.net/android/sellermigration/ic_seller_insight.png"
    const val URL_TEMPLATE_REVIEW_ICON = "https://ecs7.tokopedia.net/android/sellermigration/ic_template_review.png"
    const val URL_TOPADS_ICON = "https://ecs7.tokopedia.net/android/sellermigration/ic_topads.png"
    const val URL_STOCK_REMINDER_ICON = "https://ecs7.tokopedia.net/android/sellermigration/ic_stock_reminder.png"
    const val URL_FEED_ICON = "https://ecs7.tokopedia.net/android/sellermigration/ic_feed.png"
    const val URL_SHOP_FUND_ICON = "https://ecs7.tokopedia.net/android/sellermigration/ic_shop_fund.png"
}