package com.tokopedia.recharge_component.presentation.adapter

import com.tokopedia.home_component.productcardgridcarousel.typeFactory.CommonCarouselProductCardTypeFactory
import com.tokopedia.recharge_component.model.RechargeBUWidgetProductCardModel

interface RechargeBUWidgetProductCardTypeFactory: CommonCarouselProductCardTypeFactory {
    fun type(rechargeBUWidgetProductCardModel: RechargeBUWidgetProductCardModel) : Int
}