package com.tokopedia.buy_more_get_more.olp.utils.constant

object TrackerConstant {
    const val EVENT_CLICK_PG = "clickPG"
    const val EVENT_CLICK_COMMUNICATION = "clickCommunication"
    const val EVENT_VIEW_COMMUNICATION_IRIS = "viewCommunicationIris"
    const val EVENT_OPEN_SCREEN = "openScreen"
    const val EVENT_VIEW_PG_IRIS = "viewPGIris"
    const val EVENT_VIEW_ITEM_LIST = "view_item_list"
    const val EVENT_SELECT_CONTENT = "select_content"
    const val EVENT_ADD_TO_CART = "add_to_cart"
    const val EVENT_CATEGORY_OLP_BMGM = "olp bmgm"
    const val EVENT_CATEGORY_BMSM_PAGE = "bmsm page"
    const val TRACKER_ID = "trackerId"
    const val BUSINESS_UNIT_OLP_BMGM = "physical goods"
    const val BUSINESS_UNIT_SHARING_EXPERIENCE = "sharingexperience"
    const val CURRENT_SITE_OLP_BMGM = "tokopediamarketplace"
    const val LOGIN_STATUS = "isLoggedInStatus"
    const val SCREEN_NAME = "screenName"
    const val SESSION_IRIS = "sessionIris"

    const val EVENT = "event"
    const val EVENT_ACTION = "eventAction"
    const val EVENT_CATEGORY = "eventCategory"
    const val EVENT_LABEL = "eventLabel"
    const val BUSINESS_UNIT = "businessUnit"
    const val CURRENT_SITE = "currentSite"
    const val ITEM_LIST = "item_list"
    const val ITEMS = "items"
    const val USER_ID = "userId"
    const val SHOP_ID = "shopId"
}
