package com.tokopedia.shop.common.constant

object ShopShowcaseParamConstant {
    const val SHOWCASE_PICKER_RESULT_REQUEST_CODE = 1011
    const val EXTRA_SHOP_ID = "EXTRA_SHOP_ID"
    const val EXTRA_ETALASE_ID = "EXTRA_ETALASE_ID"
    const val EXTRA_SHOP_TYPE = "EXTRA_SHOP_TYPE"
    const val EXTRA_SELECTED_ETALASE_ID = "EXTRA_SELECTED_ETALASE_ID"
    const val EXTRA_IS_SHOW_DEFAULT = "EXTRA_IS_SHOW_DEFAULT"
    const val EXTRA_IS_SHOW_ZERO_PRODUCT = "EXTRA_IS_HIDE_HERO_PRODUCT"
    const val EXTRA_ETALASE_NAME = "EXTRA_ETALASE_NAME"
    const val EXTRA_ETALASE_TYPE = "EXTRA_ETALASE_TYPE"
    const val EXTRA_ETALASE_BADGE = "EXTRA_ETALASE_BADGE"
    const val EXTRA_IS_NEED_TO_RELOAD_DATA = "EXTRA_IS_NEED_TO_RELOAD_DATA"
    const val EXTRA_EDIT_SHOWCASE_RESULT = "EXTRA_IS_EDIT_SHOWCASE_SUCCESS"
    const val EXTRA_IS_SELLER_NEED_TO_HIDE_SHOWCASE_GROUP_VALUE = "EXTRA_IS_SELLER_NEED_TO_HIDE_SHOWCASE_GROUP_VALUE"
    const val EXTRA_IS_NEED_TO_OPEN_SHOWCASE_PICKER = "EXTRA_IS_NEED_TO_OPEN_SHOWCASE_PICKER"
    const val EXTRA_PRE_SELECTED_SHOWCASE_PICKER = "EXTRA_PRE_SELECTED_SHOWCASE_PICKER"
    const val EXTRA_IS_MY_SHOP = "EXTRA_IS_MY_SHOP"
    const val EXTRA_PICKER_SELECTED_SHOWCASE = "EXTRA_PICKER_SELECTED_SHOWCASE"
    const val EXTRA_PICKER_TYPE = "EXTRA_PICKER_TYPE"
    const val EXTRA_PICKER_PRODUCT = "EXTRA_PICKER_PRODUCT"
    const val EXTRA_PICKER_PRODUCT_ID = "EXTRA_PICKER_PRODUCT_ID"
    const val EXTRA_PICKER_PRODUCT_NAME = "EXTRA_PICKER_PRODUCT_NAME"
    const val EXTRA_BUNDLE = "EXTRA_BUNDLE"
}

object ShowcaseRulesName {
    const val FOLLOWERS_ONLY = "followers_only"
}

object ShowcasePickerType {
    const val CHECKBOX = "showcase_checkbox_picker"
    const val RADIO = "showcase_radio_picker"
}