package com.tokopedia.shop.common.constant

object ShopShowcaseParamConstant {
    val EXTRA_SHOP_ID = "EXTRA_SHOP_ID"
    val EXTRA_ETALASE_ID = "EXTRA_ETALASE_ID"
    val EXTRA_SHOP_TYPE = "EXTRA_SHOP_TYPE"
    val EXTRA_SELECTED_ETALASE_ID = "EXTRA_SELECTED_ETALASE_ID"
    val EXTRA_IS_SHOW_DEFAULT = "EXTRA_IS_SHOW_DEFAULT"
    val EXTRA_IS_SHOW_ZERO_PRODUCT = "EXTRA_IS_HIDE_HERO_PRODUCT"

    val EXTRA_ETALASE_NAME = "EXTRA_ETALASE_NAME"
    val EXTRA_ETALASE_TYPE = "EXTRA_ETALASE_TYPE"
    val EXTRA_ETALASE_BADGE = "EXTRA_ETALASE_BADGE"
    val EXTRA_IS_NEED_TO_RELOAD_DATA = "EXTRA_IS_NEED_TO_RELOAD_DATA"
}