package com.tokopedia.gm.common.constant

const val IMG_URL_REGULAR_MERCHANT_POPUP = "https://ecs7.tokopedia.net/img/android/gold_merchant_common/regular_merchant_popup.png"
const val IMG_URL_POWER_MERCHANT_IDLE_POPUP = "https://ecs7.tokopedia.net/img/android/power_merchant_subscribe/power_merchant_idle.png"
const val GM_TITLE = "Power Merchant"
const val PATTERN_DATE_SHOP_INFO = "yyyy-MM-dd"
const val NEW_SELLER_DAYS = 90
const val START_TENURE_EIGHTY_THREE = 83
const val TRANSITION_PERIOD = "transition_period"
const val ZERO_NUMBER = 0
const val ONE_NUMBER = 1
const val TWO_NUMBER = 2
const val THREE_NUMBER = 3
const val FOUR_NUMBER = 4
const val FIVE_NUMBER = 5
const val SIX_NUMBER = 6
const val SEVEN_NUMBER = 7
const val THIRTY_DAYS = 30
const val PATTERN_DATE_TEXT = "dd MMMM yyyy"
const val SHOP_AGE_NINETY_ONE = 91
const val SHOP_AGE_NINETY_TWO = 92
const val SHOP_AGE_NINETY_THREE = 93
const val SHOP_AGE_NINETY_FOUR = 94
const val SHOP_AGE_NINETY_FIVE = 95
const val SHOP_AGE_NINETY_SEVEN = 97
const val SHOP_AGE_NINETY_EIGHT = 98
const val SHOP_AGE_NINETY_NINE = 99
const val SHOP_AGE_ONE_HUNDRED = 100
const val SHOP_AGE_ONE_HUNDRED_ONE = 101
