package com.tokopedia.play.broadcaster.domain.model.imagegenerator

import com.tokopedia.play.broadcaster.ui.model.campaign.ProductTagSectionUiModel
import com.tokopedia.play.broadcaster.ui.model.setup.AutoGeneratedCoverIUModel

class ImageGeneratorMapper(
    private val productSectionList: List<ProductTagSectionUiModel>,
    private val authorLogo: String,
) {

    private val backgroundList = listOf("blue", "red", "turquoise", "purple", "orange", "green")
    private val productAmount: Int
        get() = getProductImageUrl().size
    private val productUrl1: String
        get() = getProductImageUrl()[0]
    private val productUrl2: String
        get() = getProductImageUrl()[1]

    private fun getProductImageUrl(): List<String> {
        val productUrl = mutableListOf<String>()
        if (productSectionList.isNullOrEmpty()) return emptyList()
        if (productSectionList[0].products.isNullOrEmpty()) return emptyList()
        if (productSectionList[0].products.size > 2) {
            productUrl.add(productSectionList[0].products[0].imageUrl)
            productUrl.add(productSectionList[0].products[1].imageUrl)
        } else {
            productUrl.add(productSectionList[0].products[0].imageUrl)
        }
        return productUrl
    }

    private fun generateImage(backgroundColor: String): String {
        val previewImage = "$HOST_PROD?" +
            "$KEY_BACKGROUND_COLOR=$backgroundColor&" +
            "$KEY_SHOP_LOGO=$authorLogo&" +
            "$KEY_PRODUCT_AMOUNT=$productAmount&" +
            "$KEY_PRODUCT_IMAGE_1=$productUrl1"
        return if (productAmount == 2) "$previewImage&$KEY_PRODUCT_IMAGE_2=$productUrl2"
        else previewImage
    }

    fun getImagePreview(): List<AutoGeneratedCoverIUModel> {
        val data = mutableListOf<AutoGeneratedCoverIUModel>()
        backgroundList.forEach { backgroundColor ->
            data.add(AutoGeneratedCoverIUModel(imageUrl = generateImage(backgroundColor)))
        }
        return data
    }

    companion object {
        private const val KEY_BACKGROUND_COLOR = "background_color"
        private const val KEY_SHOP_LOGO = "shop_logo"
        private const val KEY_PRODUCT_AMOUNT = "product_amount"
        private const val KEY_PRODUCT_IMAGE_1 = "product_image_1"
        private const val KEY_PRODUCT_IMAGE_2 = "product_image_2"
        private const val SOURCE_ID = "LScDrk"
        private const val HOST_PROD = "https://imagenerator.tokopedia.com/v2/preview/$SOURCE_ID"
        private const val HOST_STAGING = "https://imagenerator-staging.tokopedia.com/v2/preview/$SOURCE_ID"
    }
}
