package com.tokopedia.tokofood.common.analytics

object TokoFoodAnalyticsConstants {

    const val BUSSINESS_UNIT = "businessUnit"
    const val CURRENT_SITE = "currentSite"
    const val USER_ID = "userId"
    const val SHOP_ID = "shopId"
    const val DESTINATION_ID = "destinationId"
    const val PRODUCT_ID = "productId"
    const val TRACKER_ID = "trackerId"
    const val PROMO_ID = "promoId"
    const val IS_LOGGED_IN_STATUS = "isLoggedInStatus"
    const val SCREEN_NAME = "screenName"
    const val GOFOOD_PAGENAME = "gofood"
    const val PAGE_SOURCE = "pageSource"
    const val NULL = "null"

    const val KEY_EE_PROMOTIONS = "promotions"
    const val KEY_EE_CREATIVE_NAME = "creative_name"
    const val KEY_EE_CREATIVE_SLOT = "creative_slot"
    const val KEY_EE_ITEM_ID = "item_id"
    const val KEY_EE_ITEM_NAME = "item_name"

    const val TOKOPEDIA_MARKETPLACE = "tokopediamarketplace"
    const val OPEN_SCREEN = "openScreen"
    const val CLICK_PG = "clickPG"
    const val PHYSICAL_GOODS = "Physical Goods"
    const val ADD_TO_CART = "add_to_cart"
    const val VIEW_ITEM = "view_item"
    const val BEGIN_CHECKOUT = "begin_checkout"
    const val VIEW_PG_IRIS = "viewPGIris"

    // home
    const val EMPTY_DATA = "null"
    const val HOME_PAGE = "Tokofood Homepage"
    const val OUT_OF_COVERAGE = "Error State Out of Coverage"
    const val NO_PIN_POIN = "Error State No Pinpoint"
    const val TRACKER_ID_31288 = "31288"
    const val TRACKER_ID_31289 = "31289"
    const val TRACKER_ID_32007 = "32007"
    const val TRACKER_ID_32008 = "32008"

    // post purchase
    const val ORDER_DETAIL_PAGE = "Order detail page"
    const val VIEW_TOKOFOOD_ORDER_DETAIL_PAGE = "view tokofood order detail page"
    const val CLICK_CALL_ICON = "click call icon"
    const val CLICK_CALL_DRIVER = "click call driver"
    const val CLICK_HELP = "click bantuan"
    const val CLICK_BUY_AGAIN = "click buy again"
    const val TOKOFOOD_ORDER_DETAIL_PAGE = "tokofood order detail page"

    // Merchant Page
    const val ITEM_LIST = "item_list"
    const val SELECT_CONTENT = "select_content"
    const val VIEW_ITEM_LIST = "view_item_list"
    const val IMPRESSION_ON_PRODUCT_CARD = "impression on product card"
    const val CLICK_ON_PRODUCT_CARD = "click on product card"
    const val CLICK_ON_CHECKOUT_MINICART = "click on checkout minicart"
    const val CLICK_ON_PESAN_PRODUCT_CARD = "click on pesan - product card"
    const val CLICK_ON_PESAN_PRODUCT_BOTTOM_SHEET = "click on pesan - product bottom sheet"
    const val CLICK_ON_PESAN_VARIANT_PAGE = "click on pesan - variant page"
    const val CLICK_ON_CHECKOUT_BUTTON_ON_MINICART = "click on checkout button on minicart"
    const val CLOSED = "closed"
    const val OPEN = "open"

    const val OOS = "OOS"
    const val NOT = "Not"
    const val INDEX = "index"
    const val TOKOFOOD_MERCHANT_PAGE = "tokofood merchant page"
    const val MERCHANT = "merchant"
    const val VIEW_COMMUNICATION_IRIS = "viewCommunicationIris"
    const val CLICK_COMMUNICATION = "clickCommunication"
    const val CLICK_CLOSE_SHARE_BOTTOM_SHEET = "click - close share bottom sheet"
    const val CLICK_SHARE_BOTTOM_SHEET = "click - share button"
    const val VIEW_ON_SHARING_CHANNEL = "view on sharing channel"
    const val USER_ID_FORMAT = "UserID %s"
    const val VIEW_MERCHANT_PAGE = "view_merchant_page"

    const val IMPRESSION_ON_PROMO_BUTTON = "impression on promo button"
    const val TRACKER_ID_37402 = "37402"
    const val CLICK_ON_PROMO_BUTTON = "click on promo button"
    const val TRACKER_ID_37403 = "37403"

    // Search Page
    const val CLICK_SEARCH_BAR_TOKOFOOD = "click search bar tokofood"
    const val TRACKER_ID_35766 = "35766"
    const val TOKOFOOD_HOME = "tokofood home"
    const val VIEW_SEARCH_HISTORY_TOKOFOOD = "view search history tokofood"
    const val TOKOFOOD_SEARCH_RECOMMENDATION = "tokofood search recommendation"
    const val TRACKER_ID_35767 = "35767"
    const val CLICK_SEARCH_HISTORY_TOKOFOOD = "click search history tokofood"
    const val TRACKER_ID_35768 = "35768"
    const val VIEW_TOP_KEYWORD_TOKOFOOD = "view top keyword tokofood"
    const val TRACKER_ID_35769 = "35769"
    const val CLICK_TOP_KEYWORD_TOKOFOOD = "click top keyword tokofood"
    const val TRACKER_ID_35770 = "35770"
    const val VIEW_CUISINE_LIST_TOKOFOOD = "view cuisine list tokofood"
    const val TRACKER_ID_35771 = "35771"
    const val CLICK_CUISINE_LIST_TOKOFOOD = "click cuisine list tokofood"
    const val TRACKER_ID_35772 = "35772"
    const val TOKOFOOD_SEARCH_RESULT_PAGE = "tokofood search result page"
    const val VIEW_COMPLETE_FILTER_TOKOFOOD = "view complete filter tokofood"
    const val TRACKER_ID_35773 = "35773"
    const val CLICK_COMPLETE_FILTER_TOKOFOOD = "click complete filter tokofood"
    const val TRACKER_ID_35774 = "35774"
    const val VIEW_SORT_FILTER_TOKOFOOD = "view sort filter tokofood"
    const val TRACKER_ID_35775 = "35775"
    const val CLICK_SORT_FILTER_TOKOFOOD = "click sort filter tokofood"
    const val TRACKER_ID_35776 = "35776"
    const val VIEW_MINI_FILTER_TOKOFOOD = "view mini filter tokofood"
    const val TRACKER_ID_35777 = "35777"
    const val CLICK_MINI_FILTER_TOKOFOOD = "click mini filter tokofood"
    const val TRACKER_ID_35778 = "35778"
    const val CLICK_ON_SUBMIT_FILTER_TOKOFOOD = "click on submit filter tokofood"
    const val TRACKER_ID_35785 = "35785"
    const val CLICK_ADDRESS_WIDGET_TOKOFOOD = "click address widget tokofood"
    const val TRACKER_ID_35786 = "35786"
    const val CLICK_MERCHANT_CARD_TOKOFOOD = "click merchant card tokofood"
    const val TRACKER_ID_35787 = "35787"
    const val CLICK_OTHER_BRANCHES = "click cabang lain"
    const val TRACKER_ID_35788 = "35788"
    const val VIEW_ADDRESS_WIDGET_IN_SRP_TOKOFOOD = "view address widget in SRP tokofood"
    const val TRACKER_ID_36853 = "36853"
    const val VIEW_MERCHANT_CARD_IN_SRP_TOKOFOOD = "view merchant card in SRP tokofood"
    const val TRACKER_ID_36854 = "36854"
    const val VIEW_COACHMARK = "view coachmark"
    const val TRACKER_ID_39609 = "39609"
    const val COMPONENT_SEARCH_BAR = "component:search_bar"
    const val TITLE_PREFIX = "title:"
    const val SUBTITLE_PREFIX = "subtitle:"

    // tokochat trackers
    const val TOKOCHAT_ORDER_DETAIL = "tokochat order detail"
    const val CLICK_CHAT_FROM_ORDER_DETAIL = "click chat from order detail"

    const val TRACKER_ID_39065 = "39065"
    const val BUYER = "buyer"
    const val TOKOFOOD_SOURCE = "Tokofood"

    const val COMMUNICATION = "communication"
}
