package com.tokopedia.sellerhome.analytic

/**
 * Created By @ilhamsuaib on 2020-02-11
 */

object TrackingConstant {

    //key
    const val EVENT = "event"
    const val EVENT_CATEGORY = "eventCategory"
    const val EVENT_ACTION = "eventAction"
    const val EVENT_LABEL = "eventLabel"
    const val SCREEN_NAME = "screenName"
    const val IS_LOGGED_IN_STATUS = "isLoggedInStatus"
    const val CURRENT_SITE = "currentSite"
    const val USER_ID = "userId"
    const val SHOP_ID = "shopId"
    const val BUSINESS_UNIT = "businessUnit"
    const val TRACKER_ID = "trackerId"

    //event
    const val VIEW_HOMEPAGE_IRIS = "viewHomepageIris"
    const val VIEW_PG_IRIS = "viewPGIris"
    const val CLICK_NAVIGATION_DRAWER = "clickNavigationDrawer"
    const val OPEN_SCREEN = "openScreen"
    const val CLICK_HOMEPAGE = "clickHomepage"
    const val CLICK_PG = "clickPG"

    //category
    const val TOP_NAV = "top nav"
    const val BOTTOM_NAV = "bottom nav"
    const val SELLER_APP_HOME = "seller app - home"

    //action
    const val IMPRESSION_WIDGET_CARD = "impression widget card"
    const val CLICK_WIDGET_CARD = "click widget card"
    const val IMPRESSION_WIDGET_LINE_GRAPH = "impression widget trendline"
    const val CLICK_WIDGET_LINE_GRAPH = "click widget trendline"
    const val IMPRESSION_WIDGET_DESCRIPTION = "impression widget description"
    const val CLICK_WIDGET_DESCRIPTION = "click widget description"
    const val IMPRESSION_WIDGET_PROGRESS_BAR = "impression widget progress bar"
    const val CLICK_WIDGET_PROGRESS_BAR = "click widget progress bar"
    const val IMPRESSION_WIDGET_POST = "impression widget post"
    const val CLICK_WIDGET_POST = "click widget post"
    const val CLICK_WIDGET_BANNER = "click widget banner"
    const val IMPRESSION_WIDGET_BANNER = "impression widget banner"
    const val SEE_MORE = "see more"
    const val HYPERLINK = "hyperlink"
    const val CLICK_NOTIFICATION = "click notification"
    const val CLICK_HOME = "click home"
    const val CLICK_PRODUCT = "click product"
    const val CLICK_CHAT = "click chat"
    const val CLICK_ORDER = "click order"
    const val CLICK_OTHERS = "click others"
    const val FILTER = "filter"
    const val POST = "post"
    const val SWIPE = "swipe"
    const val TRENDLINE = "trendline"
    const val RECOMMENDATION = "recom"
    const val CLICK_WIDGET_MULTI_LINE_GRAPH = "click widget multi trendline"
    const val CLICK_WIDGET_ANNOUNCEMENT = "click widget announcement"
    const val CLICK_WIDGET_RECOMMENDATION = "click widget recommendation"
    const val IMPRESSION_WIDGET_TABLE = "impression widget advance table"
    const val IMPRESSION_WIDGET_PIE_CHART = "impression widget pie chart"
    const val IMPRESSION_WIDGET_BAR_CHART = "impression widget bar chart"
    const val IMPRESSION_WIDGET_MULTI_LINE_GRAPH = "impression multi trendline"
    const val IMPRESSION_WIDGET_ANNOUNCEMENT = "impression widget announcement "
    const val IMPRESSION_WIDGET_RECOMMENDATION = "impression widget recommendation"
    const val CLICK_WIDGET_ADVANCE_TABLE = "click widget advance table"
    const val CLICK_WIDGET_BAR_CHART = "click widget bar chart"
    const val CLICK_WIDGET_PIE_CHART = "click widget pie chart"
    const val IMPRESSION_WIDGET_MILESTONE = "impression widget milestone - higher level"
    const val IMPRESSION_WIDGET_MILESTONE_CARD = "impression widget milestone - card level"
    const val CLICK_WIDGET_MILESTONE_CARD = "click widget milestone - card level"
    const val CLICK_WIDGET_MILESTONE_CARD_FINISHED =
        "click widget milestone - card level - finished state"
    const val CLICK_WIDGET_MILESTONE_SEE_MORE = "click widget milestone - higher level - see more"
    const val CLICK_WIDGET_MILESTONE_MINIMIZE =
        "click widget milestone - higher level - minimize view"
    const val CLICK_WIDGET_MILESTONE_SHARE = "click widget milestone - share"
    const val IMPRESSION_TICKER = "impression ticker"
    const val CLICK_TICKER_HYPERLINK = "click ticker - hyperlink"
    const val IMPRESSION_WIDGET_CALENDAR = "impression widget calendar"
    const val CLICK_WIDGET_CALENDAR_EVENT = "click widget calendar - event"
    const val CLICK_WIDGET_CALENDAR_SELECT_DATE_RANGE = "click widget calendar - select date range"
    const val CLICK_WIDGET_UNIFICATION_TAB = "click widget navigation tab - tab"
    const val CLICK_WIDGET_UNIFICATION_TAB_ITEM = "click widget navigation tab - item"
    const val CLICK_WIDGET_UNIFICATION_SEE_MORE = "click widget navigation tab - see more"
    const val CLICK_WIDGET_UNIFICATION_EMPTY_STATE = "click widget navigation tab - empty state"
    const val IMPRESSION_WIDGET_UNIFICATION = "impression widget navigation tab"
    const val IMPRESSION_WIDGET_UNIFICATION_SEE_TAB = "impression widget navigation tab - see tab"
    const val CLICK_POST_WIDGET_DELETE = "click widget post - delete"
    const val CLICK_POST_WIDGET_SUBMIT_DISMISSAL = "click widget post - submit dismissal"
    const val CLICK_POST_WIDGET_CANCEL_DISMISSAL = "click widget post - cancel dismissal"
    const val CLICK_ANNOUNCEMENT_WIDGET_CANCEL_DISMISSAL = "click widget announcement - cancel dismissal"
    const val CLICK_ANNOUNCEMENT_WIDGET_SUBMIT_DISMISSAL = "click widget announcement - submit dismissal"
    const val CLICK_ANNOUNCEMENT_WIDGET_DISMISSAL_PROMPT = "click widget announcement - dismissal prompt"
    const val IMPRESSION_FIRST_TRANSACTION_POPUP = "impression first transaction pop up"
    const val CLICK_FIRST_TRANSACTION_POPUP_NANTI_SAJA = "click on first transaction pop up - nanti saja"
    const val CLICK_FIRST_TRANSACTION_POPUP_PROSES_PESANAN = "click on first transaction pop up - proses pesanan"

    //search
    const val CLICK_SEARCH = "clickSearch"
    const val GLOBAL_SEARCH = "global search"
    const val CLICK_SEARCH_BUTTON = "click search button"

    //other value
    const val SCREEN_NAME_SELLER_HOME = "Seller Home"
    const val ADS_PROMOTION = "/adspromotion"
    const val TOKOPEDIA_SELLER = "tokopediaseller"
    const val TOKOPEDIA_MARKETPLACE = "tokopediamarketplace"
    const val PHYSICAL_GOODS = "physical goods"
    const val PHYSICAL_GOODS_CAPITALIZED = "Physical Goods"
    const val SINGLE = "single"
    const val MULTIPLE = "multiple"
    const val EMPTY = "empty"
    const val NOT_EMPTY = "not empty"
    const val NO_ACCESS = "No Access"
    const val EMPTY_STATE = "emptystate"
    const val SEPARATOR = " - "
    const val SPACE = " "
    const val ACTIVE = "active"
    const val FINISHED = "finished"
    const val LOCKED = "locked"
    const val EMPTY_STRING = ""
    const val TOTAL_FINISHED_MISSION = "%d out of %d missions finished"
    const val PG = "Physical Goods"
    const val DATA_KEY_LOW_STOCK = "lowStock"
    const val NOTIFY_ME = "notify me"

    //performance
    const val CLICK_SHOP_SCORE = "clickShopScore"
    const val ACTION_SHOP_SCORE = "click - performa toko"
    const val ACTION_SHOP_SCORE_NEW_SELLER = "click - performa"
    const val IMPRESS_ACTION_SHOP_SCORE_NEW_SELLER = "impression - performa"
    const val IMPRESS_ACTION_SHOP_SCORE = "impression - performa toko"
    const val CATEGORY_SHOP_SCORE_NEW_SELLER = "toko saya"
    const val CATEGORY_SHOP_SCORE = "lainnya"
    const val NEW_SELLER = "new seller -"
    const val SHOP_TYPE_RM = "RM"
    const val SHOP_TYPE_PM = "PM"
    const val SHOP_TYPE_OS = "OS"
    const val VIEW_SHOP_SCORE_IRIS = "viewShopScoreIris"

    //ticker
    const val TICKER_ANNOUNCEMENT = "announcement"
    const val TICKER_WARNING = "warning"
    const val TICKER_INFO = "info"
    const val TICKER_DANGER = "danger"

}
