package com.tokopedia.sellerhome.analytic

/**
 * Created By @ilhamsuaib on 2020-02-11
 */

object TrackingConstant {

    //key
    const val EVENT = "event"
    const val EVENT_CATEGORY = "eventCategory"
    const val EVENT_ACTION = "eventAction"
    const val EVENT_LABEL = "eventLabel"
    const val ECOMMERCE = "ecommerce"
    const val ID = "id"
    const val NAME = "name"
    const val CREATIVE = "creative"
    const val CREATIVE_URL = "creative_url"
    const val CATEGORY = "category"
    const val PROMO_ID = "promo_id"
    const val PROMO_CODE = "promo_code"
    const val POSITION = "position"
    const val PROMOTIONS = "promotions"
    const val SCREEN_NAME = "screenName"
    const val IS_LOGGED_IN_STATUS = "isLoggedInStatus"
    const val CURRENT_SITE = "currentSite"
    const val USER_ID = "userId"
    const val SHOP_ID = "shopId"
    const val SHOP_TYPE = "shopType"
    const val BUSINESS_UNIT = "businessUnit"

    //event
    const val VIEW_SELLER_WIDGET = "viewSellerWidget"
    const val VIEW_SELLER_DASHBOARD = "viewSellerDashboardIris"
    const val VIEW_SELLER_WIDGET_IRIS = "viewSellerWidgetIris"
    const val VIEW_SELLER_HOMEPAGE_IRIS = "viewHomepageIris"
    const val CLICK_SELLER_WIDGET = "clickSellerWidget"
    const val CLICK_SELLER_DASHBOARD = "clickSellerDashboard"
    const val PROMO_VIEW = "promoView"
    const val PROMO_CLICK = "promoClick"
    const val CLICK_NAVIGATION_DRAWER = "clickNavigationDrawer"
    const val OPEN_SCREEN = "openScreen"
    const val CLICK_HOMEPAGE = "clickHomepage"

    //category
    const val HOME = "home"
    const val SELLER_APP = "seller app"
    const val TOP_NAV = "top nav"
    const val BOTTOM_NAV = "bottom nav"

    //action
    const val IMPRESSION_WIDGET_CARD = "impression widget card"
    const val CLICK_WIDGET_CARD = "click widget card"
    const val IMPRESSION_WIDGET_LINE_GRAPH = "impression widget trend line"
    const val CLICK_WIDGET_LINE_GRAPH = "click widget trend line"
    const val IMPRESSION_WIDGET_DESCRIPTION = "impression widget description"
    const val CLICK_WIDGET_DESCRIPTION = "click widget description"
    const val IMPRESSION_WIDGET_PROGRESS_BAR = "impression widget progress bar"
    const val CLICK_WIDGET_PROGRESS_BAR = "click widget progress bar"
    const val IMPRESSION_WIDGET_POST = "impression widget post"
    const val CLICK_WIDGET_POST = "click widget post"
    const val CLICK_WIDGET_BANNER = "click widget banner"
    const val IMPRESSION_WIDGET_BANNER = "impression widget banner"
    const val SEE_MORE = "see more"
    const val CLICK_NOTIFICATION = "click notification"
    const val CLICK_HOME = "click home"
    const val CLICK_PRODUCT = "click product"
    const val CLICK_CHAT = "click chat"
    const val CLICK_ORDER = "click order"
    const val CLICK_OTHERS = "click others"
    const val FILTER = "filter"
    const val CLICK_WIDGET_MULTI_LINE_GRAPH = "click widget multi trendline"
    const val CLICK_WIDGET_MULTI_ANNOUNCEMENT = "click widget announcement"
    const val CLICK_RECOMMENDATION = "click recommendation"
    const val CLICK_RECOMMENDATION_WIDGET = "click recommendation widget"
    const val IMPRESSION_WIDGET_TABLE = "impression widget simple table"
    const val IMPRESSION_WIDGET_PIE_CHART = "impression widget pie chart"
    const val IMPRESSION_WIDGET_BAR_CHART = "impression widget bar chart"
    const val IMPRESSION_WIDGET_MULTI_LINE_GRAPH = "impression multi trendline"
    const val IMPRESSION_WIDGET_ANNOUNCEMENT = "impression widget announcement "
    const val IMPRESSION_RECOMMENDATION_WIDGET = "impression recommendation widget"
    const val CLICK_WIDGET_ADVANCE_TABLE = "click widget advance table"
    const val CLICK_WIDGET_SIMPLE_TABLE = "click widget simple table"

    //search
    const val CLICK_SEARCH = "clickSearch"
    const val GLOBAL_SEARCH = "global search"
    const val CLICK_SEARCH_BUTTON = "click search button"

    //other value
    const val SELLER_WIDGET = "/seller widget"
    const val SCREEN_NAME_SELLER_HOME = "Seller Home"
    const val ADS_PROMOTION = "/adspromotion"
    const val TOKOPEDIA_SELLER = "tokopediaseller"
    const val PHYSICAL_GOODS = "physical goods"
    const val NONE = "none"
    const val EMPTY = "empty"
    const val NOT_EMPTY = "not empty"
    const val WIDGET_SIMPLE_TABLE = "widget simple table"
    const val WIDGET_PIE_CHART = "widget pie chart"
    const val WIDGET_BAR_CHART = "widget bar chart"
    const val EMPTY_STATE = "emptystate"

    //performance
    const val CLICK_SHOP_SCORE = "clickShopScore"
    const val ACTION_CLICK_LEARN_MORE = "click - pelajari selengkapnya"
    const val ACTION_SHOP_SCORE = "click - performa toko"
    const val ACTION_SHOP_SCORE_NEW_SELLER = "click - performa"
    const val IMPRESS_LEARN_MORE = "impression - pelajari selengkapnya"
    const val IMPRESS_ACTION_SHOP_SCORE_NEW_SELLER = "impression - performa"
    const val IMPRESS_ACTION_SHOP_SCORE = "impression - performa toko"
    const val CATEGORY_COMMUNICATION_PERIOD_HOME = "communication period - home"
    const val CATEGORY_SHOP_SCORE_NEW_SELLER = "toko saya"
    const val CATEGORY_SHOP_SCORE = "lainnya"
    const val NEW_SELLER = "new seller -"
    const val SHOP_TYPE_RM = "RM"
    const val SHOP_TYPE_PM = "PM"
    const val SHOP_TYPE_OS = "OS"
    const val VIEW_SHOP_SCORE_IRIS = "viewShopScoreIris"
}