package com.tokopedia.discovery2.viewcontrollers.adapter.factory

import com.tokopedia.discovery2.ComponentNames
import com.tokopedia.discovery2.R


enum class ComponentsList(val id: Int, val componentName: String) {
    Default(R.layout.coming_soon_view, ComponentNames.Default.componentName),
    SingleBanner(R.layout.multi_banner_layout, ComponentNames.SingleBanner.componentName),
    DoubleBanner(R.layout.multi_banner_layout, ComponentNames.DoubleBanner.componentName),
    TripleBanner(R.layout.multi_banner_layout, ComponentNames.TripleBanner.componentName),
    QuadrupleBanner(R.layout.multi_banner_layout, ComponentNames.QuadrupleBanner.componentName),
    Share(R.layout.multi_banner_layout, ComponentNames.Share.componentName),
    CategoryNavigation(R.layout.discovery_horizontal_recycler_view_with_title, ComponentNames.HorizontalCategoryNavigation.componentName),
    CategoryNavigationIem(R.layout.item_category_navigation, ComponentNames.HorizontalCategoryNavigationIem.componentName),
    BrandRecommendation(R.layout.brand_recommendation_layout, ComponentNames.BrandRecommendation.componentName),
    BrandRecommendationItem(R.layout.brand_recommendation_layout_item, ComponentNames.BrandRecommendationItem.componentName),
    CarouselBanner(R.layout.carousel_banner_layout, ComponentNames.CarouselBanner.componentName),
    CarouselBannerItemView(R.layout.carousel_banner_item_layout, ComponentNames.CarouselBannerItemView.componentName),
    SliderBanner(R.layout.slider_banner_layout, ComponentNames.SliderBanner.componentName),
    BannerTimer(R.layout.banner_timer_layout, ComponentNames.BannerTimer.componentName),
    Tokopoints(R.layout.horizontal_recycler_view_layout, ComponentNames.Tokopoints.componentName),
    TokopointsItem(R.layout.tokopoints_item_layout, ComponentNames.TokopointsItem.componentName),
    LihatSemua(R.layout.lihat_semua, ComponentNames.LihatSemua.componentName),
    CpmTopAds(R.layout.cpm_topads_layout, ComponentNames.CpmTopAds.componentName),
    CpmTopAdsItem(R.layout.item_cpm_topads_shop_layout, ComponentNames.CpmTopAdsShopItem.componentName),
    CpmTopAdsProductItem(R.layout.item_cpm_topads_product_layout, ComponentNames.CpmTopAdsProductItem.componentName),
    YouTubeView(R.layout.youtube_player_view, ComponentNames.Video.componentName),
    ChipsFilterView(R.layout.coming_soon_view, ComponentNames.ChipsFilter.componentName),
    Notifier(R.layout.coming_soon_view, ComponentNames.Notifier.componentName),
    TitleImage(R.layout.coming_soon_view, ComponentNames.TitleImage.componentName),
    TextComponent(R.layout.coming_soon_view, ComponentNames.TextComponent.componentName),
    ClaimCoupon(R.layout.component_claim_coupon_layout, ComponentNames.ClaimCoupon.componentName),
    ClaimCouponItem(R.layout.component_claim_coupon_item, ComponentNames.ClaimCouponItem.componentName),
    CustomTopChat(R.layout.coming_soon_view, ComponentNames.CustomTopchat.componentName),
    Spacing(R.layout.spacing_layout, ComponentNames.Margin.componentName),
    ChipsFilter(R.layout.widget_recycler_view, ComponentNames.ChipsFilter.componentName),
    ChipsFilterItem(R.layout.chips_filter_item_layout, ComponentNames.ChipsFilterItem.componentName),
    Tabs(R.layout.widget_recycler_view, ComponentNames.Tabs.componentName),
    TabsItem(R.layout.tabs_item_layout, ComponentNames.TabsItem.componentName),
    DynamicCategory(R.layout.dynamic_category_layout, ComponentNames.DynamicCategory.componentName),
    DynamicCategoryItem(R.layout.dynamic_category_single_item_layout, ComponentNames.DynamicCategoryItem.componentName),
    LihatFlashSaleTimer(R.layout.lihat_flash_sale_timer_widget, ComponentNames.FlashSaleTimer.componentName),
    TimerSprintSale(R.layout.discovery_timer_sprint_sale_layout, ComponentNames.TimerSprintSale.componentName),
    ProductCardCarousel(R.layout.horizontal_recycler_view_layout, ComponentNames.ProductCardCarousel.componentName),
    PrductCardSprintSaleCarousel(R.layout.horizontal_recycler_view_layout, ComponentNames.PrductCardSprintSaleCarousel.componentName),
    ProductCardRevamp(R.layout.product_card_revamp_layout, ComponentNames.ProductCardRevamp.componentName),
    ProductCardItem(R.layout.product_item_layout, ComponentNames.ProductCardItem.componentName),
}
