package com.tokopedia.purchase_platform.common.constant

/**
 * Created by Irfan Khoirul on 2019-09-24.
 */

object CheckoutConstant {
    const val CHECKOUT = "CHECKOUT"
    const val REQUEST_CODE_CHECKOUT_ADDRESS = 981
    const val RESULT_CODE_ACTION_SELECT_ADDRESS = 100
    const val RESULT_CODE_ACTION_CHECKOUT_CHANGE_ADDRESS = 101
    const val RESULT_CODE_ACTION_CHECKOUT_SELECT_ADDRESS_FOR_SNIPPET = 102
    const val RESULT_CHECKOUT_CACHE_EXPIRED = 824
    const val TYPE_REQUEST_SELECT_ADDRESS_FROM_COMPLETE_LIST_FOR_MONEY_IN = 5
    const val EXTRA_SELECTED_ADDRESS_DATA = "EXTRA_SELECTED_ADDRESS_DATA"
    const val EXTRA_TYPE_REQUEST = "EXTRA_TYPE_REQUEST"
    const val EXTRA_IS_ONE_CLICK_SHIPMENT = "EXTRA_IS_ONE_CLICK_SHIPMENT"
    const val EXTRA_IS_FROM_CHECKOUT_CHANGE_ADDRESS = "EXTRA_IS_FROM_CHECKOUT_CHANGE_ADDRESS"
    const val EXTRA_IS_FROM_CHECKOUT_SNIPPET = "EXTRA_IS_FROM_CHECKOUT_SNIPPET"
    const val EXTRA_PREVIOUS_STATE_ADDRESS = "EXTRA_PREVIOUS_STATE_ADDRESS"
    const val EXTRA_CACHE_EXPIRED_ERROR_MESSAGE = "EXTRA_CACHE_EXPIRED_ERROR_MESSAGE"
    const val EXTRA_CHECKOUT_PAGE_SOURCE = "EXTRA_CHECKOUT_PAGE_SOURCE"
    const val CHECKOUT_PAGE_SOURCE_CART = "cart"
    const val CHECKOUT_PAGE_SOURCE_PDP = "product detail page"
    const val STATE_RED = "red"
    const val PARAM_DEFAULT = "default"
    const val PARAM_CHECKOUT = "checkout"
    const val PARAM_OCC_MULTI = "occmulti"
    const val RESULT_CODE_COUPON_STATE_CHANGED = 735
    const val KERO_TOKEN = "token"
    const val EXTRA_REF = "EXTRA_REF"
    const val REQUEST_ADD_ON_BOTTOMSHEET = 333
    const val ADD_ON_PRODUCT_LEVEL = "product"
    const val ADD_ON_ORDER_LEVEL = "order"

    const val EXTRA_DISTRICT_RECOMMENDATION_TOKEN = "DISTRICT_RECOMMENDATION_TOKEN"
    const val EXTRA_CURRENT_ADDRESS = "CURRENT_ADDRESS"
    const val EXTRA_MULTIPLE_ADDRESS_CHILD_INDEX = "EXTRA_MULTIPLE_ADDRESS_CHILD_INDEX"
    const val EXTRA_MULTIPLE_ADDRESS_DATA_LIST = "EXTRA_MULTIPLE_ADDRESS_DATA_LIST"
    const val EXTRA_MULTIPLE_ADDRESS_PARENT_INDEX = "EXTRA_MULTIPLE_ADDRESS_PARENT_INDEX"
    const val TYPE_REQUEST_ADD_SHIPMENT_DEFAULT_ADDRESS = 1
    const val TYPE_REQUEST_MULTIPLE_ADDRESS_ADD_SHIPMENT = 3
    const val TYPE_REQUEST_MULTIPLE_ADDRESS_CHANGE_ADDRESS = 2
    const val TYPE_REQUEST_SELECT_ADDRESS_FROM_COMPLETE_LIST = 0
    const val TYPE_REQUEST_EDIT_ADDRESS_FOR_TRADE_IN = 4
}