package com.tokopedia.purchase_platform.common.constant

const val ARGS_PROMO_REQUEST = "ARGS_PROMO_REQUEST"
const val ARGS_VALIDATE_USE_REQUEST = "ARGS_VALIDATE_USE_REQUEST"
const val ARGS_BBO_PROMO_CODES = "ARGS_BBO_PROMO_CODES"
const val ARGS_PAGE_SOURCE = "ARGS_PAGE_SOURCE"
const val ARGS_CHOSEN_ADDRESS = "ARGS_CHOSEN_ADDRESS"

const val ARGS_VALIDATE_USE_DATA_RESULT = "ARGS_VALIDATE_USE_DATA_RESULT"
const val ARGS_CLEAR_PROMO_RESULT = "ARGS_CLEAR_PROMO_RESULT"
const val ARGS_LAST_VALIDATE_USE_REQUEST = "ARGS_LAST_VALIDATE_USE_REQUEST";
const val ARGS_PROMO_MVC_LOCK_COURIER_FLOW = "ARGS_PROMO_MVC_LOCK_COURIER_FLOW"
const val ARGS_APPLIED_MVC_CART_STRINGS = "ARGS_APPLIED_MVC_CART_STRINGS"

const val PAGE_CART = 1
const val PAGE_CHECKOUT = 2
const val PAGE_OCC = 3

