#!/bin/bash

if [ -f ".remoteX/custom/custom_before_exec.sh" ]; then
printf """
chmod +x before_exec_customerapp.sh
./before_exec_customerapp.sh
""" >> .remoteX/custom/custom_before_exec.sh
fi
./remote -ci ./gradlew packageLiveDevDebugUniversalApk -p customerapp --stacktrace