#!/bin/bash

if [ -f ".remoteX/custom/custom_before_exec.sh" ]; then
> ".remoteX/custom/custom_before_exec.sh"
printf """#!/bin/bash
echo 'custom before exec by remote'
cd $1
curDirName=`pwd`
\n
if [ -f "$curDirName/settings.gradle" ]; then
sed -i 's|apply from: \"buildconfig/appcompile/compile-sellerapp.gradle\"||g' settings.gradle
sed -i 's|apply from: \"buildconfig/appcompile/compile-customerapp_pro.gradle\"||g' settings.gradle
sed -i 's|apply from: \"buildconfig/appcompile/compile-testing.gradle\"||g' settings.gradle
sed -i 's|apply from: \"buildconfig/appcompile/compile-libraries.gradle\"||g' settings.gradle
sed -i 's|apply from: \"buildconfig/appcompile/compile-customerapp.gradle\"||g' settings.gradle
sed -i 's|apply from: \"buildconfig/appcompile/compile-macrobenchmark.gradle\"||g' settings.gradle
sed -i 's|apply from: \"buildconfig/appcompile/compile-wearosapp.gradle\"||g' settings.gradle
fi""" >> .remoteX/custom/custom_before_exec.sh
fi

./remote -ci ./gradlew :testapp:assembleDebug