#!/bin/bash

curDir=$(pwd)

function echoStr() {
  echo "[33m  $1 [0m $2"
}

echo "Usage:"
echoStr "$ remote"

echo ""
echo "Commands:"
echo ""
echoStr "+ build" "           build and install apk to mobile"
echoStr "+ cleanBuild" "      cleanBuild and install apk to mobile"
echoStr "+ open" "            open remoteX web workspace"
echoStr "+ *" "               other command and call ./start.sh *"
echo ""

if [ ! -f "$curDir/start.sh" ]; then
  curl -H "Cache-Control: no-cache" http://tosv-cn.byted.org/obj/ttclient-android/release/remoteX.zip -o remoteX.zip &&
    unzip -o remoteX.zip &&
    rm -rf remoteX.zip &&
    chmod +x start.sh
fi

function getBuildTask() {
  function findModuleConfigFile() {
    local module_name=$1
    parent_dir=".idea/modules"
    config_file=$(find $parent_dir -name "*.$module_name.iml")
    if [ -f "$config_file" ]; then
      echo $config_file
    else
      echo ""
    fi
  }

  function parseBuildCommand() {
    # use bash args to choose module name
    local module_name=$1
    config_file=$(findModuleConfigFile $module_name)

    if [[ -z $config_file ]]; then
      echo ""
    else
      #  echo "config_file: $config_file"
      project_path=$(xmllint --xpath "string(//option[@name='GRADLE_PROJECT_PATH']/@value)" $config_file)
      assemble_task_name=$(xmllint --xpath "string(//option[@name='ASSEMBLE_TASK_NAME']/@value)" $config_file)
      command_line_options=$(xmllint --xpath "string(//option[@name='COMMAND_LINE_OPTIONS']/@value)" .idea/workspace.xml)
      #  echo "assemble_task: ${assemble_task_name}"
      #  echo "Compiler options: ${COMMAND_LINE_OPTIONS}"
      echo "${project_path}:${assemble_task_name} ${command_line_options}"
    fi
  }

  MODULE_NAME="app"
  BUILD_COMMAND=$(parseBuildCommand ${MODULE_NAME})

  echo $BUILD_COMMAND
}

if [[ $1 == "cleanBuild" ]]; then
  BUILD_COMMAND=$(getBuildTask)
  if [[ -z $BUILD_COMMAND ]]; then
    echo ""
    echo "[31m .idea/modules中, 未找到 *.$MODULE_NAME.iml, 请sync后在编译 [0m"
    echo "[31m 或者直接输入编译命令, rx -ci ./gradlew :app:aDCD 进行编译 [0m"
    echo ""
  else
    ./start.sh -ci "./gradlew clean ${BUILD_COMMAND} --console=rich"
  fi
elif [[ $1 == "build" ]]; then
  BUILD_COMMAND=$(getBuildTask)
  if [[ -z $BUILD_COMMAND ]]; then
    echo ""
    echo "[31m .idea/modules中, 未找到 *.$MODULE_NAME.iml, 请sync后在编译 [0m"
    echo "[31m 或者直接输入编译命令, rx -ci ./gradlew :app:aDCD 进行编译 [0m"
    echo ""
  else
    ./start.sh -ci "./gradlew ${BUILD_COMMAND} --console=rich"
  fi
elif [[ $1 == "open" ]]; then
  if [ -d "/Applications/Google Chrome.app" ]; then
    open -a "/Applications/Google Chrome.app" http://remotex.bytedance.net/remoteX
  else
    open -a "/Applications/Safari.app" http://remotex.bytedance.net/remoteX
  fi
else
  ./start.sh $@
fi
