package com.tokopedia.analyticsdebugger.serverlogger.presentation.uimodel

import com.tokopedia.abstraction.base.view.adapter.Visitable
import com.tokopedia.analyticsdebugger.serverlogger.presentation.adapter.ServerLoggerAdapterTypeFactory

interface BaseServerLoggerUiModel: Visitable<ServerLoggerAdapterTypeFactory>