package com.tokopedia.play.broadcaster.analytic.setup.cover

import com.tokopedia.play.broadcaster.ui.model.setup.AutoGeneratedCoverAnalyticModel

/**
 * Created By : Jonathan Darwin on February 04, 2022
 */
interface PlayBroSetupCoverAnalytic {

    fun clickAddNewCover()

    fun clickEditCover()

    fun clickCloseTemplateTabCoachMark()

    fun clickCoverTab(tabName: String)

    fun clickTemplateCoverAddProduct()

    fun clickCloseCoverBottomSheet()

    fun clickTryAgainTemplateCoverBottomSheet()

    fun clickSaveGeneratedCover(coverData: AutoGeneratedCoverAnalyticModel)

    fun clickDeleteGeneratedCover(coverData: AutoGeneratedCoverAnalyticModel)

    fun clickSelectGeneratedCover(coverData: AutoGeneratedCoverAnalyticModel)

    fun clickSaveGeneratedCoverOption(coverData: AutoGeneratedCoverAnalyticModel)

}
