package com.tokopedia.play.broadcaster.analytic.setup.cover

import com.tokopedia.play.broadcaster.ui.model.setup.AutoGeneratedCoverAnalyticModel

/**
 * Created By : Jonathan Darwin on February 04, 2022
 */
interface PlayBroSetupCoverAnalytic {

    fun clickAddNewCover()

    fun clickEditCover()

    fun clickCloseTemplateTabCoachMark()

    fun clickCoverTab(tabName: String, entryPoint: String)

    fun clickTemplateCoverAddProduct(entryPoint: String)

    fun clickCloseCoverBottomSheet(entryPoint: String)

    fun clickTryAgainTemplateCoverBottomSheet(entryPoint: String)

    fun clickSaveGeneratedCover(coverData: AutoGeneratedCoverAnalyticModel, entryPoint: String)

    fun clickDeleteGeneratedCover(coverData: AutoGeneratedCoverAnalyticModel, entryPoint: String)

    fun clickSelectGeneratedCover(coverData: AutoGeneratedCoverAnalyticModel, entryPoint: String)

    fun clickSaveGeneratedCoverOption(coverData: AutoGeneratedCoverAnalyticModel, entryPoint: String)

}
