package com.tokopedia.play.broadcaster.analytic.setup.cover

import com.tokopedia.content.analytic.BusinessUnit
import com.tokopedia.content.analytic.Event
import com.tokopedia.content.analytic.Key
import com.tokopedia.play.broadcaster.analytic.KEY_TRACK_CATEGORY_PLAY
import com.tokopedia.play.broadcaster.analytic.KEY_TRACK_CLICK_EVENT
import com.tokopedia.play.broadcaster.analytic.currentSite
import com.tokopedia.play.broadcaster.analytic.getTrackerId
import com.tokopedia.play.broadcaster.analytic.sessionIris
import com.tokopedia.play.broadcaster.data.config.HydraConfigStore
import com.tokopedia.play.broadcaster.ui.model.setup.AutoGeneratedCoverAnalyticModel
import com.tokopedia.track.builder.Tracker
import com.tokopedia.user.session.UserSessionInterface
import javax.inject.Inject

/**
 * Created By : Jonathan Darwin on February 04, 2022
 */
class PlayBroSetupCoverAnalyticImpl @Inject constructor(
    private val userSession: UserSessionInterface,
    private val hydraConfig: HydraConfigStore
) : PlayBroSetupCoverAnalytic {

    private val userId = userSession.userId
    private val authorId: String
        get() = hydraConfig.getAuthorId()
    private val authorTypeName: String
        get() = hydraConfig.getAuthorTypeName()

    override fun clickAddNewCover() {
        Tracker.Builder()
            .setEvent(KEY_TRACK_CLICK_EVENT)
            .setEventAction("click - cover thumbnail to add cover")
            .setEventCategory(KEY_TRACK_CATEGORY_PLAY)
            .setEventLabel(userId)
            .setBusinessUnit(BusinessUnit.play)
            .setCurrentSite(currentSite)
            .setCustomProperty(Key.sessionIris, sessionIris)
            .setUserId(userId)
            .setCustomProperty(Key.trackerId, getTrackerId("30214", "26713"))
            .build()
            .send()
    }

    override fun clickEditCover() {
        Tracker.Builder()
            .setEvent(KEY_TRACK_CLICK_EVENT)
            .setEventAction("click - edit cover")
            .setEventCategory(KEY_TRACK_CATEGORY_PLAY)
            .setEventLabel(userSession.userId)
            .setBusinessUnit(BusinessUnit.play)
            .setCurrentSite(currentSite)
            .setCustomProperty(Key.sessionIris, sessionIris)
            .setUserId(userId)
            .setCustomProperty(Key.trackerId, getTrackerId("30217", "26716"))
            .build()
            .send()
    }

    override fun clickCloseTemplateTabCoachMark() {
        Tracker.Builder()
            .setEvent(Event.clickContent)
            .setEventAction("click - x template tab")
            .setEventCategory(KEY_TRACK_CATEGORY_PLAY)
            .setCustomProperty(Key.trackerId, getTrackerId("40737", "40703"))
            .setEventLabel("$authorId - $authorTypeName")
            .setBusinessUnit(BusinessUnit.play)
            .setCurrentSite(currentSite)
            .setCustomProperty(Key.sessionIris, sessionIris)
            .setUserId(userId)
            .build()
            .send()
    }

    override fun clickCoverTab(tabName: String, entryPoint: String) {
        Tracker.Builder()
            .setEvent(Event.clickContent)
            .setEventAction("click - cover tab")
            .setEventCategory(KEY_TRACK_CATEGORY_PLAY)
            .setCustomProperty(Key.trackerId, getTrackerId("40738", "40704"))
            .setEventLabel("$authorId - $authorTypeName - $tabName - $entryPoint")
            .setBusinessUnit(BusinessUnit.play)
            .setCurrentSite(currentSite)
            .setCustomProperty(Key.sessionIris, sessionIris)
            .setUserId(userId)
            .build()
            .send()
    }

    override fun clickTemplateCoverAddProduct(entryPoint: String) {
        Tracker.Builder()
            .setEvent(Event.clickContent)
            .setEventAction("click - template tambah produk")
            .setEventCategory(KEY_TRACK_CATEGORY_PLAY)
            .setCustomProperty(Key.trackerId, getTrackerId("40739", "40705"))
            .setEventLabel("$authorId - $authorTypeName - $entryPoint")
            .setBusinessUnit(BusinessUnit.play)
            .setCurrentSite(currentSite)
            .setCustomProperty(Key.sessionIris, sessionIris)
            .setUserId(userId)
            .build()
            .send()
    }

    override fun clickCloseCoverBottomSheet(entryPoint: String) {
        Tracker.Builder()
            .setEvent(Event.clickContent)
            .setEventAction("click - x cover bottomsheet")
            .setEventCategory(KEY_TRACK_CATEGORY_PLAY)
            .setCustomProperty(Key.trackerId, getTrackerId("40740", "40706"))
            .setEventLabel("$authorId - $authorTypeName - $entryPoint")
            .setBusinessUnit(BusinessUnit.play)
            .setCurrentSite(currentSite)
            .setCustomProperty(Key.sessionIris, sessionIris)
            .setUserId(userId)
            .build()
            .send()
    }

    override fun clickTryAgainTemplateCoverBottomSheet(entryPoint: String) {
        Tracker.Builder()
            .setEvent(Event.clickContent)
            .setEventAction("click - coba lagi template cover")
            .setEventCategory(KEY_TRACK_CATEGORY_PLAY)
            .setCustomProperty(Key.trackerId, getTrackerId("40741", "40708"))
            .setEventLabel("$authorId - $authorTypeName - $entryPoint")
            .setBusinessUnit(BusinessUnit.play)
            .setCurrentSite(currentSite)
            .setCustomProperty(Key.sessionIris, sessionIris)
            .setUserId(userId)
            .build()
            .send()
    }

    override fun clickSaveGeneratedCover(
        coverData: AutoGeneratedCoverAnalyticModel,
        entryPoint: String
    ) {
        Tracker.Builder()
            .setEvent(Event.clickContent)
            .setEventAction("click - save generated cover")
            .setEventCategory(KEY_TRACK_CATEGORY_PLAY)
            .setCustomProperty(Key.trackerId, getTrackerId("40742", "40709"))
            .setEventLabel("$authorId - $authorTypeName - ${coverData.coverId} - ${coverData.coverPosition + 1} - ${coverData.coverColor} - $entryPoint")
            .setBusinessUnit(BusinessUnit.play)
            .setCurrentSite(currentSite)
            .setCustomProperty(Key.sessionIris, sessionIris)
            .setUserId(userId)
            .build()
            .send()
    }

    override fun clickDeleteGeneratedCover(
        coverData: AutoGeneratedCoverAnalyticModel,
        entryPoint: String
    ) {
        Tracker.Builder()
            .setEvent(Event.clickContent)
            .setEventAction("click - delete generated cover")
            .setEventCategory(KEY_TRACK_CATEGORY_PLAY)
            .setCustomProperty(Key.trackerId, getTrackerId("40743", "40710"))
            .setEventLabel("$authorId - $authorTypeName - ${coverData.coverId} - ${coverData.coverPosition + 1} - ${coverData.coverColor} - $entryPoint")
            .setBusinessUnit(BusinessUnit.play)
            .setCurrentSite(currentSite)
            .setCustomProperty(Key.sessionIris, sessionIris)
            .setUserId(userId)
            .build()
            .send()
    }

    override fun clickSelectGeneratedCover(
        coverData: AutoGeneratedCoverAnalyticModel,
        entryPoint: String
    ) {
        Tracker.Builder()
            .setEvent(Event.clickContent)
            .setEventAction("click - generated cover")
            .setEventCategory(KEY_TRACK_CATEGORY_PLAY)
            .setCustomProperty(Key.trackerId, getTrackerId("40744", "40711"))
            .setEventLabel("$authorId - $authorTypeName - ${coverData.coverId} - ${coverData.coverPosition + 1} - ${coverData.coverColor} - $entryPoint")
            .setBusinessUnit(BusinessUnit.play)
            .setCurrentSite(currentSite)
            .setCustomProperty(Key.sessionIris, sessionIris)
            .setUserId(userId)
            .build()
            .send()
    }

    override fun clickSaveGeneratedCoverOption(
        coverData: AutoGeneratedCoverAnalyticModel,
        entryPoint: String
    ) {
        Tracker.Builder()
            .setEvent(Event.clickContent)
            .setEventAction("click - save generated cover option")
            .setEventCategory(KEY_TRACK_CATEGORY_PLAY)
            .setCustomProperty(Key.trackerId, getTrackerId("40745", "40712"))
            .setEventLabel("$authorId - $authorTypeName - ${coverData.coverId} - ${coverData.coverPosition + 1} - ${coverData.coverColor} - $entryPoint")
            .setBusinessUnit(BusinessUnit.play)
            .setCurrentSite(currentSite)
            .setCustomProperty(Key.sessionIris, sessionIris)
            .setUserId(userId)
            .build()
            .send()
    }
}
