package com.tokopedia.mvc.domain.entity

data class VoucherDetailData(
    val voucherId: Long,
    val shopId: Long,
    val voucherName: String,
    val voucherType: Int,
    val voucherImage: String,
    val voucherImageSquare: String,
    val voucherImagePortrait: String,
    val voucherStatus: Int,
    val voucherDiscountType: Int,
    val voucherDiscountAmount: Long,
    val voucherDiscountAmountMax: Long,
    val voucherDiscountAmountMin: Long,
    val voucherQuota: Long,
    val voucherStartTime: String,
    val voucherFinishTime: String,
    val voucherCode: String,
    val galadrielVoucherId: Long,
    val galadrielCatalogId: Long,
    val createTime: String,
    val createBy: Long,
    val updateTime: String,
    val updateBy: Int,
    val isPublic: Int,
    val isQuotaAvailable: Int,
    val voucherTypeFormatted: String,
    val voucherStatusFormatted: String,
    val voucherDiscountTypeFormatted: String,
    val voucherDiscountAmountFormatted: String,
    val voucherDiscountAmountMaxFormatted: String,
    val remainingQuota: Long,
    val tnc: String,
    val bookedGlobalQuota: Long,
    val confirmedGlobalQuota: Long,
    val targetBuyer: Int,
    val minimumTierLevel: Int,
    val isLockToProduct: Int,
    val isVps: Int,
    val packageName: String,
    val vpsUniqueId: Long,
    val voucherPackageId: Long,
    val vpsBundlingId: Long,
    val isSubsidy: Int,
    val appLink: String,
    val webLink: String,
    val warehouseId: Long,
    val voucherMinimumAmountType: Int,
    val voucherMinimumAmountTypeFormatted: String,
    val isPeriod: Boolean,
    val totalPeriod: Int,
    val voucherLockType: String,
    val voucherLockId: Long,
    val productIds: List<ProductId>
) {
    data class ProductId(
        val parentProductId: Long,
        val chilProductId: List<Long>?,
    )
}

