package com.tokopedia.review.feature.createreputation.analytics

object CreateReviewTrackingConstants {
    const val EVENT_CATEGORY = "product review detail page"
    const val CLICK_EXPAND_TEXTBOX = "click - expand textbox"
    const val CLICK_COLLAPSE_TEXT_BOX = "click - collapse textbox"
    const val VIEW_SMILEY = "view - smiley components"
    const val EVENT_LABEL_ORDER_ID_PRODUCT_ID = "order id:%s; product id:%s;"
    const val VIEW_DIALOG = "view - pop up %s"
    const val EMPTY_LABEL = ""
    const val CLICK_CONTINUE_IN_DIALOG = "click - lanjut tulis ulasan on %s"
    const val CLICK_LEAVE_PAGE = "click - ya keluar on %s"
    const val CLICK_COMPLETE_REVIEW_FIRST = "click - lengkapi ulasan dulu on %s"
    const val CLICK_SEND_NOW = "click - kirim sekarang aja on %s"
    const val CLICK_SEND_ANOTHER = "click - kirim ulasan lagi on %s"
    const val EVENT_LABEL_PENDING_INCENTIVE_QUEUE = "has pending incentive review queue:%s;"
    const val CLICK_LATER = "click - nanti aja deh on %s"
    const val CLICK_OK = "click - ok sip on %s"
    const val SCREEN_NAME = "/create-review-form"
    const val EVENT_CATEGORY_REVIEW_BOTTOM_SHEET = "product review detail page - create review form bottomsheet"
    const val EVENT_ACTION_VIEW_SEND_RATING_DIALOG = "view - mau kirim rating aja pop up"
    const val EVENT_ACTION_VIEW_UNSAVED_DIALOG = "view - ulasanmu nanti hilang pop up"
    const val KEY_BUSINESS_UNIT = "businessUnit"
    const val KEY_CURRENT_SITE = "currentSite"
    const val BUSINESS_UNIT = "product detail page"
    const val CURRENT_SITE = "tokopediamarketplace"
    const val KEY_PRODUCT_ID = "productId"
    const val EVENT_LABEL_VIEW_DIALOG = "pop up title:%s;reputation_id:%s;order_id:%s;product_id:%s;"
    const val EVENT_ACTION_CLICK_SEND_RATING_OPTION = "click - kirim rating on pop up"
    const val EVENT_ACTION_CLICK_STAY_OPTION = "click - tetap disini on pop up"
    const val EVENT_ACTION_CLICK_TEMPLATE = "click - review template"
    const val EVENT_LABEL_CLICK_TEMPLATE = "template:%s;reputation_id:%s;order_id:%s;product_id:%s;"
}