package com.tokopedia.play.broadcaster.ui.viewholder.setup

import android.view.LayoutInflater
import android.view.ViewGroup
import androidx.recyclerview.widget.RecyclerView
import com.tokopedia.play.broadcaster.databinding.ItemSetupCoverAutoGeneratedBinding
import com.tokopedia.play.broadcaster.ui.model.setup.AutoGeneratedCoverIUIModel
import timber.log.Timber

class PlayAutoGeneratedCoverViewHolder(
    private val binding: ItemSetupCoverAutoGeneratedBinding,
) : RecyclerView.ViewHolder(binding.root) {

    fun bind(data: AutoGeneratedCoverIUIModel) {
        Timber.d(bindingAdapterPosition.toString())
        Timber.d(binding.rbSelectedAutoGeneratedCover.toString())
    }

    companion object {
        fun create(parent: ViewGroup) = PlayAutoGeneratedCoverViewHolder(
            ItemSetupCoverAutoGeneratedBinding.inflate(
                LayoutInflater.from(parent.context),
                parent,
                false,
            ),
        )
    }

}
