package com.tokopedia.discovery2


enum class ComponentNames(val componentName: String) {
    Default("default"),
    SingleBanner("banner_image"),
    DoubleBanner("banner_image_double"),
    TripleBanner("banner_image_triple"),
    QuadrupleBanner("banner_image_quadruple"),
    Share("share"),
    HorizontalCategoryNavigation("horizontal_category_navigation"),
    HorizontalCategoryNavigationIem("horizontal_category_navigation_item"),
    BrandRecommendation("brand_recommendation"),
    BrandRecommendationItem("brand_recommendation_item"),
    CarouselBanner("carousel_banner"),
    CarouselBannerItemView("carousel_banner_item"),
    SliderBanner("slider_banner"),
    BannerTimer("timer_with_banner"),
    Tokopoints("tokopoints"),
    TokopointsItem("tokopoints_item"),
    LihatSemua("lihat_semua"),
    CpmTopAds("topads"),
    CpmTopAdsShopItem("cpm_topads_shop_item"),
    CpmTopAdsProductItem("cpm_topads_product_item"),
    Video("video"),
    Notifier("notifier"),
    TitleImage("title_image"),
    TextComponent("text_component"),
    ClaimCoupon("claim_coupon"),
    ClaimCouponItem("claim_coupon_item"),
    Margin("margin"),
    CustomTopchat("custom_topchat"),
    ChipsFilter("chips_filter"),
    ChipsFilterItem("chips_filter_item"),
    Tabs("tabs"),
    TabsItem("tabs_item"),
    DynamicCategory("dynamic_category"),
    DynamicCategoryItem("dynamic_category_item"),
    FlashSaleTimer("flash_sale_timer"),
    ProductCardRevamp("product_card_revamp"),
    ProductCardCarousel("product_card_carousel"),
    PrductCardSprintSaleCarousel("product_card_sprint_sale_carousel"),
    ProductCardItem("product_card_item"),
    TimerSprintSale("timer_sprint_sale"),
    ProductCardHorizontalItem("product_card_horizontal_item"),
    ShimmerProductCard("shimmer_product_card"),
    Shimmer("shimmer")
}
