package com.tokopedia.shop.analytic

/**
 * Created by zulfikarrahman on 3/12/18.
 */
object OldShopPageTrackingConstant {
    const val FEATURED_PRODUCT = "Produk Unggulan"

    //event
    const val CLICK_SHOP_PAGE = "clickShopPage"
    const val VIEW_SHOP_PAGE = "viewShopPage"
    const val PROMO_VIEW = "promoView"
    const val PROMO_CLICK = "promoClick"
    const val CLICK_SHOP_MANAGE = "clickManageShop"
    const val CLICK_SHOP_MESSAGE = "clickMessageShop"
    const val CLICK_TOP_NAV = "clickTopNav"
    const val SELLER_ADDED_TO_FAVORITE = "Seller_Added_To_Favorite"
    const val SELLER_REMOVED_FROM_FAVORITE = "Seller_Removed_From_Favorite"
    const val CLICK_MEMBERSHIP_EVENT = "clickShopPage"

    //category
    const val SHOP_PAGE_SELLER = "shop page - seller"
    const val SHOP_PAGE_BUYER = "shop page - buyer"
    const val SHOP_PAGE = "shop page"
    const val TOP_NAV = "top nav - %s"
    const val MEMBERSHIP_SHOP_PAGE = "membership - shop page"

    //ACTION
    const val TOP_SECTION = "top section"
    const val INFO = "info"
    const val MERCHANT_VOUCHER_CODE = "merchant voucher code"
    const val MERCHANT_VOUCHER = "merchant voucher"
    const val PROMO_BANNER = "promo banner"
    const val MANAGE_SHOP = "manage shop"
    const val MANAGE_PRODUCT = "manage product"
    const val CLICK = "click"
    const val CLICK_MESSAGE_SELLER = "click message seller"
    const val FOLLOW = "follow"
    const val UNFOLLOW = "unfollow"
    const val SEARCH_BAR = "search bar"
    const val PRODUCT_NAVIGATION = "product navigation"
    const val IMPRESSION = "impression"
    const val CLICK_SEND_CHAT = "click on kirim pesan"
    const val SHOP_SEARCH_PRODUCT_CLICK_CART_BUTTON = "click cart button - search result"
    const val SHOP_SEARCH_PRODUCT_CLICK_SHARE_BUTTON = "click share button - search result"
    const val SHOP_SEARCH_PRODUCT_CLICK_SEARCH_BOX = "click search box"
    const val SHOP_SEARCH_PRODUCT_CLICK_SEARCH = "click - search"
    const val SHOP_SEARCH_PRODUCT_CLICK_ETALASE_AUTOCOMPLETE = "click - etalase autocomplete"
    const val SHOP_SEARCH_PRODUCT_CLICK_GLOBAL_SEARCH = "click - global autocomplete"
    const val SHOP_SEARCH_PRODUCT_CLICK_PRODUCT_AUTOCOMPLETE = "click - global autocomplete"

    //label
    const val CLICK_TAB = "click tab"
    const val CLICK_SHARE_BUTTON = "click share button"
    const val CLICK_CART_BUTTON = "click cart button"
    const val CLICK_REQUEST_OPEN_SHOP = "click request open shop"
    const val IMPRESSION_OF_REQUEST_OPEN_SHOP = "impression of request open shop"
    const val SEARCH_RESULT = "search result"
    const val NO_SEARCH_RESULT = "no search result"
    const val IMPRESSION_OPEN_OPERATIONAL_SHOP = "impression of open operational shop"
    const val CLICK_OPEN_OPERATIONAL_SHOP = "click open operational shop"
    const val IMPRESSION_HOW_TO_ACTIVATE_SHOP = "impression of how to activate shop"
    const val CLICK_HOW_TO_ACTIVATE_SHOP = "click how to activate shop"
    const val CLICK_FOLLOW_FROM_ZERO_FOLLOWER = "click follow from zero follower"
    const val IMPRESSION_FOLLOW_FROM_ZERO_FOLLOWER = "impression of follow from zero follower"
    const val CLICK_MENU_FROM_MORE_MENU = "click menu from more menu"
    const val CLICK_WISHLIST = "click wishlist"
    const val ADD = "add"
    const val REMOVE = "remove"
    const val CLICK_SORT = "click sort"
    const val LIST = "list"
    const val CLICK_SORT_BY = "click sort by"
    const val CLICK_ADD_PRODUCT = "click add product"
    const val CLICK_FOLLOWER_LIST = "click follower list"
    const val CLICK_ADD_NOTE = "click add note"
    const val SEE_ALL = "see all"
    const val MVC_DETAIL = "mvc detail"
    const val USE_VOUCHER = "use voucher"
    const val CLICK_PRODUCT_PICTURE = "click product picture"
    const val IMPRESSION_OF_PRODUCT_LIST = "impression of product list"
    const val CLICK_VIEW_ALL = "click view all"
    const val CLICK_ADD_PRODUCT_FROM_ZERO_PRODUCT = "click add product from zero product"
    const val IMPRESSION_ADD_PRODUCT_FROM_ZERO_PRODUCT = "impression of add product from zero product"
    const val CLICK_READ_NOTES = "click read notes"
    const val CLICK_REVIEW = "click review"
    const val CLICK_DISCUSSION = "click discussion"
    const val CLICK_MANAGE_SHOP = "click manage shop"
    const val SHOP_INFO = "Shop Info"
    const val LABEL_SHOP_SEARCH_PRODUCT_KEYWORD_PAGEURL = "keyword:  %s - page: %s"
    const val LABEL_SHOP_SEARCH_PRODUCT_KEYWORD_VALUE_PAGEURL = "keyword:  %s - value: %s - page:%s"
    const val MEMBERSHIP_CLICK_MEMBER = "click daftar jadi member"
    const val MEMBERSHIP_DETAIL_PAGE = "click membership detail page"
    const val MEMBERSHIP_COUPON_CLAIM = "click klaim kupon"
    const val MEMBERSHIP_COUPON_CHECK = "click cek kupon saya"

    //key
    const val EVENT = "event"
    const val EVENT_CATEGORY = "eventCategory"
    const val EVENT_ACTION = "eventAction"
    const val EVENT_LABEL = "eventLabel"
    const val EVENT_PROMO_ID = "promoId"
    const val EVENT_PRODUCT_ID = "productId"
    const val SHOP_ID = "shop_id"
    const val SHOP_NAME = "shop_name"
    const val PAGE_TYPE = "page_type"
    const val PRODUCT_ID = "product_id"
    const val ECOMMERCE = "ecommerce"
    const val ACTION_FIELD = "actionField"
    const val SHOPPAGE = "/shoppage"
    const val SEARCH = "search"
    const val PRODUCT = "product"
    const val PRODUCTS = "products"
    const val NAME = "name"
    const val CREATIVE = "creative"
    const val CREATIVE_URL = "creative_url"
    const val PROMO_ID = "promo_id"
    const val PROMO_CODE = "promo_code"
    const val ID = "id"
    const val PRICE = "price"
    const val BRAND = "brand"
    const val CATEGORY = "category"
    const val VARIANT = "variant"
    const val POSITION = "position"
    const val ATTRIBUTION = "attribution"
    const val NONE = "none"
    const val CURRENCY_CODE = "currencyCode"
    const val IDR = "IDR"
    const val IMPRESSIONS = "impressions"
    const val CLICK_MENU = "click menu"
    const val CLICK_MORE_MENU = "click more menu"
    const val SHOP_TYPE = "shop_type"
    const val PRODUCT_CLICK = "productClick"
    const val PRODUCT_VIEW = "productView"
    const val ALL_ETALASE = "Semua Etalase"
    const val PROMOTIONS = "promotions"
    const val DIMENSION83 = "dimension83"
    const val FREE_ONGKIR = "bebas ongkir"
    const val NONE_OR_OTHER = "none / other"
    const val SHOP_LOCATION = "shop_location"
    const val URL_SLUG = "url_slug"
    const val IS_OFFICIAL_STORE = "is_official_store"

    //SCREEN/PAGES
    const val SCREEN_SHOP_PAGE = "Shop Page"
    const val SCREEN_SEARCH_BAR = "Search Bar"

    //value
    const val VALUE_PRODUCT = "Product"

    //page_url
    const val ETALASE_SHOPNAME = "etalase-%s"
    const val SRP_SHOPNAME = "srp-%s"
}