package com.tokopedia.play.broadcaster.view.adapter

import com.tokopedia.adapterdelegate.BaseDiffUtilAdapter
import com.tokopedia.play.broadcaster.ui.model.setup.AutoGeneratedCoverIUModel
import com.tokopedia.play.broadcaster.view.adapter.delegate.PlayAutoGeneratedCoverAdapterDelegate

/**
 * Created by fachrizalmrsln on 16/01/23
 */
class PlayAutoGeneratedCoverAdapter(
    listener: Listener
) : BaseDiffUtilAdapter<PlayAutoGeneratedCoverAdapter.Model>() {

    init {
        delegatesManager
            .addDelegate(PlayAutoGeneratedCoverAdapterDelegate.PlayAutoGeneratedCover(listener))
    }

    override fun areItemsTheSame(oldItem: Model, newItem: Model): Boolean {
        return when {
            oldItem is Model.PlayAutoGeneratedCoverModel &&
                newItem is Model.PlayAutoGeneratedCoverModel -> {
                oldItem.data.id == newItem.data.id
            }
            else -> oldItem == newItem
        }
    }

    override fun areContentsTheSame(oldItem: Model, newItem: Model): Boolean {
        return oldItem == newItem
    }

    sealed interface Model {
        data class PlayAutoGeneratedCoverModel(val data: AutoGeneratedCoverIUModel) : Model
    }

    interface Listener {
        fun onClickItem(data: AutoGeneratedCoverIUModel, position: Int)
    }

}

