package com.tokopedia.play.broadcaster.view.adapter

import com.tokopedia.adapterdelegate.BaseDiffUtilAdapter
import com.tokopedia.play.broadcaster.ui.model.setup.AutoGeneratedCoverIUIModel
import com.tokopedia.play.broadcaster.view.adapter.delegate.PlayAutoGeneratedCoverAdapterDelegate

class PlayAutoGeneratedCoverAdapter : BaseDiffUtilAdapter<PlayAutoGeneratedCoverAdapter.Model>() {

    init {
        delegatesManager
            .addDelegate(PlayAutoGeneratedCoverAdapterDelegate.PlayAutoGeneratedCover())
    }

    override fun areItemsTheSame(oldItem: Model, newItem: Model): Boolean {
        return oldItem == newItem
    }

    override fun areContentsTheSame(oldItem: Model, newItem: Model): Boolean {
        return oldItem == newItem
    }

    sealed interface Model {
        data class PlayAutoGeneratedCoverModel(val data: AutoGeneratedCoverIUIModel) : Model
    }

}

