package com.tokopedia.play.broadcaster.view.adapter

import com.tokopedia.adapterdelegate.BaseDiffUtilAdapter
import com.tokopedia.play.broadcaster.ui.model.setup.AutoGeneratedCoverUIModel
import com.tokopedia.play.broadcaster.view.adapter.delegate.PlayAutoGeneratedCoverAdapterDelegate

/**
 * Created by fachrizalmrsln on 16/01/23
 */
class PlayAutoGeneratedCoverAdapter(
    userAccessToken: String,
    listener: Listener
) : BaseDiffUtilAdapter<AutoGeneratedCoverUIModel>() {

    init {
        delegatesManager
            .addDelegate(PlayAutoGeneratedCoverAdapterDelegate.PlayAutoGeneratedCover(userAccessToken, listener))
    }

    override fun areItemsTheSame(oldItem: AutoGeneratedCoverUIModel, newItem: AutoGeneratedCoverUIModel): Boolean {
        return run {
            oldItem.imageUrl == newItem.imageUrl
        }
    }

    override fun areContentsTheSame(oldItem: AutoGeneratedCoverUIModel, newItem: AutoGeneratedCoverUIModel): Boolean {
        return oldItem == newItem
    }

    interface Listener {
        fun onClickItem(data: AutoGeneratedCoverUIModel, position: Int)
        fun onFailLoadResources(exception: Exception?)
    }

}

