package com.tokopedia.tokopedianow.similarproduct.analytic

object TokonowSimilarProductConstants {
    const val TRACKER_ID_CLICK_SIMILAR_PRODUCT_BUTTON = "39574"
    const val TRACKER_ID_VIEW_SIMILAR_PRODUCT_BOTTOMSHEET = "39575"
    const val TRACKER_ID_CLICK_PRODUCT = "39576"
    const val TRACKER_ID_ADD_TO_CART = "39577"
    const val TRACKER_ID_CLICK_CLOSE_BOTTOMSHEET = "39578"
    const val TRACKER_ID_VIEW_EMPTY_STATE = "39579"

    const val TRACKER_ID_CLICK_SIMILAR_PRODUCT_BUTTON_CATEGORY = "39603"
    const val TRACKER_ID_VIEW_SIMILAR_PRODUCT_BOTTOMSHEET_CATEGORY = "39604"
    const val TRACKER_ID_CLICK_PRODUCT_CATEGORY = "39605"
    const val TRACKER_ID_ADD_TO_CART_CATEGORY = "39606"
    const val TRACKER_ID_CLICK_CLOSE_BOTTOMSHEET_CATEGORY = "39607"
    const val TRACKER_ID_VIEW_EMPTY_STATE_CATEGORY = "39608"

}
