package com.tokopedia.talk.common.analytics

object TalkTrackingConstants {
    const val TRACKING_EVENT = "event"
    const val TRACKING_EVENT_CATEGORY = "eventCategory"
    const val TRACKING_EVENT_ACTION = "eventAction"
    const val TRACKING_EVENT_LABEL = "eventLabel"
    const val TRACKING_SCREEN_NAME = "screenName"
    const val TRACKING_CURRENT_SITE = "currentSite"
    const val TRACKING_USER_ID = "userId"
    const val TRACKING_BUSINESS_UNIT = "businessUnit"
    const val TRACKING_PRODUCT_ID = "productId"
    const val TRACKING_IS_LOGGED_IN = "isLoggedInStatus"
    const val TRACKING_ECOMMERCE = "ecommerce"
    const val TRACKING_CURRENCY_CODE = "currencyCode"
    const val TRACKING_CLICK = "click"
    const val TRACKING_IMPRESSIONS = "impressions"
    const val TRACKING_ACTION_FIELD = "actionField"
    const val TRACKING_PRODUCTS = "products"
    const val TRACKING_NAME = "name"
    const val TRACKING_ID = "id"
    const val TRACKING_LIST = "list"
    const val TRACKING_POSITION = "position"
    const val TRACKING_PROMOTIONS = "promotions"
    const val TRACKING_CREATIVE = "creative"
    const val TRACKING_CREATIVE_URL = "creative_url"
    const val TRACKING_SHOP_ID = "shopId"

    const val EVENT_ACTION_CLICK = "click -"
    const val EVENT_TALK = "clickPDP"
    const val EVENT_OPEN_SCREEN = "openScreen"
    const val BUSINESS_UNIT_TALK = "physical goods"
    const val CURRENT_SITE_TALK = "tokopediamarketplace"
    const val EVENT_CATEGORY_TALK = "product talk"
    const val SCREEN_NAME_TALK = "/product-talk"
    const val IDR_CURRENCY = "IDR"
    const val EVENT_CATEGORY_INBOX_PRODUCT = "inbox talk - %s"
    const val BUSINESS_UNIT_TALK_INBOX = "product detail page"
}