package com.tokopedia.home_recom.model.dataModel

import com.tokopedia.abstraction.base.view.adapter.Visitable
import com.tokopedia.home_recom.view.adapter.homerecommendation.HomeRecommendationTypeFactory

interface BaseHomeRecommendationDataModel: Visitable<HomeRecommendationTypeFactory>