package com.tokopedia.logisticcart.shipping.model

import android.os.Parcelable
import com.tokopedia.purchase_platform.common.feature.ethicaldrug.data.model.EthicalDrugDataModel
import com.tokopedia.purchase_platform.common.feature.gifting.data.model.AddOnsDataModel
import kotlinx.parcelize.Parcelize

@Parcelize
data class CartItemModel(
        var cartId: Long = 0,
        var shopId: String = "",
        var shopName: String = "",
        var productId: Long = 0,
        var productCatId: Long = 0,
        var name: String = "",
        var price: Double = 0.0,
        var originalPrice: Double = 0.0,
        var currency: Int = 0,
        var variant: String = "",
        var variantParentId: String = "",
        var weightUnit: Int = 0,
        var weight: Double = 0.0,
        var weightFmt: String = "",
        var weightActual: Double = 0.0,
        var quantity: Int = 0,
        var noteToSeller: String = "",
        var imageUrl: String = "",
        var cashback: String = "",
        var preOrderDurationDay: Int = 0,
        var isCashback: Boolean = false,
        var isPreOrder: Boolean = false,
        var isFreeReturn: Boolean = false,
        var fInsurance: Boolean = false,
        var fCancelPartial: Boolean = false,
        var isError: Boolean = false,
        var isShopError: Boolean = false,
        var errorMessage: String = "",
        var errorMessageDescription: String = "",
        var isProtectionAvailable: Boolean = false,
        var protectionPricePerProduct: Int = 0,
        var protectionPrice: Double = 0.0,
        var protectionSubTitle: String = "",
        var protectionTitle: String = "",
        var protectionLinkText: String = "",
        var protectionLinkUrl: String = "",
        var isProtectionOptIn: Boolean = false,
        var isProtectionCheckboxDisabled: Boolean = false,
        var preOrderInfo: String = "",
        var isFreeShipping: Boolean = false,
        var isFreeShippingExtra: Boolean = false,
        var freeShippingName: String = "",
        var isShowTicker: Boolean = false,
        var tickerMessage: String = "",
        var isWholesalePrice: Boolean = false,
        var analyticsProductCheckoutData: AnalyticsProductCheckoutData = AnalyticsProductCheckoutData(),
        var isValidTradeIn: Boolean = false,
        var newDevicePrice: Long = 0,
        var oldDevicePrice: Long = 0,
        var deviceModel: String = "",
        var diagnosticId: String = "",
        var productInformation: List<String> = emptyList(),
        var productAlertMessage: String = "",
        var isBundlingItem: Boolean = false,
        var bundlingItemPosition: Int = 0,
        var bundleId: String = "",
        var bundleGroupId: String = "",
        var bundleType: String = "",
        var bundleTitle: String = "",
        var bundlePrice: Double = 0.0,
        var bundleSlashPriceLabel: String = "",
        var bundleOriginalPrice: Double = 0.0,
        var bundleQuantity: Int = 0,
        var bundleIconUrl: String = "",
        var addOnProductLevelModel: AddOnsDataModel = AddOnsDataModel(),
        var addOnDefaultFrom: String = "",
        var addOnDefaultTo: String = "",
        var isTokoCabang: Boolean = false,
        var cartString: String = "",
        var warehouseId: String = "",
        var ethicalDrugDataModel : EthicalDrugDataModel = EthicalDrugDataModel()
) : Parcelable
