package com.tokopedia.logisticcart.shipping.model

import android.os.Parcelable
import com.tokopedia.purchase_platform.common.feature.addons.data.model.AddOnProductDataModel
import com.tokopedia.purchase_platform.common.feature.ethicaldrug.data.model.EthicalDrugDataModel
import com.tokopedia.purchase_platform.common.feature.gifting.data.model.AddOnGiftingDataModel
import com.tokopedia.purchase_platform.common.feature.gifting.data.model.AddOnGiftingWordingModel
import kotlinx.parcelize.Parcelize

@Parcelize
data class CartItemModel(
    val cartId: Long = 0,
    val shopId: String = "",
    val shopName: String = "",
    val productId: Long = 0,
    val productCatId: Long = 0,
    val name: String = "",
    val price: Double = 0.0,
    val originalPrice: Double = 0.0,
    val currency: Int = 0,
    val variant: String = "",
    val variantParentId: String = "",
    val weightUnit: Int = 0,
    val weight: Double = 0.0,
    val weightFmt: String = "",
    val weightActual: Double = 0.0,
    val quantity: Int = 0,
    val noteToSeller: String = "",
    val imageUrl: String = "",
    val cashback: String = "",
    val preOrderDurationDay: Int = 0,
    val isCashback: Boolean = false,
    val isPreOrder: Boolean = false,
    val isFreeReturn: Boolean = false,
    val fInsurance: Boolean = false,
    val fCancelPartial: Boolean = false,
    var isError: Boolean = false,
    var isShopError: Boolean = false,
    var errorMessage: String = "",
    val errorMessageDescription: String = "",
    val isProtectionAvailable: Boolean = false,
    val protectionPricePerProduct: Int = 0,
    val protectionPrice: Double = 0.0,
    val protectionSubTitle: String = "",
    val protectionTitle: String = "",
    val protectionLinkText: String = "",
    val protectionLinkUrl: String = "",
    val isProtectionOptIn: Boolean = false,
    val isProtectionCheckboxDisabled: Boolean = false,
    val preOrderInfo: String = "",
    val isFreeShipping: Boolean = false,
    val isFreeShippingExtra: Boolean = false,
    val freeShippingName: String = "",
    val isShowTicker: Boolean = false,
    val tickerMessage: String = "",
    val isWholesalePrice: Boolean = false,
    val analyticsProductCheckoutData: AnalyticsProductCheckoutData = AnalyticsProductCheckoutData(),
    val isValidTradeIn: Boolean = false,
    val newDevicePrice: Long = 0,
    val oldDevicePrice: Long = 0,
    val deviceModel: String = "",
    val diagnosticId: String = "",
    val productInformation: List<String> = emptyList(),
    val productAlertMessage: String = "",
    val isBundlingItem: Boolean = false,
    val bundlingItemPosition: Int = 0,
    val bundleId: String = "",
    val bundleGroupId: String = "",
    val bundleType: String = "",
    val bundleTitle: String = "",
    val bundlePrice: Double = 0.0,
    val bundleSlashPriceLabel: String = "",
    val bundleOriginalPrice: Double = 0.0,
    val bundleQuantity: Int = 0,
    val bundleIconUrl: String = "",
    val addOnGiftingProductLevelModel: AddOnGiftingDataModel = AddOnGiftingDataModel(),
    val addOnDefaultFrom: String = "",
    val addOnDefaultTo: String = "",
    val isTokoCabang: Boolean = false,
    override val cartStringGroup: String,
    val warehouseId: String = "",
    val ethicalDrugDataModel: EthicalDrugDataModel = EthicalDrugDataModel(),
    val cartItemPosition: Int = 0,
    var isLastItemInOrder: Boolean = false,
    val addOnOrderLevelModel: AddOnGiftingWordingModel = AddOnGiftingWordingModel(),

    // new
    val shouldShowShopInfo: Boolean = false,
    val shopTypeInfoData: ShopTypeInfoData = ShopTypeInfoData(),
    val cartStringOrder: String = "",
    val originWarehouseIds: List<Long> = emptyList(),
    val addOnProduct: AddOnProductDataModel = AddOnProductDataModel(),
    val campaignId: Int = -1
) : Parcelable, ShipmentCartItem
