package com.tokopedia.logisticcart.shipping.model

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * Created by Irfan Khoirul on 25/01/18.
 */
@Parcelize
class CourierItemData(
        var shipperId: Int = 0,
        var shipperProductId: Int = 0,
        var serviceId: Int = 0,
        var name: String? = null,
        var serviceName: String? = null,
        var deliverySchedule: String? = null,
        var estimatedTimeDelivery: String? = null,
        var minEtd: Int = 0,
        var maxEtd: Int = 0,
        var shipperPrice: Int = 0,
        var shipperFormattedPrice: String? = null,
        var insurancePrice: Int = 0,
        var additionalPrice: Int = 0,
        var courierInfo: String? = null,
        var insuranceType: Int = 0,
        var insuranceUsedType: Int = 0,
        var insuranceUsedInfo: String? = null,
        var insuranceUsedDefault: Int = 0,
        var isUsePinPoint: Boolean = false,
        var isAllowDropshiper: Boolean = false,
        var isSelected: Boolean = false,
        var shipmentItemDataEtd: String? = null,
        var shipmentItemDataType: String? = null,
        var promoCode: String? = null,
        var logPromoCode: String? = null,
        var logPromoMsg: String? = null,
        var discountedRate: Int = 0,
        var shippingRate: Int = 0,
        var benefitAmount: Int = 0,
        var promoTitle: String? = null,
        var isHideShipperName: Boolean = false,
        var logPromoDesc: String? = null,
        var checksum: String? = null,
        var ut: String? = null,
        var blackboxInfo: String? = null,
        var now: Boolean? = null,
        var priorityPrice: Int = 0,
        var priorityInnactiveMessage: String? = null,
        var priorityFormattedPrice: String? = null,
        var priorityInactiveMessage: String? = null,
        var priorityDurationMessage: String? = null,
        var priorityCheckboxMessage: String? = null,
        var priorityWarningboxMessage: String? = null,
        var priorityFeeMessage: String? = null,
        var priorityPdpMessage: String? = null,
        var ontimeDelivery: OntimeDelivery? = null,
        var codProductData: CashOnDeliveryProduct? = null,
        var etaText: String? = null,
        var etaErrorCode: Int = 0,
        var shipperName: String? = null,
        var merchantVoucherProductModel: MerchantVoucherProductModel? = null,
        var preOrderModel: PreOrderModel? = null,
        var freeShippingChosenCourierTitle: String = "",
        var isHideChangeCourierCard: Boolean = false
) : Parcelable, ShipmentOptionData