package com.tokopedia.logisticcart.shipping.model

data class RatesParam(
        val spids: String,
        var shop_id: String = "",
        val origin: String,
        val destination: String,
        val weight: String,
        var token: String = "",
        var ut: String = "",
        var type: String = "",
        var from: String = "",
        var insurance: String = "",
        var product_insurance: String = "",
        var order_value: String = "",
        var cat_id: String = "",
        var lang: String = "",
        var user_history: Int = 0,
        var is_corner: Int = 0,
        var is_blackbox: Int = 0,
        var address_id: String = "",
        var preorder: Int = 0,
        var trade_in: Int = 0,
        var vehicle_leasing: Int = 0,
        var psl_code: String = "",
        var products: String = "",
        var unique_id: String = "",
        var corner_id: Int? = null,
        var pdp: String? = null,
        var loadtest: Int? = null,
        var is_express_checkout: Int? = null,
        var val_rates: String? = null,
        var used_otdg: Int? = null
) {
    fun toMap(): Map<String, Any> = mapOf(
            "spids" to spids,
            "shop_id" to shop_id,
            "origin" to origin,
            "destination" to destination,
            "weight" to weight,
            "token" to token,
            "ut" to ut,
            "type" to type,
            "from" to from,
            "insurance" to insurance,
            "product_insurance" to product_insurance,
            "order_value" to order_value,
            "cat_id" to cat_id,
            "lang" to lang,
            "user_history" to user_history,
            "is_corner" to is_corner,
            "is_blackbox" to is_blackbox,
            "address_id" to address_id,
            "preorder" to preorder,
            "trade_in" to trade_in,
            "vehicle_leasing" to vehicle_leasing,
            "psl_code" to psl_code,
            "products" to products,
            "unique_id" to unique_id
    )
}