package com.tokopedia.home_component.model

object DynamicChannelLayout {
    const val LAYOUT_HERO: String = "hero_4_image"
    const val LAYOUT_3_IMAGE: String = "3_image"
    const val LAYOUT_SPRINT: String = "sprint_3_image"
    const val LAYOUT_SPRINT_LEGO: String = "sprint_lego"
    const val LAYOUT_ORGANIC: String = "organic"
    const val LAYOUT_6_IMAGE: String = "6_image"
    const val LAYOUT_BANNER_GIF: String = "banner_image"
    const val LAYOUT_LEGO_3_IMAGE: String = "lego_3_image"
    const val LAYOUT_LEGO_4_IMAGE: String = "lego_4_image"
    const val LAYOUT_LEGO_2_IMAGE: String = "1x2_banner"
    const val LAYOUT_SPRINT_CAROUSEL: String = "sprint_carousel"
    const val LAYOUT_BU_WIDGET: String = "bu_widget"
    const val LAYOUT_TOPADS: String = "topads"
    const val LAYOUT_SPOTLIGHT: String = "spotlight"
    const val LAYOUT_HOME_WIDGET: String = "home_widget"
    const val LAYOUT_BANNER_ORGANIC: String = "banner_organic"
    const val LAYOUT_BANNER_CAROUSEL: String = "banner_carousel"
    const val LAYOUT_REVIEW: String = "product_review"
    const val LAYOUT_PLAY_BANNER: String = "play_widget"
    const val LAYOUT_DEFAULT_ERROR: String = "default_error"
    const val LAYOUT_LIST_CAROUSEL: String = "list_carousel"
    const val LAYOUT_POPULAR_KEYWORD: String = "popular_keyword"
    const val LAYOUT_MIX_LEFT: String = "left_carousel"
    const val LAYOUT_LEGO_4_AUTO: String = "4_banners_auto"
    const val LAYOUT_MIX_TOP: String = "top_carousel"
    const val LAYOUT_PRODUCT_HIGHLIGHT: String = "product_highlight"
    const val LAYOUT_RECHARGE_RECOMMENDATION: String = "dg_bills"
}