package com.tokopedia.topchat.common

object InboxChatConstant {
    const val PARCEL = "parcel"
    const val UPLOADING = "Uploaded Image"
    const val USER_TAG = "Pengguna"
    const val ADMIN_TAG = "Administrator"
    const val OFFICIAL_TAG = "Official"
    const val SELLER_TAG = "Penjual"
    const val CHATRESPONSEMODEL = "ChatResponseModel"
    const val CHAT_ROLE = "chatRole"
    const val SENDER_NAME = "senderName"
    const val CHAT_ENABLED = "isChatEnabled"
    const val MSG_ID = "messageID"
    const val BLOCK_TYPE = "blockType"
    const val BLOKCED = "isBlocked"
    const val CHAT_PROMOTION = "chat promosi"
    const val CHAT_PERSONAL = "chat personal"
    const val CHAT_BOTH = "semua chat"
    const val SHOP_NAME = "shopName"
    const val SHOP_ID = "shopId"
    const val SHOP_LOGO = "shopLogo"
    const val INVOICE = "INVOICE:"
    const val INVOICEURL = "invoiceUrl"
}