package com.tokopedia.purchase_platform.features.one_click_checkout.order.view.model

data class OrderCost(
//        val totalItem: Int,
        val totalPrice: Double = 0.0,
        val totalItemPrice: Double = 0.0,
//        val totalWeight: Double,
        val shippingFee: Double = 0.0,
        val insuranceFee: Double = 0.0,
        val paymentFee: Double = 0.0,
//        val priorityFee: Double,
//        val totalPurchaseProtectionItem: Int,
//        val purchaseProtectionFee: Double,
//        val additionalFee: Double,
//        val promoPrice: Double,
//        val donation: Double,
//        val promoMessage: String,
//        val emasPrice: Double,
//        val tradeInPrice: Double,
//        val totalPromoStackAmount: Int,
//        val totalPromoStackAmountStr: String,
//        val TotalDiscWithoutCashback: Int,
//        val macroInsurancePrice: Long,
//        val macroInsurancePriceLabel: String,
//        val bookingFee: Int,
//        val discountLabel: String,
//        val discountAmount: Int,
//        val hasDiscountDetails: Boolean,
//        val shippingDiscountLabel: String,
        val shippingDiscountAmount: Int = 0,
//        val productDiscountLabel: String,
        val productDiscountAmount: Int = 0
//        val cashbackLabel: String = "",
//        val cashbackAmount: Int = 0
)