package com.tokopedia.core.service.constant;

/**
 * Created by m.normansyah on 11/20/15.
 */
public interface DownloadServiceConstant {
    // common
    String TYPE = "type";
    String RETRY_FLAG = "RETRY_FLAG";
    String RECEIVER = "receiver";
    int NUMBER_OF_TRY = 1;
    int TIMEOUT_TIME = 10000;
    String IS_NEED_LOGIN = "IS_NEED_LOGIN";

    // error
    String MESSAGE_ERROR_FLAG = "MESSAGE_ERROR_FLAG";
    String INVALID_MESSAGE_ERROR = "Terjadi kesalahan, mohon coba kembali";
    String NETWORK_ERROR_FLAG = "NETWORK_ERROR_FLAG";
    int INVALID_NETWORK_ERROR_FLAG = -1;

    // HotList input
    String PAGE_KEY = "PAGE_KEY";
    String PER_PAGE_KEY = "PER_PAGE_KEY";
    // HotList output
    String HOTLIST_DATA = "HOTLIST_DATA";
    String HOTLIST_HAS_NEXT = "HOTLIST_HAS_NEXT";
    String HOTLIST_NEXT_PAGE = "HOTLIST_NEXT_PAGE";

    // Login input
    String LOGIN_VIEW_MODEL_KEY = "LOGIN_VIEW_MODEL";
    String LOGIN_SECURITY_QUESTION_DATA = "LOGIN_SECURITY_QUESTION_DATA";
    String LOGIN_MOVE_SECURITY = "LOGIN_MOVE_SECURITY";
    String LOGIN_ACTIVATION_RESENT = "LOGIN_ACTIVATION_RESENT";
    String VALIDATION_OF_DEVICE_ID = "VALIDATION_OF_DEVICE_ID";
    String LOGIN_SHOW_DIALOG = "LOGIN_SHOW_DIALOG";
    String LOGIN_GOOGLE_MODEL_KEY = "LOGIN_GOOGLE_MODEL_KEY";
    String LOGIN_FACEBOOK_MODEL_KEY = "LOGIN_FACEBOOK_MODEL_KEY";
    String LOGIN_WEBVIEW_MODEL_KEY = "LOGIN_WEBVIEW_MODEL_KEY";
    String LOGIN_MOVE_REGISTER_THIRD = "LOGIN_MOVE_REGISTER_THIRD";
    String DO_LOGIN = "DO_LOGIN";
    String TOKEN_BUNDLE = "TOKEN_BUNDLE";
    String INFO_BUNDLE = "INFO_BUNDLE";
    String PROFILE_BUNDLE = "PROFILE_BUNDLE";
    String EXTRA_TYPE = "EXTRA_TYPE";
    String LOGIN_PROVIDER = "LOGIN_PROVIDER";


    // Security Question
    String SECURITY_QUESTION_GET_MODEL = "SECURITY_QUESTION_GET_MODEL";
    String REQUEST_OTP_MODEL = "REQUEST_OTP_MODEL";
    String ANSWER_QUESTION_MODEL = "ANSWER_QUESTION_MODEL";
    String ANSWER_SECURITY_QUESTION_FALSE_MODEL = "ANSWER_SECURITY_QUESTION_FALSE_MODEL";
    String SECURITY_QUESTION_LOADING = "SECURITY_QUESTION_LOADING";
    String PHONE_TRUECALLER = "PHONE_TRUECALLER";
    String ALLOW_LOGIN = "ALLOW_LOGIN";

    // Register
    String REGISTER_MODEL_KEY = "REGISTER_MODEL_KEY";
    String REGISTER_QUESTION_LOADING = "REGISTER_QUESTION_LOADING";

    // Product Feed
    String PRODUCT_FEED_MODEL = "PRODUCT_FEED_MODEL";
    String PRODUCT_FEED_FIRST_PAGE_MODEL = "PRODUCT_FEED_FIRST_PAGE_MODEL";
    String PRODUCT_FEED_PAGE_KEY = "PRODUCT_FEED_PAGE_KEY";
    String PRODUCT_FEED_PER_PAGE_KEY = "PRODUCT_FEED_PER_PAGE_KEY";
    String PRODUCT_FEED_HAS_NEXT_KEY = "PRODUCT_FEED_HAS_NEXT_KEY";

    // Favorite
    String FAVORITE_PAGE_KEY = "FAVORITE_PAGE_KEY";
    String FAVORITE_PER_PAGE_KEY = "FAVORITE_PER_PAGE_KEY";
    String FAVORITE_FIRST_MODEL_KEY = "FAVORITE_FIRST_MODEL_KEY";
    String FAVORITE_SECOND_MODEL_KEY = "FAVORITE_SECOND_MODEL_KEY";
    String FAVORITE_MODEL_KEY = "FAVORITE_MODEL_KEY";
    String FAVORITE_HAS_NEXT_KEY = "FAVORITE_HAS_NEXT_KEY";

    // some response string
    String noNetworkConnection = "Tidak ada koneksi";

    String FETCH_DEPARTMENT_ = "FETCH_DEPARTMENT";

    // login bypass
    String LOGIN_BYPASS_MODEL_KEY = "LOGIN_BYPASS_MODEL";

    String CREATE_PASSWORD_MODEL_KEY = "CREATE_PASSWORD_MODEL_KEY";

    String LOGIN_TOKEN_MODEL_KEY = "LOGIN_TOKEN_MODEL_KEY";


    // type
    int INVALID_TYPE = -1;
    int HOTLIST = 0;
    int LOGIN_EMAIL = 1;
    int LOGIN_FACEBOOK = 2;
    int LOGIN_GOOGLE = 3;
    int SECURITY = 4;
    int SECURITY_QUESTION_GET = 5;
    int ANSWER_SECURITY_QUESTION = 6;
    int REQUEST_OTP = 7;
    int ANSWER_SECURITY_QUESTION_FALSE = 8;
    int REGISTER = 9;
    int REGISTER_LOGIN = 10;
    int REGISTER_THIRD = 11;
    int REGISTER_THIRD_LOGIN = 12;
    int LOGIN_BYPASS = 13;
    int REGISTER_PASS_PHONE = 14;

    int ADD_PRODUCT = 10;
    int FETCH_DEPARTMENT = 15;
    int SHIPPING_CITY = 16;
    int LOGIN_ACCOUNTS_TOKEN = 17;
    int LOGIN_ACCOUNTS_INFO = 18;
    int LOGIN_ACCOUNTS_PROFILE = 19;
    int MAKE_LOGIN = 20;
    int LOGIN_WEBVIEW = 21;
    int DISCOVER_LOGIN = 22;
    int REGISTER_FACEBOOK = 23;
    int RESET_PASSWORD = 24;
    int REGISTER_GOOGLE = 25;
    int REGISTER_WEBVIEW = 26;

    int REQUEST_OTP_PHONE = 27;
    int VERIFY_PHONE = 28;
    int LOGIN_UNIQUE_CODE = 29;

    int DOWNLOAD_RUNNING = 0;
    int DOWNLOAD_FINISHED = 1;
    int DOWNLOAD_ERROR = 2;

    String FACEBOOK = "facebook";
    String GOOGLE = "gplus";
    String WEBVIEW = "webview";
}
