package com.tokopedia.seller.selling.constant;

/**
 * Created by m.normansyah on 11/20/15.
 */
public interface SellingServiceConstant {
    // common
    String TYPE = "type";
    String DATA = "data";
    String RESULT_CODE = "result_code";
    String RETRY_FLAG = "RETRY_FLAG";
    String RECEIVER = "receiver";
    int NUMBER_OF_TRY = 1;
    int TIMEOUT_TIME = 10000;
    String IS_NEED_LOGIN = "IS_NEED_LOGIN";

    // error
    String MESSAGE_ERROR_FLAG ="MESSAGE_ERROR_FLAG";
    String INVALID_MESSAGE_ERROR = "default";
    String NETWORK_ERROR_FLAG ="NETWORK_ERROR_FLAG";
    int INVALID_NETWORK_ERROR_FLAG = -1;

    // HotList input
    String PAGE_KEY = "PAGE_KEY";
    String PER_PAGE_KEY = "PER_PAGE_KEY";
    // HotList output
    String HOTLIST_DATA = "HOTLIST_DATA";
    String HOTLIST_HAS_NEXT = "HOTLIST_HAS_NEXT";
    String HOTLIST_NEXT_PAGE = "HOTLIST_NEXT_PAGE";

    // Login input
    String MODEL_PARAM_SELLING_KEY = "MODEL_PARAM_SELLING";

    String MODEL_CONFIRM_SHIPPING_KEY = "MODEL_CONFIRM_SHIPPING";


    // Security Question
    String SECURITY_QUESTION_GET_MODEL = "SECURITY_QUESTION_GET_MODEL";
    String REQUEST_OTP_MODEL = "REQUEST_OTP_MODEL";
    String ANSWER_QUESTION_MODEL = "ANSWER_QUESTION_MODEL";
    String ANSWER_SECURITY_QUESTION_FALSE_MODEL = "ANSWER_SECURITY_QUESTION_FALSE_MODEL";
    String SECURITY_QUESTION_LOADING = "SECURITY_QUESTION_LOADING";

    // Register
    String REGISTER_MODEL_KEY = "REGISTER_MODEL_KEY";
    String REGISTER_QUESTION_LOADING = "REGISTER_QUESTION_LOADING";

    // Product Feed
    String PRODUCT_FEED_MODEL = "PRODUCT_FEED_MODEL";
    String PRODUCT_FEED_FIRST_PAGE_MODEL = "PRODUCT_FEED_FIRST_PAGE_MODEL";
    String PRODUCT_FEED_PAGE_KEY = "PRODUCT_FEED_PAGE_KEY";
    String PRODUCT_FEED_PER_PAGE_KEY = "PRODUCT_FEED_PER_PAGE_KEY";
    String PRODUCT_FEED_HAS_NEXT_KEY = "PRODUCT_FEED_HAS_NEXT_KEY";

    // Favorite
    String FAVORITE_PAGE_KEY = "FAVORITE_PAGE_KEY";
    String FAVORITE_PER_PAGE_KEY = "FAVORITE_PER_PAGE_KEY";
    String FAVORITE_FIRST_MODEL_KEY = "FAVORITE_FIRST_MODEL_KEY";
    String FAVORITE_SECOND_MODEL_KEY = "FAVORITE_SECOND_MODEL_KEY";
    String FAVORITE_MODEL_KEY = "FAVORITE_MODEL_KEY";
    String FAVORITE_HAS_NEXT_KEY = "FAVORITE_HAS_NEXT_KEY";

    // some response string
    String noNetworkConnection = "Tidak ada koneksi";

    // login bypass
    String LOGIN_BYPASS_MODEL_KEY = "LOGIN_BYPASS_MODEL";

    String CREATE_PASSWORD_MODEL_KEY = "CREATE_PASSWORD_MODEL_KEY";

    // type
    int INVALID_TYPE = -1;
    int CONFIRM_SHIPPING = 0;
    int CONFIRM_MULTI_SHIPPING = 1;
    int CONFIRM_NEW_ORDER = 2;
    int PARTIAL_NEW_ORDER = 3;
    int CANCEL_SHIPPING = 4;
    int REJECT_ORDER_WITH_DESCRIPTION = 5;
    int REJECT_ORDER_WITH_PRICE = 6;
    int REJECT_ORDER = 7;
    int REJECT_ORDER_CLOSE_SHOP = 8;
    int REJECT_ORDER_WITH_REASON = 9;
    int GET_PRODUCT_FORM_EDIT = 10;
    int GET_PRODUCT_FORM_EDIT_CLOSED = 11;
    int REJECT_NEW_ORDER = 12;

    String RECEIVER_BROADCAST_ORDER_NAME = "receiver_broadcast_order";

}
