package com.tokopedia.logisticaddaddress.common

/**
 * Created by Fajar Ulin Nuha on 09/10/18.
 */
object AddressConstants {
    const val REQUEST_CODE = 0x12
    const val EXTRA_INSTANCE_TYPE = "EXTRA_INSTANCE_TYPE"
    const val EDIT_PARAM = "EDIT_PARAM"
    const val KERO_TOKEN = "token"
    const val INSTANCE_TYPE_DEFAULT = 0
    const val INSTANCE_TYPE_ADD_ADDRESS_FROM_MANAGE_ADDRESS_EMPTY_DEFAULT_ADDRESS = 3
    const val INSTANCE_TYPE_EDIT_ADDRESS_FROM_MANAGE_ADDRESS = 2
    const val INSTANCE_TYPE_ADD_ADDRESS_FROM_SINGLE_CHECKOUT_EMPTY_DEFAULT_ADDRESS = 13
    const val INSTANCE_TYPE_EDIT_ADDRESS_FROM_SINGLE_CHECKOUT = 12
    const val INSTANCE_TYPE_ADD_ADDRESS_FROM_MULTIPLE_CHECKOUT = 21
    const val INSTANCE_TYPE_EDIT_ADDRESS_FROM_MULTIPLE_CHECKOUT = 22
    const val EXTRA_LAT = "EXTRA_LAT"
    const val EXTRA_LONG = "EXTRA_LONG"
    const val EXTRA_REF = "EXTRA_REF"
    const val EXTRA_SHOW_AUTOCOMPLETE = "EXTRA_SHOW_AUTOCOMPLETE"
    const val EXTRA_IS_MISMATCH = "EXTRA_IS_MISMATCH"
    const val EXTRA_IS_MISMATCH_SOLVED = "EXTRA_IS_ORIGIN_MISMATCH_SOLVED"
    const val EXTRA_IS_POLYGON = "EXTRA_IS_POLYGON"
    const val EXTRA_ADDRESS_STATE = "EXTRA_ADDRESS_STATE"
    const val EXTRA_SAVE_DATA_UI_MODEL = "EXTRA_SAVE_DATA_UI_MODEL"
    const val EXTRA_IS_EDIT = "EXTRA_IS_EDIT"
    const val EXTRA_ADDRESS_ID = "EXTRA_ADDRESS_ID"
    const val EXTRA_IS_CHANGES_REQUESTED = "EXTRA_IS_CHANGES_REQUESTED"
    const val EXTRA_IS_UNNAMED_ROAD = "EXTRA_UNNAMED_ROAD"
    const val EXTRA_IS_NULL_ZIPCODE = "EXTRA_IS_NULL_ZIPCODE"
    const val EXTRA_GMS_AVAILABILITY = "EXTRA_GMS_AVAILABILITY"
    const val EXTRA_NEGATIVE_FULL_FLOW = "EXTRA_NEGATIVE_FULL_FLOW"
    const val EXTRA_FROM_ADDRESS_FORM = "EXTRA_FROM_ADDRESS_FORM"
    const val EXTRA_FROM_PINPOINT = "EXTRA_FROM_PINPOINT"
    const val EXTRA_RESET_TO_SEARCH_PAGE = "EXTRA_RESET_TO_SEARCH_PAGE"
    const val KEY_SAVE_INSTANCE_SAVE_ADDRESS_DATA_MODEL =
        "KEY_SAVE_INSTANCE_SAVE_ADDRESS_DATA_MODEL"
    private const val MONAS_LAT = -6.175794
    private const val MONAS_LONG = 106.826457
    const val EXTRA_IS_FULL_FLOW = "EXTRA_IS_FULL_FLOW"
    const val EXTRA_ADDRESS_MODEL = "EXTRA_ADDRESS_MODEL"
    const val EXTRA_IS_LOGISTIC_LABEL = "EXTRA_IS_LOGISTIC_LABEL"
    const val EXTRA_IS_CIRCUIT_BREAKER = "EXTRA_IS_CIRCUIT_BREAKER"
    const val EXTRA_WAREHOUSE_DATA = "EXTRA_WAREHOUSE_DATA"
    const val EXTRA_IS_EDIT_WAREHOUSE = "EXTRA_IS_EDIT_WAREHOUSE"
    const val EXTRA_IS_POSITIVE_FLOW = "EXTRA_IS_POSITIVE_FLOW"
    const val EXTRA_IS_ANA_REVAMP = "EXTRA_IS_ANA_REVAMP"
    const val EXTRA_IS_PINPOINT = "EXTRA_IS_PINPOINT"
    const val CIRCUIT_BREAKER_ON_CODE = 101
    const val DEFAULT_LAT = MONAS_LAT
    const val DEFAULT_LONG = MONAS_LONG
    const val ANA_POSITIVE = "positive"
    const val ANA_NEGATIVE = "negative"
    const val LOGISTIC_LABEL = "logistic"
    const val NON_LOGISTIC_LABEL = "non-logistic"
    const val GPS_REQUEST = 108

    // Lite Pinpoint
    const val KEY_DISTRICT_ID = "KEY_DISTRICT_ID"
    const val KEY_LAT_ID = "KEY_LAT_ID"
    const val KEY_LONG_ID = "KEY_LONG_ID"
    const val KEY_CURRENT_LOC = "KEY_CURRENT_LOC"
    const val KEY_LOCATION_PASS = "KEY_LOCATION_PASS"
    const val KEY_ADDRESS_DATA = "KEY_ADDRESS_DATA"
    const val KEY_SOURCE_PINPOINT = "KEY_SOURCE_PINPOINT"
    const val PARAM_LAT = "lat"
    const val PARAM_LONG = "lng"
    const val PARAM_TRACKER = "trackerId"
    const val PARAM_TRACKER_LABEL = "label"
    const val PARAM_DISTRICT_ID = "districtId"
    const val PARAM_CURRENT_LOC = "currentLoc"
    const val PARAM_SOURCE = "source"

    // User Consent
    const val ADD_ADDRESS_COLLECTION_ID_STAGING = "01203d44-15c8-46f5-aed2-77e92dd4e625"
    const val ADD_ADDRESS_COLLECTION_ID_PRODUCTION = "1dd907e3-3e1f-405d-90c5-3db42e19d59d"
    const val EDIT_ADDRESS_COLLECTION_ID_STAGING = "e5a06379-2564-4357-8380-d2bf9e694340"
    const val EDIT_ADDRESS_COLLECTION_ID_PRODUCTION = "011d3e50-a147-41ea-8ea4-eae1dda6701e"
}
