package com.tokopedia.seller.menu.common.analytics

object SettingTrackingConstant {

    const val EVENT = "event"
    const val EVENT_CATEGORY = "eventCategory"
    const val EVENT_ACTION = "eventAction"
    const val EVENT_LABEL = "eventLabel"

    const val IMPRESSION = "impression"
    const val CLICK= "click"
    const val CLICK_NAVIGATION_DRAWER = "clickNavigationDrawer"
    const val CLICK_SHOP_SETTING = "clickShopSetting"
    const val VIEW_NAVIGATION_IRIS = "viewNavigationIris"
    const val VIEW_SHOP_SETTING_IRIS = "viewShopSettingIris"
    const val OTHERS_TAB = "others tab"
    const val VIEW_STATISTIC_IRIS = "viewStatistikIris"
    const val CLICK_STATISTIC = "clickStatistik"

    const val GOLD_MERCHANT = "gold_merchant"
    const val OFFICIAL_STORE = "official_store"
    const val REGULAR = "regular"
    const val UPGRADE = "upgrade"
    const val VERIFICATION = "verification"
    const val ACTIVE = "active"
    const val INACTIVE = "inactive"
    const val ON_VERIFICATION = "on_verification"

    const val SHOP_PICTURE = "shop picture"
    const val SHOP_NAME = "shop name"
    const val SHOP_ARROW = "shop arrow"
    const val SHOP_BADGE = "shop badge"
    const val SHOP_FOLLOWERS = "shop followers"
    const val SHOP_STATE = "shop state"
    const val ON_SALDO = "on saldo"
    const val ON_TOPADS_CREDIT = "on topads credits"
    const val SHOP_ADS_AND_PROMOTION = "shop ads and promotions"
    //temporary
    const val SHOP_PERFORMANCE = "shop performance"
    const val REVIEW = "review"
    const val DISCUSSION = "discussion"
    const val COMPLAINT = "complaint"
    const val FINANCIAL_SERVICE = "financial service"
    const val SELLER_CENTER = "seller center"
    const val TOKOPEDIA_CARE = "tokopedia care"
    const val SETTINGS = "settings"
    const val BACK_ARROW = "back arrow"
    const val SHOP_SETTING = "shop settings"
    const val COD_ACTIVATION_SETTING = "cod activation settings"
    const val ACCOUNT_SETTING = "account settings"
    const val APP_SETTING = "app settings"
    const val APPLICATION_SETTING = "application settings"
    const val OTHER_SETTING = "other settings"
    const val SELLER_APP_LAINNYA = "seller app - lainnya"
    const val IMPRESSION_MENU_STATISTIC = "impression - menu statistik"
    const val CLICK_MENU_STATISTIC = "click - menu statistik"

    const val SHOP_REGULAR_MERCHANT = "RM"
    const val SHOP_POWER_MERCHANT = "PM"
    const val SHOP_OFFICIAL_STORE = "OS"

    const val USER_ID = "userId"
    const val SHOP_ID = "shopId"
    const val SHOP_TYPE = "shopType"
    const val KEY_BUSINESS_UNIT = "businessUnit"
    const val KEY_CURRENT_SITE = "currentSite"

    const val PHYSICAL_GOODS = "physicalgoods"
    const val TOKOPEDIASELLER = "tokopediaseller"
}