query GETCANCELREASON($input:CancelReasonRequest!) {
  get_cancellation_reason(input:$input) {
    is_requested_cancel,
    is_requested_cancel_available,
    is_eligible_instant_cancel,
    is_show_ticker,
    cancellation_min_time,
    cancellation_notes,
    ticker_info{
      label,
      color,
      bg_color,
      link_text,
      link_url
    },
    reasons{
      title,
      question,
      sub_reasons{
        r_code,
        reason
      }
    }
  }
}