query GETCANCELREASON($input:CancelReasonRequest!) {
  get_cancellation_reason(input:$input) {
    is_requested_cancel,
    is_requested_cancel_available,
    is_eligible_instant_cancel,
    is_show_ticker,
    cancellation_min_time,
    cancellation_notes,
    ticker_info{
        text,
        type,
        action_text,
        action_key,
        action_url
    },
    reasons{
      title,
      question,
      sub_reasons{
        r_code,
        reason
      }
    },
    have_product_bundle,
    bundle_detail {
      total_product,
      product_bundling_icon,
      bundle {
        bundle_id,
        bundle_name,
        bundle_price,
        bundle_quantity,
        bundle_subtotal_price,
        order_detail {
          order_id,
          order_dtl_id,
          product_id,
          product_name,
          quantity,
          product_price,
          subtotal_price,
          notes,
          thumbnail,
          bundle_id
        }
      },
      non_bundle {
        order_id,
        product_id,
        product_name,
        quantity,
        product_price,
        subtotal_price,
        notes,
        thumbnail,
        bundle_id
      }
    }
  }
}