query GETCANCELREASON($input:CancelReasonRequest!) {
  get_cancellation_reason(input:$input) {
    is_requested_cancel,
    is_requested_cancel_available,
    is_eligible_instant_cancel,
    is_show_ticker,
    cancellation_min_time,
    cancellation_notes,
    ticker_info{
        text,
        type,
        action_text,
        action_key,
        action_url
    },
    reasons{
      title,
      question,
      sub_reasons{
        r_code,
        reason
      }
    },
    have_product_bundle,
    bundle_detail {
      total_product,
      product_bundling_icon,
      bundle {
        bundle_name,
        order_detail {
          product_id,
          product_name,
          product_price,
          picture
        }
      },
      non_bundle {
        product_id,
        product_name,
        product_price,
        picture
      }
    },
    order_details{
        product_id,
        product_name,
        product_price,
        picture,
        bundle_id,
        bundle_variant_id
    }
  }
}