query ORDERDETAIL($cartString: String, $paymentId: String,$orderCategory: String) {
  orderDetails(cartString: $cartString, paymentId: $paymentId,orderCategoryStr: $orderCategory) {
    status {
          status
      statusText
      statusLabel
      iconUrl
      textColor
      backgroundColor
      fontSize
    }
    requestCancelInfo{
          requestCancelNote
      requestCancelMinTime
      isRequestedCancel
      isRequestCancelAvail
    }
    flag {
          isOrderCOD
      isOrderNow
      isOrderTradeIn
      warehouseID
      fulfillBy
    }
    title {
          label
      value
      textColor
      backgroundColor
      imageUrl
    }
    driverDetails {
          name
      photo
      phone
      licenseNumber
      trackingURL
    }
    dropShipper {
          name
      phone
    }
    helpLink
    invoice {
          invoiceRefNum
      invoiceUrl
    }
    items {
      detail_id
      categoryID
      categoryL1
      categoryL2
      categoryL3
      id
      imageUrl
      category
      title
      quantity
      price
      promotionAmount
      metaData
      description
      productUrl
      totalPrice
      weight
      freeShipping {
            isEligible
        imageUrl
      }
      actionButtons {
            label
        buttonType
        uri
        mappingUri
        weight
        key
        method
        uriWeb
        value
        name
        control
        header
        color{
              textColor
          border
          background
        }
        body {
              appURL
          webURL
          method
          body
        }
      }
      tapActions {
            label
        weight
        control
        header
        buttonType
        value
        method
        key
        name
        color {
              textColor
          border
          background
        }
        body {
              appURL
          method
          body
        }
      }
    }
    pricing {
          label
      value
      textColor
      backgroundColor
      imageUrl
    }
    discount {
      label
      value
      textColor
      backgroundColor
      imageUrl
    }
    detail {
      label
      value
    }
    paymentData {
          label
      value
      textColor
      backgroundColor
      imageUrl
    }
    actionButtons {
          label
      buttonType
      key
      value
      weight
      control
      header
      uri
      color {
            textColor
        border
        background
      }
      body {
            appURL
        webURL
        method
        body
      }
      popup {
            title
        body
        actionButtons {
               label
           buttonType
           uri
           key
           method
           value
           name
        }
      }
    }
    shopDetails {
          id
      name
      logo
      shopURL
    }
    conditionalInfo {
          text
      color {
            border
        background
      }
    }
    contactUs {
          helpText
      helpUrl
    }
    paymentMethod {
          label
      value
    }
    payMethod{
          label
      value
    }
    beforeOrderId
    resolutionId
    driverDetails {
          name
      phone
      photo
      licenseNumber
      trackingURL
    }
    promoCode
    additionalInfo {
          label
      value
      imageUrl
      textColor
      backgroundColor
    }
    additionalTickerInfo {
          title
      notes
      urlDetail
      urlText
    }
  }
}