package com.tokopedia.seller.menu.presentation.uimodel.compose

enum class SellerMenuActionClick {
    INBOX, NOTIF_CENTER, BACK_BUTTON,
    SHOP, SHOP_FAVORITES, SHOP_SCORE, BALANCE,
    POWER_MERCHANT, POWER_MERCHANT_UPGRADE, POWER_MERCHANT_INACTIVE, OFFICIAL_STORE,
    NEW_ORDER, READY_TO_SHIP_ORDER, ALL_ORDER,
    PRODUCT_LIST, ADD_PRODUCT,
    REVIEW, DISCUSSION, COMPLAINTS,
    SELLER_EDU, TOKOPEDIA_CARE, SETTINGS,
    MIGRATION_STATISTIC, MIGRATION_PROMO, MIGRATION_FEED, MIGRATION_FINANCE,
    NONE
}
