package com.tokopedia.home_account.account_settings


/**
 * @author okasurya on 7/20/18.
 */
object AccountConstants {
    object Analytics {
        const val CLICK_HOME_PAGE = "clickHomePage"
        const val CLICK_SETTING = "clickSetting"
        const val CLICK_ACCOUNT = "clickAccount"
        const val CLICK_ACCOUNT_SETTING = "clickAccountSetting"
        const val CLICK_OTP = "clickOtp"
        const val SHOP_MANAGE = "clickManageShop"
        const val CATEGORY_SHOP_MANAGE = "Manage Shop"
        const val SHOP_SHIPPING = "Shop Shipping"
        const val AKUN_SAYA = "akun saya"
        const val CLICK = "click"
        const val SHOP_CLICK = "Click"
        const val PENJUAL = "penjual"
        const val USER = "user"
        const val SETTING = "setting"
        const val FINGERPRINT = "fingerprint"
        const val SHOP = "shop"
        const val ACCOUNT = "account"
        const val PAYMENT_METHOD = "payment method"
        const val NOTIFICATION = "notification"
        const val INBOX = "inbox"
        const val SHAKE_SHAKE = "shake - shake"
        const val SAFE_MODE = "safe mode"
        const val TERM_CONDITION = "terms & condition"
        const val ABOUT_US = "about us"
        const val PRIVACY_POLICY = "privacy policy"
        const val APPLICATION_REVIEW = "application review"
        const val HELP_CENTER = "help center"
        const val DEVELOPER_OPTIONS = "developer options"
        const val LOGOUT = "logout"
        const val CLEAR_CACHE = "clear cache"
        const val ADVANCED_SETTING = "pengaturan tambahan"
        const val PERSONAL_DATA = "personal data"
        const val ADDRESS_LIST = "address list"
        const val PASSWORD = "password"
        const val TOKOCASH = "tokocash"
        const val BALANCE = "balance"
        const val GOPAY = "gopay"
        const val ACCOUNT_BANK = "account bank"
        const val CREDIT_CARD = "credit card"
        const val SCREEN_NAME = "screenName"
        const val EVENT = "event"
        const val EVENT_CATEGORY = "eventCategory"
        const val EVENT_ACTION = "eventAction"
        const val EVENT_LABEL = "eventLabel"
        const val TOP_NAV = "top nav"
        const val SCREEN_NAME_ACCOUNT = "/account"
        const val ACTIVITY_NAME_SALDO_DEPOSIT = "com.tokopedia.saldodetails.saldoDetail.SaldoDepositActivity"
        const val MY_ACCOUNT = "my account page"
        const val CLICK_MY_ACCOUNT_ACTIVATION_OVO = "click aktivasi ovo pada akun"
        const val CLICK_KYC_SETTING = "click dokumen data diri"
        const val CLICK_KYC_REJECTED = "click on verifikasi ulang"
        const val CLICK_KYC_NOT_VERIFIED = "click on verifikasi sekarang"
        const val CLICK_KYC_PENDING = "click on lihat status"
        const val CLICK_BIOMETRIC_BUTTON = "click on button biometric"
        const val EVENT_SALDO_OVO = "clickSaldo"
        const val EVENT_CLICK_SAMPAI = "clickRegister"
        const val EVENT_CATEGORY_SAMPAI = "register tokopedia corner"
        const val EVENT_ACTION_SAMPAI = "click button daftar"
        const val EVENT_ACTION_MENUNGGU_PEMBAYARAN = "click on button menunggu pembayaran"
        const val EVENT_ACTION_SEMUA_TRANSAKSI = "click on button semua transaksi"
        const val EVENT_ACTION_DALAM_PROSES = "click on button dalam proses"
        const val EVENT_ACTION_ETICKET_EVOUCHER = "click on e-tiket & e-voucher aktif"
        const val EVENT_ACTION_CLICK_SCREEN_RECORDER = "click on screen recorder"
        const val CLICK_FINTECH_MICROSITE = "clickFintechMicrosite"
        const val CLICK_ON_PASSWORD = "click on kata sandi"
        const val EVENT_CLICK_ACCOUNT = "clickAccount"
        const val CATEGORY_ACCOUNT_SELL = "my account - sell"
        const val ACTION_CLICK_OPEN_SHOP = "click open shop"
        const val ACTION_CLICK_LEARN_MORE = "click learn more"
        const val ECOMMERCE = "ecommerce"
        const val EVENT_PRODUCT_VIEW = "productView"
        const val EVENT_CATEGORY_ACCOUNT_PAGE_BUYER = "account page - buyer"
        const val EVENT_ACTION_IMPRESSION_PRODUCT_RECOMMENDATION = "impression - product recommendation"
        const val CURRENCY_CODE = "currencyCode"
        const val CURRENT_SITE = "currentSite"
        const val TRACKER_ID = "trackerId"
        const val IDR = "IDR"
        const val IMPRESSIONS = "impressions"
        const val DATA_NAME = "name"
        const val DATA_ID = "id"
        const val DATA_PRICE = "price"
        const val DATA_BRAND = "brand"
        const val DATA_CATEGORY = "category"
        const val DATA_VARIAN = "variant"
        const val LIST = "list"
        const val DATA_POSITION = "position"
        const val NONE_OTHER = "none/other"
        const val EVENT_PRODUCT_CLICK = "productClick"
        const val EVENT_ACTION_CLICK_PRODUCT_RECOMMENDATION = "click - product recommendation"
        const val EMPTY = ""
        const val ACTION_FIELD = "actionField"
        const val PRODUCTS = "products"
        const val DATA_ATTRIBUTION = "attribution"
        const val VALUE_PRODUCT_RECOMMENDATION_LIST = "/user - rekomendasi untuk anda - %s"
        const val VALUE_PRODUCT_TOPADS = " - product topads"
        const val VALUE_WISHLIST_PRODUCT = "%s - wishlist on product recommendation"
        const val SECTION_OTHER_FEATURE = "Fitur Lainnya"
        const val ITEM_POWER_MERCHANT = "Power Merchant"
        const val DATA_DIMENSION_83 = "dimension83"
        const val VALUE_BEBAS_ONGKIR = "bebas ongkir"
        const val EVENT_CATEGORY_AKUN_PEMBELI = "akun saya pembeli"
        const val EVENT_ACTION_ACCOUNT_PROMOTION_IMPRESSION = "account promotion impression"
        const val EVENT_ACTION_ACCOUNT_PROMOTION_CLICK = "click reward section"
        const val EVENT_ACTION_ACCOUNT_PROMOTION_REWARD_CLICK = "click entry point to reward page"
        const val FIELD_ID = "id"
        const val FIELD_NAME = "name"
        const val FIELD_CREATIVE = "creative"
        const val FIELD_CREATIVE_URL = "creative_url"
        const val FIELD_POSITION = "position"
        const val EVENT_PROMO_VIEW = "promoView"
        const val PROMOTIONS = "promotions"
        const val PROMOTION_VIEW = "promoView"
        const val VALUE_ACCOUNT_PROMOTION_NAME = "/account_profile_buyer/promotion"
        const val CLICK_NOTIF_CENTER = "clickNotifCenter"
        const val NOTIF_CENTER = "notif center"
        const val NOTIF_CENTER_ACTION = "click on bell on global nav"
        const val FIELD_USER_ID = "userId"
        const val FIELD_SHOP_ID = "shopId"
        const val FIELD_SHOP_TYPE = "shopType"
        const val SHOP_TYPE_RM = "RM"
        const val SHOP_TYPE_PM = "PM"
        const val EVENT_NAME_CLICK_NOTIF_CENTER = "clickNotifCenter"
        const val CATEGORY_NOTIF_CENTER = "notif center"
        const val EVENT_ACTION_TS_USR_MENU = "click on notif setting from setting page"
        const val USER_BELI = "user/beli"
        const val TOKOPEDIA_MARKETPLACE = "tokopediamarketplace"
        const val BUSINESS_UNIT = "businessUnit"
        const val USER_PLATFORM = "user platform"
        const val HOME_AND_BROWSE = "home & browse"
        const val CATEGORY_SETTING_PAGE = "setting page"
        const val ACTION_SIMPAN_THEME_SELECTION = "click simpan on theme selection"
    }

    interface ErrorCodes {
        companion object {
            const val ERROR_CODE_NULL_MENU = "ACC001"
            const val ERROR_CODE_ACCOUNT_SETTING_CONFIG = "ASC001"
        }
    }

    object Query {
        const val QUERY_USER_REWARDSHORCUT = "query_user_rewardshortcut"
    }
}