package com.tokopedia.productcard_compact.similarproduct.analytic

object TokonowSimilarProductConstants {
    const val TRACKER_ID_CLICK_SIMILAR_PRODUCT_BUTTON_SEARCH = "39574"
    const val TRACKER_ID_VIEW_SIMILAR_PRODUCT_BOTTOMSHEET_SEARCH = "39575"
    const val TRACKER_ID_CLICK_PRODUCT_SEARCH = "39576"
    const val TRACKER_ID_ADD_TO_CART_SEARCH = "39577"
    const val TRACKER_ID_CLICK_CLOSE_BOTTOMSHEET_SEARCH = "39578"
    const val TRACKER_ID_VIEW_EMPTY_STATE_SEARCH = "39579"

    const val TRACKER_ID_CLICK_SIMILAR_PRODUCT_BUTTON_CATEGORY = "39603"
    const val TRACKER_ID_VIEW_SIMILAR_PRODUCT_BOTTOMSHEET_CATEGORY = "39604"
    const val TRACKER_ID_CLICK_PRODUCT_CATEGORY = "39605"
    const val TRACKER_ID_ADD_TO_CART_CATEGORY = "39606"
    const val TRACKER_ID_CLICK_CLOSE_BOTTOMSHEET_CATEGORY = "39607"
    const val TRACKER_ID_VIEW_EMPTY_STATE_CATEGORY = "39608"

    const val TRACKER_ID_CLICK_SIMILAR_PRODUCT_BUTTON_REPURCHASE = "39959"
    const val TRACKER_ID_VIEW_SIMILAR_PRODUCT_BOTTOMSHEET_REPURCHASE = "39960"
    const val TRACKER_ID_CLICK_PRODUCT_REPURCHASE = "39961"
    const val TRACKER_ID_ADD_TO_CART_REPURCHASE = "39962"
    const val TRACKER_ID_CLICK_CLOSE_BOTTOMSHEET_REPURCHASE = "39963"
    const val TRACKER_ID_VIEW_EMPTY_STATE_REPURCHASE = "39964"

}
