package com.tokopedia.play.broadcaster.shorts.di

import androidx.fragment.app.Fragment
import androidx.fragment.app.FragmentFactory
import com.tokopedia.abstraction.base.view.fragment.FragmentKey
import com.tokopedia.abstraction.base.view.fragment.TkpdFragmentFactory
import com.tokopedia.content.product.picker.seller.di.ProductPickerBindModule
import com.tokopedia.content.product.picker.seller.di.ProductPickerFragmentModule
import com.tokopedia.play.broadcaster.shorts.view.fragment.PlayShortsPreparationFragment
import com.tokopedia.play.broadcaster.shorts.view.fragment.PlayShortsSummaryFragment
import com.tokopedia.play.broadcaster.view.bottomsheet.PlayBroadcastSetupCoverBottomSheet
import com.tokopedia.play.broadcaster.view.bottomsheet.PlayBroadcastSetupTitleBottomSheet
import com.tokopedia.play.broadcaster.view.bottomsheet.PlayShortsAffiliateSuccessBottomSheet
import com.tokopedia.play.broadcaster.view.bottomsheet.PlayShortsAffiliateTnCBottomSheet
import com.tokopedia.content.product.picker.seller.view.bottomsheet.ProductPickerUserBottomSheet
import com.tokopedia.play.broadcaster.shorts.view.bottomsheet.InterspersingConfirmationBottomSheet
import com.tokopedia.play.broadcaster.shorts.view.fragment.PlayShortsVideoPreviewFragment
import com.tokopedia.play.broadcaster.view.fragment.setup.cover.PlayBroadcastSetupAutoGeneratedCoverFragment
import com.tokopedia.play.broadcaster.view.fragment.setup.cover.PlayBroadcastSetupCoverUploadImageFragment
import dagger.Binds
import dagger.Module
import dagger.multibindings.IntoMap

/**
 * Created By : Jonathan Darwin on November 08, 2022
 */
@Module(
    includes = [
        ProductPickerFragmentModule::class,
    ]
)
abstract class PlayShortsFragmentModule {

    @Binds
    abstract fun bindFragmentFactory(fragmentFactory: TkpdFragmentFactory): FragmentFactory

    @Binds
    @IntoMap
    @FragmentKey(PlayShortsPreparationFragment::class)
    abstract fun bindPlayShortsPreparationFragment(fragment: PlayShortsPreparationFragment): Fragment

    @Binds
    @IntoMap
    @FragmentKey(PlayShortsSummaryFragment::class)
    abstract fun bindPlayShortsSummaryFragment(fragment: PlayShortsSummaryFragment): Fragment

    @Binds
    @IntoMap
    @FragmentKey(ProductPickerUserBottomSheet::class)
    abstract fun getPlayPlaceholderBottomSheet(bottomSheet: ProductPickerUserBottomSheet): Fragment

    @Binds
    @IntoMap
    @FragmentKey(PlayShortsAffiliateTnCBottomSheet::class)
    abstract fun getPlayShortsAffiliateTnCBottomSheet(fragment: PlayShortsAffiliateTnCBottomSheet): Fragment

    @Binds
    @IntoMap
    @FragmentKey(PlayShortsAffiliateSuccessBottomSheet::class)
    abstract fun getPlayShortsAffiliateSuccessBottomSheet(fragment: PlayShortsAffiliateSuccessBottomSheet): Fragment

    @Binds
    @IntoMap
    @FragmentKey(PlayBroadcastSetupTitleBottomSheet::class)
    abstract fun getSetupTitleBottomSheet(fragment: PlayBroadcastSetupTitleBottomSheet): Fragment

    @Binds
    @IntoMap
    @FragmentKey(PlayBroadcastSetupCoverBottomSheet::class)
    abstract fun getSetupCoverBottomSheet(fragment: PlayBroadcastSetupCoverBottomSheet): Fragment

    @Binds
    @IntoMap
    @FragmentKey(PlayBroadcastSetupCoverUploadImageFragment::class)
    abstract fun getSetupCoverUploadImageFragment(fragment: PlayBroadcastSetupCoverUploadImageFragment): Fragment

    @Binds
    @IntoMap
    @FragmentKey(PlayBroadcastSetupAutoGeneratedCoverFragment::class)
    abstract fun getSetupAutoGeneratedCoverFragment(fragment: PlayBroadcastSetupAutoGeneratedCoverFragment): Fragment

    @Binds
    @IntoMap
    @FragmentKey(InterspersingConfirmationBottomSheet::class)
    abstract fun getInterspersingConfirmationBottomSheet(fragment: InterspersingConfirmationBottomSheet): Fragment

    @Binds
    @IntoMap
    @FragmentKey(PlayShortsVideoPreviewFragment::class)
    abstract fun getPlayShortsVideoPreviewFragment(fragment: PlayShortsVideoPreviewFragment): Fragment
}
