package com.tokopedia.play.broadcaster.view.fragment.setup.cover

import android.annotation.SuppressLint
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.core.view.isVisible
import androidx.fragment.app.FragmentManager
import androidx.fragment.app.viewModels
import androidx.lifecycle.lifecycleScope
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.LinearLayoutManager.HORIZONTAL
import androidx.recyclerview.widget.PagerSnapHelper
import androidx.recyclerview.widget.RecyclerView
import com.tokopedia.abstraction.common.dispatcher.CoroutineDispatchers
import com.tokopedia.content.common.ui.itemdecoration.AutoGeneratedCoverItemDecoration
import com.tokopedia.kotlin.extensions.view.showWithCondition
import com.tokopedia.kotlin.util.lazyThreadSafetyNone
import com.tokopedia.play.broadcaster.R
import com.tokopedia.play.broadcaster.analytic.PlayBroadcastAnalytic
import com.tokopedia.play.broadcaster.databinding.FragmentSetupCoverChooseTemplateBinding
import com.tokopedia.play.broadcaster.setup.cover.PlayBroSetupCoverAction
import com.tokopedia.play.broadcaster.setup.cover.PlayBroSetupCoverEvent
import com.tokopedia.play.broadcaster.setup.cover.PlayBroSetupCoverViewModel
import com.tokopedia.play.broadcaster.setup.product.viewmodel.ViewModelFactoryProvider
import com.tokopedia.play.broadcaster.ui.model.setup.AutoGeneratedCoverUIModel
import com.tokopedia.play.broadcaster.view.adapter.PlayAutoGeneratedCoverAdapter
import com.tokopedia.play.broadcaster.view.bottomsheet.PlayBroadcastSetupCoverBottomSheet
import com.tokopedia.play.broadcaster.view.bottomsheet.PlayBroadcastSetupCoverBottomSheet.Companion.TAB_AUTO_GENERATED
import com.tokopedia.play.broadcaster.view.fragment.base.PlayBaseBroadcastFragment
import com.tokopedia.play.broadcaster.view.fragment.summary.PlayBroadcastPostVideoFragment
import com.tokopedia.play_common.lifecycle.viewLifecycleBound
import com.tokopedia.play_common.util.PlayToaster
import com.tokopedia.play_common.util.extension.withCache
import com.tokopedia.unifycomponents.Toaster
import kotlinx.coroutines.flow.collectLatest
import javax.inject.Inject

/**
 * Created by fachrizalmrsln on 11/01/23
 */
class PlayBroadcastSetupAutoGeneratedCoverFragment @Inject constructor(
    private val analytic: PlayBroadcastAnalytic,
    private val dispatchers: CoroutineDispatchers,
) : PlayBaseBroadcastFragment(),
    PlayAutoGeneratedCoverAdapter.Listener {

    private val viewModel: PlayBroSetupCoverViewModel by viewModels(
        ownerProducer = { requireParentFragment() }
    ) {
        (parentFragment as ViewModelFactoryProvider).getFactory()
    }

    private var _binding: FragmentSetupCoverChooseTemplateBinding? = null
    private val binding: FragmentSetupCoverChooseTemplateBinding
        get() = _binding!!

    private val toaster by viewLifecycleBound(
        creator = { PlayToaster(binding.toasterLayout, it.viewLifecycleOwner) }
    )

    private val mLayoutManager by lazy(LazyThreadSafetyMode.NONE) {
        LinearLayoutManager(context, HORIZONTAL, false)
    }

    private var isFailed = false

    private val scrollListener by lazy(LazyThreadSafetyMode.NONE) {
        object : RecyclerView.OnScrollListener() {
            override fun onScrolled(recyclerView: RecyclerView, dx: Int, dy: Int) {
                super.onScrolled(recyclerView, dx, dy)
                val snappedView = snapHelper.findSnapView(mLayoutManager) ?: return

                val position = mLayoutManager.getPosition(snappedView)
                binding.pcCoverTemplate.setCurrentIndicator(position)
            }
        }
    }

    private val mAdapter: PlayAutoGeneratedCoverAdapter by lazyThreadSafetyNone {
        PlayAutoGeneratedCoverAdapter(viewModel.userAccessToken, this)
    }
    private val snapHelper = PagerSnapHelper()

    private var mListener: PlayBroadcastSetupCoverBottomSheet.Listener? = null
    private var mEntryPoint = ""

    override fun getScreenName(): String {
        return TAG
    }

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        _binding = FragmentSetupCoverChooseTemplateBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        setupViews()
        observeProductTag()
        observeUIState()
        observeUIEvent()
    }

    override fun onResume() {
        super.onResume()
        viewModel.submitAction(PlayBroSetupCoverAction.CheckButtonState)
    }

    override fun onDestroyView() {
        super.onDestroyView()
        viewModel.submitAction(PlayBroSetupCoverAction.RemoveStateAutoGeneratedCover)
        binding.rvCoverTemplate.removeOnScrollListener(scrollListener)
        _binding = null
        mListener = null
    }

    private fun observeProductTag() {
        viewLifecycleOwner.lifecycleScope.launchWhenCreated {
            viewModel.observableProduct.collect {
                showTemplate(it.isNotEmpty())
                if (it.isNotEmpty()) {
                    viewModel.submitAction(PlayBroSetupCoverAction.GetAutoGeneratedImageCoverPreview)
                }
            }
        }
    }

    private fun observeUIState() {
        viewLifecycleOwner.lifecycleScope.launchWhenCreated {
            viewModel.autoGeneratedCover.withCache().collectLatest { (prevState, state) ->
                renderAutoGeneratedCover(prevState, state)
            }
        }
    }

    private fun observeUIEvent() {
        viewLifecycleOwner.lifecycleScope.launchWhenCreated {
            viewModel.uiEvent.collect { event ->
                when (event) {
                    is PlayBroSetupCoverEvent.SubmitCoverEvent -> {
                        binding.btnSetupCoverChooseTemplateSave.isLoading = event.isLoading
                        if (!event.isLoading && event.throwable == null) {
                            mListener?.dismissSetupCover(TAB_AUTO_GENERATED)
                            mListener?.onUploadCoverSuccess()
                            return@collect
                        } else if (!event.isLoading && event.throwable != null) {
                            toaster.showError(event.throwable)
                        }
                    }
                    is PlayBroSetupCoverEvent.ButtonSetupCoverEvent -> {
                        binding.btnSetupCoverChooseTemplateDelete.showWithCondition(
                            event.showDelete
                        )
                        binding.btnSetupCoverChooseTemplateSave.isEnabled = event.isEnabled
                    }
                    is PlayBroSetupCoverEvent.ErrorAutoGeneratedCover -> {
                        if (event.throwable == null) return@collect
                        toaster.showError(
                            err = event.throwable,
                            duration = Toaster.LENGTH_INDEFINITE,
                            actionLabel = getString(R.string.play_broadcast_try_again),
                            actionListener = {
                                event.onRetry?.invoke()
                            }
                        )
                    }
                }
            }
        }
    }

    private fun showTemplate(showTemplate: Boolean) {
        binding.tvAddProductTitle.text = if (mEntryPoint == PlayBroadcastPostVideoFragment.PAGE_NAME) getString(R.string.play_prepare_cover_title_choose_template_title_report_page) else getString(R.string.play_prepare_cover_title_choose_template_title)
        binding.tvAddProductDescription.text = if (mEntryPoint == PlayBroadcastPostVideoFragment.PAGE_NAME) getString(R.string.play_prepare_cover_title_header_description_report_page) else getString(R.string.play_prepare_cover_title_header_description)
        binding.clEmptyProduct.showWithCondition(!showTemplate)
        binding.clChooseTemplateContainer.showWithCondition(showTemplate)
    }

    private fun setupViews() = with(binding) {
        rvCoverTemplate.apply {
            adapter = mAdapter
            layoutManager = mLayoutManager
            if (itemDecorationCount == 0) addItemDecoration(AutoGeneratedCoverItemDecoration(context))
            addOnScrollListener(scrollListener)
        }
        snapHelper.attachToRecyclerView(rvCoverTemplate)

        btnEmptyProduct.showWithCondition(mEntryPoint != PlayBroadcastPostVideoFragment.PAGE_NAME)
        btnEmptyProduct.setOnClickListener {
            analytic.clickTemplateCoverAddProduct(mEntryPoint)
            mListener?.setupCoverProductClicked()
        }
        btnSetupCoverChooseTemplateSave.setOnClickListener {
            if (btnSetupCoverChooseTemplateDelete.isVisible) {
                analytic.clickSaveGeneratedCoverOption(viewModel.autoGeneratedCoverAnalyticData, mEntryPoint)
            } else {
                analytic.clickSaveGeneratedCover(viewModel.autoGeneratedCoverAnalyticData, mEntryPoint)
            }
            viewModel.submitAction(PlayBroSetupCoverAction.SetUploadAutoGeneratedCover)
        }
        btnSetupCoverChooseTemplateDelete.setOnClickListener {
            toaster.showToaster(getString(R.string.play_setup_cover_auto_generated_cover_delete_cover_message))
            analytic.clickDeleteGeneratedCover(viewModel.autoGeneratedCoverAnalyticData, mEntryPoint)
            viewModel.submitAction(PlayBroSetupCoverAction.UnSelectAutoGeneratedCover)
            mListener?.onDeleteAutoGeneratedCover()
        }
    }

    private fun renderAutoGeneratedCover(
        prev: List<AutoGeneratedCoverUIModel>?,
        value: List<AutoGeneratedCoverUIModel>
    ) {
        if (prev == value) return

        if (binding.rvCoverTemplate.isComputingLayout.not()) mAdapter.setItemsAndAnimateChanges(value)

        if (prev?.size == value.size) return
        binding.pcCoverTemplate.setIndicator(value.size)
    }

    override fun onClickItem(position: Int) {
        viewModel.submitAction(PlayBroSetupCoverAction.SelectAutoGeneratedCover(position))
        analytic.clickSelectGeneratedCover(viewModel.autoGeneratedCoverAnalyticData, mEntryPoint)
        scrollItemToCenter(position)
    }

    @SuppressLint("NotifyDataSetChanged")
    override fun onFailLoadResources(exception: Exception?) {
        if (exception == null || isFailed || view == null) return

        isFailed = true

        toaster.showError(
            exception,
            duration = Toaster.LENGTH_INDEFINITE,
            actionLabel = getString(R.string.play_broadcast_try_again),
            actionListener = {
                analytic.clickTryAgainTemplateCoverBottomSheet(mEntryPoint)

                isFailed = false
                mAdapter.notifyDataSetChanged()
            },
            customErrMessage = getString(R.string.play_setup_cover_auto_generated_cover_error_load_message)
        )
    }

    private fun scrollItemToCenter(position: Int) {
        val rv = binding.rvCoverTemplate
        val itemView = rv.findViewHolderForAdapterPosition(position)?.itemView
        if (itemView == null) {
            mLayoutManager.scrollToPosition(position)
            return
        }
        val centerOfScreen = rv.width.div(HALF_DIVED) - itemView.width.div(HALF_DIVED)
        mLayoutManager.scrollToPositionWithOffset(position, centerOfScreen)
    }

    fun setupData(
        listener: PlayBroadcastSetupCoverBottomSheet.Listener?,
        entryPoint: String
    ) {
        mListener = listener
        mEntryPoint = entryPoint
    }

    companion object {
        const val TAG = "PlayBroadcastSetupAutoGeneratedCoverFragment"
        private const val HALF_DIVED = 2

        fun getFragment(
            fragmentManager: FragmentManager,
            classLoader: ClassLoader
        ): PlayBroadcastSetupAutoGeneratedCoverFragment {
            val oldInstance =
                fragmentManager.findFragmentByTag(TAG) as? PlayBroadcastSetupAutoGeneratedCoverFragment
            return oldInstance ?: fragmentManager.fragmentFactory.instantiate(
                classLoader,
                PlayBroadcastSetupAutoGeneratedCoverFragment::class.java.name
            ) as PlayBroadcastSetupAutoGeneratedCoverFragment
        }
    }
}
