package com.tokopedia.categorylevels.analytics

const val EVENT_CLICK_CATEGORY = "clickCategory"
const val EVENT_PROMO_VIEW = "promoView"
const val EVENT_PROMO_CLICK = "promoClick"
const val VALUE_CATEGORY_PAGE = "category page"
const val VALUE_TOP_NAV = "top nav"
const val KEY_BUSINESS_UNIT = "businessUnit"
const val KEY_CURRENT_SITE = "currentSite"
const val KEY_USER_ID = "userId"
const val BUSINESS_UNIT_VALUE = "category"
const val CURRENT_SITE_VALUE = "tokopediamarketplace"
const val EVENT_CLICK_BACK = "click back button"
const val EVENT_CLICK_SEARCH = "click search icon"
const val EVENT_CLICK_SHARE = "click share icon"
const val IMPRESSION_NAVIGATION_CHIPS = "impression navigation chips"
const val CLICK_NAVIGATION_CHIPS = "click navigation chips"
const val CLICK_NAVIGATION_DROPDOWN = "click navigation dropdown"
const val CLICK_FILTER_CHIPS = "click filter chips"
