export const config = {
    imageBasePath : "https://ecs7.tokopedia.net/img/android_o2o/"
} 

export const icons = {
    error_icon: 'https://ecs7.tokopedia.net/img/android_o2o/Error-Icon.png',
    arrow_back: 'https://ecs7.tokopedia.net/img/android_o2o/arrow_back.png',
    anz: 'https://ecs7.tokopedia.net/img/android_o2o/Logo-ANZ.png',
    bca: 'https://ecs7.tokopedia.net/img/android_o2o/Logo-BCA.png',
    bni: 'https://ecs7.tokopedia.net/img/android_o2o/Logo-BNI.png',
    bri: 'https://ecs7.tokopedia.net/img/android_o2o/Logo-BRI.png',
    bukopin: 'https://ecs7.tokopedia.net/img/android_o2o/Logo-Bukopin.png',
    cimb: 'https://ecs7.tokopedia.net/img/android_o2o/Logo-CIMB.png',
    citi: 'https://ecs7.tokopedia.net/img/android_o2o/Logo-Citi.png',
    danamon: 'https://ecs7.tokopedia.net/img/android_o2o/Logo-Danamon.png',
    hsbc: 'https://ecs7.tokopedia.net/img/android_o2o/Logo-HSBC.png',
    jcb: 'https://ecs7.tokopedia.net/img/android_o2o/Logo-JCB.png',
    mnc: 'https://ecs7.tokopedia.net/img/android_o2o/Logo-MNC.png',
    mandiri: 'https://ecs7.tokopedia.net/img/android_o2o/Logo-Mandiri.png',
    mastercard: 'https://ecs7.tokopedia.net/img/android_o2o/Logo-MasterCard.png',
    maybank: 'https://ecs7.tokopedia.net/img/android_o2o/Logo-Maybank.png',
    ocbc: 'https://ecs7.tokopedia.net/img/android_o2o/Logo-OCBCNISP.png',
    panin: 'https://ecs7.tokopedia.net/img/android_o2o/Logo-Panin.png',
    permata: 'https://ecs7.tokopedia.net/img/android_o2o/Logo-Permata.png',
    standard: 'https://ecs7.tokopedia.net/img/android_o2o/Logo-Standard.png',
    uob: 'https://ecs7.tokopedia.net/img/android_o2o/Logo-UOB.png',
    visa: 'https://ecs7.tokopedia.net/img/android_o2o/Logo-Visa.png',
    success: 'https://ecs7.tokopedia.net/img/android_o2o/Success_icon.png',
    arrow_down_grey: 'https://ecs7.tokopedia.net/img/android_o2o/arrow-down-grey.png',
    arrow_down:'https://ecs7.tokopedia.net/img/android_o2o/arrow-down.png',
    arrow_up: 'https://ecs7.tokopedia.net/img/android_o2o/arrow-up.png',
    btn_minus: 'https://ecs7.tokopedia.net/img/android_o2o/btn_minus.png',
    btn_plus: 'https://ecs7.tokopedia.net/img/android_o2o/btn_plus.png',
    close_icon2: 'https://ecs7.tokopedia.net/img/android_o2o/close-icon 2.png',
    close_icon: 'https://ecs7.tokopedia.net/img/android_o2o/close-icon.png',
    cvv: 'https://ecs7.tokopedia.net/img/android_o2o/cvv-icon.png',
    cart: 'https://ecs7.tokopedia.net/img/android_o2o/icon-Cart.png',
    cc_info: 'https://ecs7.tokopedia.net/img/android_o2o/icon-CreditCards-Info.png',
    burger_icon: 'https://ecs7.tokopedia.net/img/android_o2o/icon-burgermenu.png',
    icon_back: 'https://ecs7.tokopedia.net/img/android_o2o/icon_back.png',
    loading: 'https://ecs7.tokopedia.net/img/android_o2o/loading.gif',
    secure_guarantee: 'https://ecs7.tokopedia.net/img/android_o2o/secure-guarantee.png',
    shopping_basket: 'https://ecs7.tokopedia.net/img/android_o2o/shopping-basket.png',
    toped: 'https://ecs7.tokopedia.net/img/android_o2o/toped.png',
    trash_all: 'https://ecs7.tokopedia.net/img/android_o2o/trash-all.png',
    trash: 'https://ecs7.tokopedia.net/img/android_o2o/trash.png'
}