package com.tokopedia.product.detail.di

object RawQueryKeyConstant {
    const val QUERY_SHOP = "query_shop"
    const val QUERY_SHOP_SPEED = "query_shop_speed"
    const val QUERY_SHOP_CHAT_SPEED = "query_shop_chat_speed"
    const val QUERY_SHOP_RATING = "query_shop_rating"
    const val QUERY_SHOP_BADGE = "query_shop_badge"
    const val QUERY_SHOP_COMMITMENT = "query_shop_commitment"
    const val QUERY_PRODUCT_INFO = "query_product_info"
    const val QUERY_TRADE_IN = "query_trade_in"
    const val QUERY_PRODUCT_CATALOG = "query_product_catalog"
    const val QUERY_VARIANT = "query_variant"
    const val QUERY_WISHLIST_STATUS = "query_is_wishlisted"
    const val QUERY_PRODUCT_RATING = "product_rating"
    const val QUERY_WISHLIST_COUNT = "wishlist_count"
    const val QUERY_GET_VOUCHER = "voucher_list"
    const val QUERY_GET_RATE_ESTIMATION = "rate_estimation"
    const val QUERY_GET_IMAGE_REVIEW = "image_review"
    const val QUERY_GET_TOP_ADS_MANAGE_PRODUCT = "top_ads_manage_product"
    const val QUERY_GET_MOST_HELPFUL_REVIEW = "helpful_review"
    const val QUERY_GET_LATEST_TALK = "latest_talk"
    const val QUERY_DISCUSSION_MOST_HELPFUL = "discussion_most_helpful"
    const val QUERY_DISPLAY_ADS = "display_ads"
    const val QUERY_OTHER_PRODUCT = "other_product"
    const val QUERY_PRODUCT_AFFILIATE = "product_affiliate"
    const val QUERY_INSTALLMENT = "installment"
    const val MUTATION_FAVORITE_SHOP = "favorite_shop"
    const val QUERY_SHOP_COD_STATUS = "shop_cod_status"
    const val QUERY_USER_COD_STATUS = "user_cod_status"
    const val QUERY_MULTI_ORIGIN = "multiorigin"
    const val QUERY_PRODUCT_PP = "query_ppGetItemDetailPage"
    const val QUERY_RECOMMEN_PRODUCT = "query_recommendation_product"
    const val QUERY_SHOP_FEATURE = "query_shop_feature"
    const val QUERY_GET_PDP_LAYOUT = "query_get_pdp_layout"
    const val QUERY_TICKER = "query_ticker"
    const val MUTATION_AFFILIATE_TRACKING = "mutation_af_tracking"
    const val QUERY_PDP_FINANCING_RECOMMENDATION = "pdpFinancingRecommendation"
    const val QUERY_PDP_FINANCING_CALCULATION = "pdpFinancingCalculation"
    const val MUTATION_NOTIFY_ME = "query_notify_me"
    const val QUERY_GET_CART_TYPE = "pdpGetCartType"
}