package com.tokopedia.product.detail.di

object RawQueryKeyConstant {
    const val QUERY_SHOP = "query_shop"
    const val QUERY_SHOP_BADGE = "query_shop_badge"
    const val QUERY_SHOP_COMMITMENT = "query_shop_commitment"
    const val QUERY_PRODUCT_INFO = "query_product_info"
    const val QUERY_VARIANT = "query_variant"
    const val QUERY_WISHLIST_STATUS = "query_is_wishlisted"
    const val QUERY_PRODUCT_RATING = "product_rating"
    const val QUERY_WISHLIST_COUNT = "wishlist_count"
    const val QUERY_GET_VOUCHER = "voucher_list"
    const val QUERY_GET_RATE_ESTIMATION = "rate_estimation"
    const val QUERY_GET_IMAGE_REVIEW = "image_review"
    const val QUERY_GET_MOST_HELPFUL_REVIEW = "helpful_review"
    const val QUERY_GET_LATEST_TALK = "latest_talk"
    const val QUERY_DISPLAY_ADS = "display_ads"
    const val QUERY_OTHER_PRODUCT = "other_product"
    const val QUERY_PRODUCT_AFFILIATE = "product_affiliate"
    const val QUERY_INSTALLMENT = "installment"
    const val QUERY_CHECKOUTTYPE = "checkout_type"
    const val MUTATION_FAVORITE_SHOP = "favorite_shop"
    const val QUERY_SHOP_COD_STATUS = "shop_cod_status"
    const val QUERY_USER_COD_STATUS = "user_cod_status"
}