package com.tokopedia.sellerhome.settings.analytics

object SettingTrackingConstant {

    const val IMPRESSION = "impression"
    const val CLICK= "click"
    const val CLICK_NAVIGATION_DRAWER = "clickNavigationDrawer"
    const val CLICK_SHOP_SETTING = "clickShopSetting"
    const val VIEW_NAVIGATION_IRIS = "viewNavigationIris"
    const val VIEW_SHOP_SETTING_IRIS = "viewShopSettingIris"
    const val OTHERS_TAB = "others tab"

    const val GOLD_MERCHANT = "gold_merchant"
    const val OFFICIAL_STORE = "official_store"
    const val REGULAR = "regular"
    const val UPGRADE = "upgrade"
    const val VERIFICATION = "verification"
    const val ACTIVE = "active"
    const val INACTIVE = "inactive"
    const val ON_VERIFICATION = "on_verification"

    const val SHOP_PICTURE = "shop picture"
    const val SHOP_NAME = "shop name"
    const val SHOP_ARROW = "shop arrow"
    const val SHOP_BADGE = "shop badge"
    const val SHOP_FOLLOWERS = "shop followers"
    const val SHOP_STATE = "shop state"
    const val ON_SALDO = "on saldo"
    const val ON_TOPADS_CREDIT = "on topads credits"
    const val SHOP_STATISTIC = "shop statistic"
    const val SHOP_ADS_AND_PROMOTION = "shop ads and promotions"
    const val REVIEW = "review"
    const val DISCUSSION = "discussion"
    const val COMPLAINT = "complaint"
    const val FINANCIAL_SERVICE = "financial service"
    const val SELLER_CENTER = "seller center"
    const val TOKOPEDIA_CARE = "tokopedia care"
    const val SETTINGS = "settings"
    const val BACK_ARROW = "back arrow"
    const val SHOP_SETTING = "shop settings"
    const val ACCOUNT_SETTING = "account settings"
    const val APP_SETTING = "app settings"
    const val APPLICATION_SETTING = "application settings"
    const val OTHER_SETTING = "other settings"

    const val SHOP_REGULAR_MERCHANT = "RM"
    const val SHOP_POWER_MERCHANT = "PM"
    const val SHOP_OFFICIAL_STORE = "OS"

}