package com.tokopedia.shop.info.domain.usecase

import com.tokopedia.gql_query_annotation.GqlQueryInterface
import com.tokopedia.graphql.coroutines.data.extensions.getSuccessData
import com.tokopedia.graphql.coroutines.domain.interactor.GraphqlUseCase
import com.tokopedia.graphql.coroutines.domain.repository.GraphqlRepository
import com.tokopedia.graphql.data.model.CacheType
import com.tokopedia.graphql.data.model.GraphqlCacheStrategy
import com.tokopedia.graphql.data.model.GraphqlRequest
import com.tokopedia.shop.info.data.mapper.ProductRevGetShopRatingAndTopicsMapper
import com.tokopedia.shop.info.data.response.ProductRevGetShopRatingAndTopicsResponse
import com.tokopedia.shop.info.domain.entity.ShopRating
import javax.inject.Inject

/**
 * Generated by Tokopedia GQL UseCase Generator plugins version 1.0
 */
class ProductRevGetShopRatingAndTopicsUseCase @Inject constructor(
    private val repository: GraphqlRepository,
    private val mapper: ProductRevGetShopRatingAndTopicsMapper
) : GraphqlUseCase<ProductRevGetShopRatingAndTopicsResponse>(repository) {

    init {
        setCacheStrategy(GraphqlCacheStrategy.Builder(CacheType.ALWAYS_CLOUD).build())
    }


    private val query = object : GqlQueryInterface {
        private val OPERATION_NAME = "productrevGetShopRatingAndTopics"
        private val QUERY = """query productrevGetShopRatingAndTopics(${'$'}shopID: String!) {
  productrevGetShopRatingAndTopics(shopID: ${'$'}shopID) {
    rating {
      totalRatingFmt
      positivePercentageFmt
      totalRating
      totalRatingTextAndImage
      totalRatingTextAndImageFmt
      detail {
        totalReviews
        percentageFloat
        rate
        formattedTotalReviews
      }
      ratingScore
    }
  }
}
"""

        override fun getOperationNameList(): List<String> = listOf(OPERATION_NAME)
        override fun getQuery(): String = QUERY
        override fun getTopOperationName(): String = OPERATION_NAME
    }


    suspend fun execute(param: Param): ShopRating {
        val request = buildRequest(param)
        val response = repository.response(listOf(request))
        return mapper.map(response.getSuccessData())
    }

    private fun buildRequest(param: Param): GraphqlRequest {
        val params = mapOf("shopID" to param.shopID)

        return GraphqlRequest(
            query,
            ProductRevGetShopRatingAndTopicsResponse::class.java,
            params
        )
    }

    data class Param(val shopID: String)

}
