package com.tokopedia.hotel.common.analytics

val PROMO_VIEW = "promoView"
val PROMO_CLICK = "promoClick"
val CLICK_HOTEL = "clickHotel"
val VIEW_HOTEL = "viewHotel"
val PRODUCT_VIEW = "productView"
val PRODUCT_CLICK = "productClick"
val ADD_TO_CART = "addToCart"
val CHECKOUT = "checkout"
val PURCHASE = "purchase"

val DIGITAL_NATIVE = "digital - native"
val DIGITAL_CHECKOUT = "digital - checkout"
val DIGITAL_THANKS = "digital - thanks"

val BANNER_IMPRESSION = "banner impression"
val CLICK_BANNER = "click banner"
val SELECT_DESTINATION = "select destination"
val SELECT_STAY_DATE = "select stay date"
val SELECT_ROOM_GUEST = "select room guest"
val SEARCH_HOTEL = "search hotel"
val VIEW_HOTEL_LIST_IMPRESSION = "view hotel list impression"
val CHOOSE_HOTEL = "choose hotel"
val USER_CLICK_FILTER = "user click filter"
val USER_CLICK_SORT = "user click sort"
val VIEW_HOTEL_PDP = "view hotel pdp"
val CLICK_HOTEL_PHOTO = "click hotel photo"
val CLICK_HOTEL_REVIEWS = "click hotel reviews"
val CHOOSE_VIEW_ROOM = "choose view room"
val VIEW_ROOM_LIST = "view room list"
val CHOOSE_ROOM = "choose room"
val CLICK_ROOM_PHOTO_ON_ROOM_LIST = "click room photo on room list"
val CLICK_ROOM_DETAILS = "click room details"
val CLICK_ROOM_PHOTO_ON_ROOM_PDP = "click room photo on room pdp"
val CHOOSE_ROOM_DETAILS_PDP = "choose room details pdp"
val CLICK_NEXT = "click next"
val CLICK_BAYAR = "click bayar"
val APPLY_PROMO = "apply promo"
val VIEW_PURCHASE_ATTEMPT = "view_purchase_attempt"

val HOTEL_LABEL = "hotel"
val ECOMMERCE_LABEL = "ecommerce"
val PRODUCTS_LABEL = "products"
val PROMOTIONS_LABEL = "promotions"
val ADD_LABEL = "add"
