package com.tokopedia.applink.digital

object DeeplinkConstDigital {
    val MAP = mapOf(
            "pulsa" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "axis" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "im3" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "bolt" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "3" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "pulsa-xl" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "paket-smartfren" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "simpati" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "as" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "mentari" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "paket-data" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet-telkomsel" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet-indosat" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet-xl" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet-axis" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet-im3" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet-mentari" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet-tri" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet-bolt" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet-simpati" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",

            "paket-data/telkomsel" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-data/indosat" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-data/xl" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-data/axis" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-data/im3" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-data/mentari" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-data/tri" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-data/bolt" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-data/simpati" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",

            "roaming" to "tokopedia://digital/form?category_id=20&menu_id=2&template=telcopre",
            "roaming/indosat" to "tokopedia://digital/form?category_id=20&menu_id=2&template=telcopre",
            "roaming/xl" to "tokopedia://digital/form?category_id=20&menu_id=2&template=telcopre",
            "roaming/telkomsel" to "tokopedia://digital/form?category_id=20&menu_id=2&template=telcopre",

            "pascabayar" to "tokopedia://digital/form?category_id=9&menu_id=3&template=telcopost",
            "tagihan/pascabayar" to "tokopedia://digital/form?category_id=9&menu_id=3&template=telcopost",

            "pulsa/axis" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "pulsa/im3" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "pulsa/bolt" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "pulsa/tri" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "pulsa/xl" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "pulsa/smartfren" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "pulsa/simpati" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "pulsa/as" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "pulsa/mentari" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "paket-internet" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet/telkomsel" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet/indosat" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet/xl" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet/axis" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet/im3" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet/mentari" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet/tri" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet/bolt" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet/simpati" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",

            "tv-kabel" to "tokopedia://digital/form?category_id=8&menu_id=154&template=general",
            "indovision" to "tokopedia://digital/form?category_id=8&menu_id=154&operator_id=120&template=general",
            "indihome" to "tokopedia://digital/form?category_id=8&menu_id=154&operator_id=125&template=general",
            "transvision" to "tokopedia://digital/form?category_id=8&menu_id=154&operator_id=121&template=general",
            "bigtv" to "tokopedia://digital/form?category_id=8&menu_id=154&operator_id=100&template=general",
            "k-vision" to "tokopedia://digital/form?category_id=8&menu_id=154&operator_id=173&template=general",

            "tv-kabel/indovision" to "tokopedia://digital/form?category_id=8&menu_id=154&operator_id=120&template=general",
            "tv-kabel/indihome" to "tokopedia://digital/form?category_id=8&menu_id=154&operator_id=125&template=general",
            "tv-kabel/transvision" to "tokopedia://digital/form?category_id=8&menu_id=154&operator_id=121&template=general",
            "tv-kabel/bigtv" to "tokopedia://digital/form?category_id=8&menu_id=154&operator_id=100&template=general",
            "tv-kabel/k-vision" to "tokopedia://digital/form?category_id=8&menu_id=154&operator_id=173&template=general",
            "tv-kabel/firstmedia" to "tokopedia://digital/form?category_id=8&menu_id=154&operator_id=243&template=general",

            "streaming" to "tokopedia://digital/form?category_id=13&menu_id=81&template=voucher",
            "viu" to "tokopedia://digital/form?category_id=13&menu_id=81&operator_id=155&template=voucher",
            "joox" to "tokopedia://digital/form?category_id=13&menu_id=81&operator_id=154&template=voucher",
            "catchplay" to "tokopedia://digital/form?category_id=13&operator_id=153&menu_id=81&template=voucher",
            "iflix" to "tokopedia://digital/form?category_id=13&operator_id=160&menu_id=81&template=voucher",
            "genflix" to "tokopedia://digital/form?category_id=13&operator_id=161&menu_id=81&template=voucher",
            "wifi-id" to "tokopedia://digital/form?category_id=13&menu_id=81&operator_id=202&template=voucher",

            "streaming/viu" to "tokopedia://digital/form?category_id=13&menu_id=81&operator_id=155&template=voucher",
            "streaming/joox" to "tokopedia://digital/form?category_id=13&menu_id=81&operator_id=154&template=voucher",
            "streaming/catchplay" to "tokopedia://digital/form?category_id=13&operator_id=153&menu_id=81&template=voucher",
            "streaming/iflix" to "tokopedia://digital/form?category_id=13&operator_id=160&menu_id=81&template=voucher",
            "streaming/genflix" to "tokopedia://digital/form?category_id=13&operator_id=161&menu_id=81&template=voucher",
            "streaming/wifi-id" to "tokopedia://digital/form?category_id=13&menu_id=81&operator_id=202&template=voucher",
            "streaming/bein-sports" to "tokopedia://digital/form?category_id=13&menu_id=81&operator_id=688&template=voucher",
            "streaming/spotify" to "tokopedia://digital/form?category_id=13&menu_id=81&operator_id=775&template=voucher",

            "belajar" to "tokopedia://digital/form?category_id=111&menu_id=84&template=voucher",
            "belajar/squline" to "tokopedia://digital/form?category_id=111&menu_id=84&operator_id=540&template=voucher",
            "belajar/ruangguru" to "tokopedia://digital/form?category_id=111&menu_id=84&operator_id=702&template=voucher",
            "belajar/quipper" to "tokopedia://digital/form?category_id=111&menu_id=84&operator_id=704&template=voucher",
            "belajar/zenius" to "tokopedia://digital/form?category_id=111&menu_id=84&operator_id=705&template=voucher",
            "belajar/lip" to "tokopedia://digital/form?category_id=111&menu_id=84&operator_id=706&template=voucher",
            "belajar/purwadhika" to "tokopedia://digital/form?category_id=111&menu_id=84&operator_id=708&template=voucher",

            "telepon" to "tokopedia://digital/form?category_id=10&menu_id=121&template=general",
            "tagihan/telepon" to "tokopedia://digital/form?category_id=10&menu_id=121&template=general",
            "pgn" to "tokopedia://digital/form?category_id=14&menu_id=124&template=general",
            "tagihan/pgn" to "tokopedia://digital/form?category_id=14&menu_id=124&template=general",
            "pln" to "tokopedia://digital/form?category_id=3&menu_id=113&template=general",
            "token-listrik" to "tokopedia://digital/form?category_id=3&menu_id=113&operator_id=6&template=general",
            "tagihan-listrik" to "tokopedia://digital/form?category_id=3&menu_id=113&operator_id=18&template=general",
            "donasi" to "tokopedia://digital/form?category_id=12&menu_id=83&template=voucher",
            "donasi-online" to "tokopedia://digital/form?category_id=12&menu_id=83&template=voucher",
            "dompet-dhuafa" to "tokopedia://digital/form?category_id=12&menu_id=83&operator_id=97&template=voucher",

            "tagihan" to "tokopedia://digital/form?category_id=3&menu_id=113&operator_id=18&template=general",
            "pln/token-listrik" to "tokopedia://digital/form?category_id=3&menu_id=113&operator_id=6&template=general",
            "pln/tagihan-listrik" to "tokopedia://digital/form?category_id=3&menu_id=113&operator_id=18&template=general",

            "bpjs" to "tokopedia://digital/form?category_id=4&menu_id=126&template=general",
            "bpjs/kesehatan" to "tokopedia://digital/form?category_id=4&menu_id=126&operator_id=13&template=general",
            "tagihan/bpjs-kesehatan" to "tokopedia://digital/form?category_id=4&menu_id=126&operator_id=13&template=general",
            "bpjs/ketenagakerjaan" to "tokopedia://digital/form?category_id=4&menu_id=126&operator_id=14&template=general",
            "tagihan/bpjs-ketenagakerjaan" to "tokopedia://digital/form?category_id=4&menu_id=126&operator_id=14&template=general",

            "top-up/mtix" to "tokopedia://digital/form?category_id=31&menu_id=128&template=general",
            "top-up/emoney" to "tokopedia://digital/form?category_id=34&operator_id=578",
            "top-up/brizzi" to "tokopedia://digital/form?category_id=34&operator_id=1015",
            "top-up/ovo" to "tokopedia://digital/form?category_id=48&menu_id=162&template=general",

            "pajak" to "tokopedia://digital/form?category_id=22&menu_id=127&template=general",
            "pajak/samsat" to "tokopedia://digital/form?category_id=49&menu_id=155&template=general",
            "pajak/pbb/jawa-tengah" to "tokopedia://digital/form?category_id=49&operator_id=970&menu_id=155&template=general",
            "pajak/pbb" to "tokopedia://digital/form?category_id=22&menu_id=127&template=general",
            "pajak/pbb/kota-bandung" to "tokopedia://digital/form?category_id=22&operator_id=1034&menu_id=127&template=general",
            "pajak/pbb/kab-cirebon" to "tokopedia://digital/form?category_id=22&operator_id=1035&menu_id=127&template=general",
            "pajak/pbb/kota-serang" to "tokopedia://digital/form?category_id=22&operator_id=1032&menu_id=127&template=general",
            "pajak/pbb/kota-sukabumi" to "tokopedia://digital/form?category_id=22&operator_id=1031&menu_id=127&template=general",
            "pajak/pbb/kota-tangerang" to "tokopedia://digital/form?category_id=22&operator_id=1030&menu_id=127&template=general",
            "pajak/pbb/kota-tangerang-selatan" to "tokopedia://digital/form?category_id=22&operator_id=1029&menu_id=127&template=general",
            "pajak/pbb/kab-lebak" to "tokopedia://digital/form?category_id=22&operator_id=1024&menu_id=127&template=general",
            "pajak/pbb/kab-bekasi" to "tokopedia://digital/form?category_id=22&operator_id=1028&menu_id=127&template=general",
            "pajak/pbb/kab-subang" to "tokopedia://digital/form?category_id=22&operator_id=1027&menu_id=127&template=general",
            "retribusi" to "tokopedia://digital/form?category_id=25&menu_id=125&template=general",
            "pdam" to "tokopedia://digital/form?category_id=5&menu_id=120&template=general",
            "tagihan/pdam" to "tokopedia://digital/form?category_id=5&menu_id=120&template=general",

            "angsuran" to "tokopedia://digital/form?category_id=7&menu_id=123&template=general",
            "kredit-mobil" to "tokopedia://digital/form?category_id=7&menu_id=123&template=general",
            "aeon-credit" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=166&template=general",
            "astra-credit" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=168&template=general",
            "kreditplus" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=150&template=general",
            "mandiri-tunas-finance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=124&template=general",
            "arthaprima-finance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=123&template=general",
            "woka-finance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=122&template=general",
            "mega-finance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=119&template=general",
            "al-ijarah-finance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=111&template=general",
            "bimafinance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=89&template=general",
            "mega-auto-finance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=108&template=general",
            "mega-central-finance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=109&template=general",
            "mpm-finance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=90&template=general",
            "radana-finance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=88&template=general",
            "smart-multi-finance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=110&template=general",
            "nsc-finance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=167&template=general",
            "baf" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=91&template=general",

            "angsuran/aeon" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=166&template=general",
            "angsuran/mobil" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=168&template=general",
            "angsuran/astra" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=168&template=general",
            "angsuran/motor" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=255&template=general",
            "angsuran/kreditplus" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=150&template=general",
            "angsuran/mandiri-tunas-finance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=124&template=general",
            "angsuran/arthaprima-finance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=123&template=general",
            "angsuran/woka-finance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=122&template=general",
            "angsuran/mega-finance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=119&template=general",
            "angsuran/al-ijarah-finance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=111&template=general",
            "angsuran/bimafinance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=89&template=general",
            "angsuran/mega-auto-finance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=108&template=general",
            "angsuran/mega-central-finance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=109&template=general",
            "angsuran/mpm-finance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=90&template=general",
            "angsuran/radana-finance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=88&template=general",
            "angsuran/smart-multi-finance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=110&template=general",
            "angsuran/nsc-finance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=167&template=general",
            "angsuran/baf" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=91&template=general",
            "angsuran/indomobil-finance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=255&template=general",
            "angsuran/bfi-finance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=526&template=general",
            "angsuran/suzuki-finance" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=628&template=general",
            "angsuran/olympindo" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=636&template=general",
            "angsuran/kredivo" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=662&template=general",
            "angsuran/btn" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=661&template=general",
            "angsuran/home-credit" to "tokopedia://digital/form?category_id=7&menu_id=123&operator_id=653&template=general",

            )
}