package com.tokopedia.applink.digital

object DeeplinkConstDigital {
    val MAP = mapOf(
            "pulsa" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "axis" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "im3" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "bolt" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "3" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "pulsa-xl" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "paket-smartfren" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "simpati" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "as" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "mentari" to "tokopedia://digital/form?category_id=1&menu_id=2&template=telcopre",
            "paket-data" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet-telkomsel" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet-indosat" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet-xl" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet-axis" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet-im3" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet-mentari" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet-tri" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet-bolt" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "paket-internet-simpati" to "tokopedia://digital/form?category_id=2&menu_id=2&template=telcopre",
            "roaming" to "tokopedia://digital/form?category_id=20&menu_id=2&template=telcopre",
            "tv-kabel" to "tokopedia://digital/form?category_id=8&menu_id=154&template=general",
            "indovision" to "tokopedia://digital/form?category_id=8&menu_id=154&operator_id=120&template=general",
            "indihome" to "tokopedia://digital/form?category_id=8&menu_id=154&operator_id=125&template=general",
            "transvision" to "tokopedia://digital/form?category_id=8&menu_id=154&operator_id=121&template=general",
            "bigtv" to "tokopedia://digital/form?category_id=8&menu_id=154&operator_id=100&template=general",
            "orangetv-prepaid" to "tokopedia://digital/form?category_id=8&menu_id=154&operator_id=158&template=general",
            "orangetv-postpaid" to "tokopedia://digital/form?category_id=8&menu_id=154&operator_id=157&template=general",
            "k-vision" to "tokopedia://digital/form?category_id=8&menu_id=154&operator_id=173&template=general",
            "top-tv" to "tokopedia://digital/form?category_id=8&menu_id=154&operator_id=144&template=general",
            "nexmedia" to "tokopedia://digital/form?category_id=8&menu_id=154&operator_id=159&template=general",
            "okevision" to "tokopedia://digital/form?category_id=8&menu_id=154&operator_id=143&template=general",
            "streaming" to "tokopedia://digital/form?category_id=13&menu_id=81&template=voucher",
            "viu" to "tokopedia://digital/form?category_id=13&menu_id=81&template=voucher",
            "joox" to "tokopedia://digital/form?category_id=13&menu_id=81&template=voucher",
            "catchplay" to "tokopedia://digital/form?category_id=13&menu_id=81&template=voucher",
            "iflix" to "tokopedia://digital/form?category_id=13&menu_id=81&template=voucher",
            "genflix" to "tokopedia://digital/form?category_id=13&menu_id=81&template=voucher",
            "wifi-id" to "tokopedia://digital/form?category_id=13&menu_id=81&template=voucher",
            "hooq" to "tokopedia://digital/form?category_id=13&menu_id=81&template=voucher",
            "pln" to "tokopedia://digital/form?category_id=3&menu_id=113&template=general",
            "token-listrik" to "tokopedia://digital/form?category_id=3&menu_id=113&operator_id=6&template=general",
            "tagihan-listrik" to "tokopedia://digital/form?category_id=3&menu_id=113&operator_id=18&template=general",
            "donasi-online" to "tokopedia://digital/form?category_id=12&menu_id=83&template=voucher",
            "dompet-dhuafa" to "tokopedia://digital/form?category_id=12&menu_id=83&operator_id=97&template=voucher",
            "voucher" to "tokopedia://digital/form?category_id=24&menu_id=82&template=voucher",
            "voucher/kfc" to "tokopedia://digital/form?category_id=24&menu_id=82&operator_id=244&template=voucher",
            "voucher/lotteria" to "tokopedia://digital/form?category_id=24&menu_id=82&operator_id=248&template=voucher",
            "voucher/hop-hop" to "tokopedia://digital/form?category_id=24&menu_id=82&operator_id=247&template=voucher",
            "voucher/tous-les-jours" to "tokopedia://digital/form?category_id=24&menu_id=82&operator_id=246&template=voucher",
            "voucher/breadlife" to "tokopedia://digital/form?category_id=24&menu_id=82&operator_id=245&template=voucher",
    )
}