mutation updateName($fullname: String!, $currValidateToken: String) {
    userProfileUpdate(fullname: $fullname, validateToken: $currValidateToken) {
        isSuccess
        completionScore
        errors
    }
}