package com.tokopedia.product.edit.view.viewmodel

import com.tokopedia.abstraction.base.view.adapter.Visitable
import com.tokopedia.product.edit.view.adapter.ProductAddVideoRecommendationAdapterTypeFactory

interface ProductAddVideoRecommendationBaseViewModel : Visitable<ProductAddVideoRecommendationAdapterTypeFactory>