package com.tokopedia.content.common.ui.itemdecoration

import android.content.Context
import android.graphics.Rect
import android.view.View
import androidx.recyclerview.widget.RecyclerView
import com.tokopedia.content.common.R

/**
 * Created by fachrizalmrsln on 18/01/23
 */
class AutoGeneratedCoverItemDecoration(
    context: Context
) : RecyclerView.ItemDecoration() {

    companion object {
        private const val FIRST_ITEM = 0
    }

    private val spaceItemEdge = context.resources.getDimensionPixelOffset(R.dimen.content_common_space_86)
    private val spaceItem = context.resources.getDimensionPixelOffset(R.dimen.content_common_space_16)

    override fun getItemOffsets(
        outRect: Rect,
        view: View,
        parent: RecyclerView,
        state: RecyclerView.State
    ) {
        val position = parent.getChildAdapterPosition(view)
        val last = parent.adapter?.itemCount ?: FIRST_ITEM

        when (position) {
            FIRST_ITEM -> outRect.left = spaceItemEdge
            last - 1 -> {
                outRect.left = spaceItem
                outRect.right = spaceItemEdge
            }
            else -> outRect.left = spaceItem
        }
    }

}
