package com.tokopedia.tokofood.feature.ordertracking.presentation.adapter

import com.tokopedia.tokofood.feature.ordertracking.presentation.viewholder.DriverSectionViewHolderPayloadViewHolder
import com.tokopedia.tokofood.feature.ordertracking.presentation.viewholder.InvoiceOrderNumberViewHolderPayloadViewHolder
import com.tokopedia.tokofood.feature.ordertracking.presentation.viewholder.OrderDetailToggleCtaViewHolderPayloadViewHolder
import com.tokopedia.tokofood.feature.ordertracking.presentation.viewholder.OrderTrackingErrorViewHolder
import com.tokopedia.tokofood.feature.ordertracking.presentation.viewholder.OrderTrackingTickerViewHolder
import com.tokopedia.tokofood.feature.ordertracking.presentation.viewholder.TemporaryFinishOrderViewHolder

interface OrderTrackingListener : OrderDetailToggleCtaViewHolderPayloadViewHolder.OrderDetailToggleCtaListener,
    OrderTrackingTickerViewHolder.Listener, TemporaryFinishOrderViewHolder.Listener,
    DriverSectionViewHolderPayloadViewHolder.Listener, OrderTrackingErrorViewHolder.Listener,
    InvoiceOrderNumberViewHolderPayloadViewHolder.Listener