package com.tokopedia.pocnewrelic

const val ANDROID = "android"
const val KEY_EVENT_TYPE = "eventType"
const val KEY_APP_VERSION = "appVersion"
const val KEY_BROWSER = "browser"
const val KEY_DEVICE_ID = "deviceId"
const val KEY_DEVICE_NAME = "deviceName"
const val KEY_DEVICE_TYPE = "deviceType"
const val KEY_NETWORK_TYPE = "networkType"
const val KEY_OS = "os"
const val KEY_OS_VERSION = "osVersion"
const val KEY_REFERRER = "referrer"
const val KEY_PAGE_NAME = "pageName"
const val KEY_TENANT_ID = "tenantId"
const val KEY_USER_AGENT = "userAgent"
const val KEY_PACKAGE_NAME = "packageName"
const val KEY_USER_ID = "userId"
const val KEY_VERSION_CODE = "versionCode"
const val KEY_PLT = "pageLoadTime"
const val PLT_PREPARE = "pageLoadTimePrepare"
const val PLT_NETWORK = "pageLoadTimeNetwork"
const val PLT_RENDER = "pageLoadTimeUI"
const val PLT_COMPONENT_NETWORK = "component%sLoadTimeNetwork"
