package com.tokopedia.play.broadcaster.di

import androidx.fragment.app.Fragment
import androidx.fragment.app.FragmentFactory
import com.tokopedia.abstraction.base.view.fragment.FragmentKey
import com.tokopedia.abstraction.base.view.fragment.TkpdFragmentFactory
import com.tokopedia.content.product.picker.seller.di.ProductPickerFragmentModule
import com.tokopedia.content.product.picker.seller.view.bottomsheet.ProductPickerUserBottomSheet
import com.tokopedia.play.broadcaster.view.bottomsheet.PlayBroInteractiveBottomSheet
import com.tokopedia.play.broadcaster.view.bottomsheet.PlayBroSelectGameBottomSheet
import com.tokopedia.play.broadcaster.view.bottomsheet.stats.PlayBroadcastLiveStatsBottomSheet
import com.tokopedia.play.broadcaster.view.bottomsheet.PlayBroadcastSetupCoverBottomSheet
import com.tokopedia.play.broadcaster.view.bottomsheet.estimatedincome.EstimatedIncomeDetailBottomSheet
import com.tokopedia.play.broadcaster.view.bottomsheet.livetovod.PlayBroLiveToVodBottomSheet
import com.tokopedia.play.broadcaster.view.fragment.PlayBroadcastPreparationFragment
import com.tokopedia.play.broadcaster.view.fragment.PlayBroadcastUserInteractionFragment
import com.tokopedia.play.broadcaster.view.fragment.PlayPermissionFragment
import com.tokopedia.play.broadcaster.view.fragment.beautification.BeautificationSetupFragment
import com.tokopedia.play.broadcaster.view.fragment.beautification.BeautificationTabFragment
import com.tokopedia.play.broadcaster.view.fragment.dialog.InteractiveSetupDialogFragment
import com.tokopedia.play.broadcaster.view.fragment.setup.cover.PlayBroadcastSetupAutoGeneratedCoverFragment
import com.tokopedia.play.broadcaster.view.fragment.setup.cover.PlayBroadcastSetupCoverUploadImageFragment
import com.tokopedia.play.broadcaster.view.fragment.summary.PlayBroadcastPostVideoFragment
import com.tokopedia.play.broadcaster.view.fragment.summary.PlayBroadcastReportFragment
import com.tokopedia.play.broadcaster.view.fragment.summary.PlayBroadcastSummaryFragment
import dagger.Binds
import dagger.Module
import dagger.multibindings.IntoMap

/**
 * Created by jegul on 27/05/20
 */
@Module(
    includes = [
        ProductPickerFragmentModule::class,
    ]
)
abstract class PlayBroadcastFragmentModule {

    @Binds
    abstract fun bindFragmentFactory(fragmentFactory: TkpdFragmentFactory): FragmentFactory

    @Binds
    @IntoMap
    @FragmentKey(PlayBroadcastPreparationFragment::class)
    abstract fun getPlayBroadcastPreparationFragment(fragment: PlayBroadcastPreparationFragment): Fragment

    @Binds
    @IntoMap
    @FragmentKey(PlayBroadcastSummaryFragment::class)
    abstract fun getPlayBroadcastSummaryFragment(fragment: PlayBroadcastSummaryFragment): Fragment

    @Binds
    @IntoMap
    @FragmentKey(PlayBroadcastReportFragment::class)
    abstract fun getPlayBroadcastReportFragment(fragment: PlayBroadcastReportFragment): Fragment

    @Binds
    @IntoMap
    @FragmentKey(PlayBroadcastUserInteractionFragment::class)
    abstract fun getPlayLiveBroadcastFragment(fragment: PlayBroadcastUserInteractionFragment): Fragment

    @Binds
    @IntoMap
    @FragmentKey(PlayPermissionFragment::class)
    abstract fun getPermissionFragment(fragment: PlayPermissionFragment): Fragment

    /**
     * Setup
     */
    @Binds
    @IntoMap
    @FragmentKey(PlayBroadcastSetupCoverBottomSheet::class)
    abstract fun getSetupCoverBottomSheet(fragment: PlayBroadcastSetupCoverBottomSheet): Fragment

    @Binds
    @IntoMap
    @FragmentKey(PlayBroLiveToVodBottomSheet::class)
    abstract fun getPlayBroLiveToVodBottomSheet(fragment: PlayBroLiveToVodBottomSheet): Fragment

    @Binds
    @IntoMap
    @FragmentKey(PlayBroadcastSetupCoverUploadImageFragment::class)
    abstract fun getSetupCoverUploadImageFragment(fragment: PlayBroadcastSetupCoverUploadImageFragment): Fragment

    @Binds
    @IntoMap
    @FragmentKey(PlayBroadcastSetupAutoGeneratedCoverFragment::class)
    abstract fun getSetupAutoGeneratedCoverFragment(fragment: PlayBroadcastSetupAutoGeneratedCoverFragment): Fragment

    /**
     * Revamp
     */
    @Binds
    @IntoMap
    @FragmentKey(PlayBroadcastPostVideoFragment::class)
    abstract fun getPlayBroadcastPostVideoFragment(fragment: PlayBroadcastPostVideoFragment): Fragment

    /**
     * Interactive
     */
    @Binds
    @IntoMap
    @FragmentKey(PlayBroSelectGameBottomSheet::class)
    abstract fun getPlayBroSelectInteractiveBottomSheet(fragment: PlayBroSelectGameBottomSheet): Fragment

    @Binds
    @IntoMap
    @FragmentKey(PlayBroInteractiveBottomSheet::class)
    abstract fun getPlayBroInteractiveBottomSheet(fragment: PlayBroInteractiveBottomSheet) : Fragment

    @Binds
    @IntoMap
    @FragmentKey(InteractiveSetupDialogFragment::class)
    abstract fun getInteractiveSetupDialogFragment(fragment: InteractiveSetupDialogFragment) : Fragment

    @Binds
    @IntoMap
    @FragmentKey(ProductPickerUserBottomSheet::class)
    abstract fun getPlayPlaceholderBottomSheet(bottomSheet: ProductPickerUserBottomSheet) : Fragment

    /**
     * Beautification
     */
    @Binds
    @IntoMap
    @FragmentKey(BeautificationSetupFragment::class)
    abstract fun getBeautificationSetupFragment(fragment: BeautificationSetupFragment) : Fragment

    @Binds
    @IntoMap
    @FragmentKey(BeautificationTabFragment::class)
    abstract fun getBeautificationTabFragment(fragment: BeautificationTabFragment) : Fragment

    /**
     * Live Stats
     */
    @Binds
    @IntoMap
    @FragmentKey(PlayBroadcastLiveStatsBottomSheet::class)
    abstract fun getPlayBroadcastLiveStatsBottomSheet(fragment: PlayBroadcastLiveStatsBottomSheet) : Fragment

    @Binds
    @IntoMap
    @FragmentKey(EstimatedIncomeDetailBottomSheet::class)
    abstract fun getEstimatedIncomeDetailBottomSheet(fragment: EstimatedIncomeDetailBottomSheet) : Fragment
}
