package com.tokopedia.play.broadcaster.di

import androidx.fragment.app.Fragment
import androidx.fragment.app.FragmentFactory
import com.tokopedia.abstraction.base.view.fragment.FragmentKey
import com.tokopedia.abstraction.base.view.fragment.TkpdFragmentFactory
import com.tokopedia.play.broadcaster.setup.product.view.ProductSetupFragment
import com.tokopedia.play.broadcaster.setup.product.view.bottomsheet.EtalaseListBottomSheet
import com.tokopedia.play.broadcaster.setup.product.view.bottomsheet.ProductChooserBottomSheet
import com.tokopedia.play.broadcaster.setup.product.view.bottomsheet.ProductSortBottomSheet
import com.tokopedia.play.broadcaster.setup.product.view.bottomsheet.ProductSummaryBottomSheet
import com.tokopedia.play.broadcaster.view.bottomsheet.PlayBroSelectGameBottomSheet
import com.tokopedia.play.broadcaster.view.bottomsheet.PlayBroInteractiveBottomSheet
import com.tokopedia.play.broadcaster.view.bottomsheet.PlayBroadcastSetupCoverBottomSheet
import com.tokopedia.play.broadcaster.view.bottomsheet.ProductPickerUGCBottomSheet
import com.tokopedia.play.broadcaster.view.fragment.*
import com.tokopedia.play.broadcaster.view.fragment.beautification.BeautificationSetupFragment
import com.tokopedia.play.broadcaster.view.fragment.beautification.BeautificationTabFragment
import com.tokopedia.play.broadcaster.view.fragment.dialog.InteractiveSetupDialogFragment
import com.tokopedia.play.broadcaster.view.fragment.setup.cover.PlayBroadcastSetupAutoGeneratedCoverFragment
import com.tokopedia.play.broadcaster.view.fragment.setup.cover.PlayBroadcastSetupCoverUploadImageFragment
import com.tokopedia.play.broadcaster.view.fragment.summary.PlayBroadcastSummaryFragment
import com.tokopedia.play.broadcaster.view.fragment.summary.PlayBroadcastPostVideoFragment
import com.tokopedia.play.broadcaster.view.fragment.summary.PlayBroadcastReportFragment
import dagger.Binds
import dagger.Module
import dagger.multibindings.IntoMap

/**
 * Created by jegul on 27/05/20
 */
@Module
abstract class PlayBroadcastFragmentModule {

    @Binds
    abstract fun bindFragmentFactory(fragmentFactory: TkpdFragmentFactory): FragmentFactory

    @Binds
    @IntoMap
    @FragmentKey(PlayBroadcastPreparationFragment::class)
    abstract fun getPlayBroadcastPreparationFragment(fragment: PlayBroadcastPreparationFragment): Fragment

    @Binds
    @IntoMap
    @FragmentKey(PlayBroadcastSummaryFragment::class)
    abstract fun getPlayBroadcastSummaryFragment(fragment: PlayBroadcastSummaryFragment): Fragment

    @Binds
    @IntoMap
    @FragmentKey(PlayBroadcastReportFragment::class)
    abstract fun getPlayBroadcastReportFragment(fragment: PlayBroadcastReportFragment): Fragment

    @Binds
    @IntoMap
    @FragmentKey(PlayBroadcastUserInteractionFragment::class)
    abstract fun getPlayLiveBroadcastFragment(fragment: PlayBroadcastUserInteractionFragment): Fragment

    @Binds
    @IntoMap
    @FragmentKey(PlayPermissionFragment::class)
    abstract fun getPermissionFragment(fragment: PlayPermissionFragment): Fragment

    /**
     * Setup
     */
    @Binds
    @IntoMap
    @FragmentKey(PlayBroadcastSetupCoverBottomSheet::class)
    abstract fun getSetupCoverBottomSheet(fragment: PlayBroadcastSetupCoverBottomSheet): Fragment

    @Binds
    @IntoMap
    @FragmentKey(PlayBroadcastSetupCoverUploadImageFragment::class)
    abstract fun getSetupCoverUploadImageFragment(fragment: PlayBroadcastSetupCoverUploadImageFragment): Fragment

    @Binds
    @IntoMap
    @FragmentKey(PlayBroadcastSetupAutoGeneratedCoverFragment::class)
    abstract fun getSetupAutoGeneratedCoverFragment(fragment: PlayBroadcastSetupAutoGeneratedCoverFragment): Fragment

    /**
     * Revamp
     */
    @Binds
    @IntoMap
    @FragmentKey(ProductSetupFragment::class)
    abstract fun getPlayBroProductSetupFragment(fragment: ProductSetupFragment): Fragment

    @Binds
    @IntoMap
    @FragmentKey(EtalaseListBottomSheet::class)
    abstract fun getPlayBroEtalaseAndCampaignListBottomSheet(fragment: EtalaseListBottomSheet): Fragment

    @Binds
    @IntoMap
    @FragmentKey(ProductChooserBottomSheet::class)
    abstract fun getPlayBroProductChooserBottomSheet(fragment: ProductChooserBottomSheet): Fragment

    @Binds
    @IntoMap
    @FragmentKey(ProductSortBottomSheet::class)
    abstract fun getPlayBroProductSortBottomSheet(fragment: ProductSortBottomSheet): Fragment

    @Binds
    @IntoMap
    @FragmentKey(ProductSummaryBottomSheet::class)
    abstract fun getPlayBroProductSummaryBottomSheet(fragment: ProductSummaryBottomSheet): Fragment

    @Binds
    @IntoMap
    @FragmentKey(PlayBroadcastPostVideoFragment::class)
    abstract fun getPlayBroadcastPostVideoFragment(fragment: PlayBroadcastPostVideoFragment): Fragment

    /**
     * Interactive
     */
    @Binds
    @IntoMap
    @FragmentKey(PlayBroSelectGameBottomSheet::class)
    abstract fun getPlayBroSelectInteractiveBottomSheet(fragment: PlayBroSelectGameBottomSheet): Fragment

    @Binds
    @IntoMap
    @FragmentKey(PlayBroInteractiveBottomSheet::class)
    abstract fun getPlayBroInteractiveBottomSheet(fragment: PlayBroInteractiveBottomSheet) : Fragment

    @Binds
    @IntoMap
    @FragmentKey(InteractiveSetupDialogFragment::class)
    abstract fun getInteractiveSetupDialogFragment(fragment: InteractiveSetupDialogFragment) : Fragment

    @Binds
    @IntoMap
    @FragmentKey(ProductPickerUGCBottomSheet::class)
    abstract fun getPlayPlaceholderBottomSheet(bottomSheet: ProductPickerUGCBottomSheet) : Fragment

    /**
     * Beautification
     */
    @Binds
    @IntoMap
    @FragmentKey(BeautificationSetupFragment::class)
    abstract fun getBeautificationSetupFragment(fragment: BeautificationSetupFragment) : Fragment

    @Binds
    @IntoMap
    @FragmentKey(BeautificationTabFragment::class)
    abstract fun getBeautificationTabFragment(fragment: BeautificationTabFragment) : Fragment
}
