package com.tkpd.atcvariant.view.viewmodel

import com.tokopedia.product.detail.common.buttons_byte_io_tracker.ICartRedirectionButtonsByteIOTrackerViewModel

interface IAtcVariantCartRedirectionButtonsByteIOTrackerSubViewModel : ICartRedirectionButtonsByteIOTrackerViewModel {
    fun registerAtcVariantCartRedirectionButtonsByteIOTrackerSubViewModel(mediator: GetVariantDataMediator)
}
