package com.tokopedia.play.broadcaster.view.bottomsheet

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import androidx.fragment.app.Fragment
import androidx.fragment.app.FragmentManager
import androidx.lifecycle.AbstractSavedStateViewModelFactory
import androidx.lifecycle.SavedStateHandle
import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.lifecycleScope
import com.tokopedia.abstraction.common.dispatcher.CoroutineDispatchers
import com.tokopedia.coachmark.CoachMark2
import com.tokopedia.coachmark.CoachMark2Item
import com.tokopedia.content.common.ui.model.ContentAccountUiModel
import com.tokopedia.kotlin.extensions.view.getScreenHeight
import com.tokopedia.play.broadcaster.R
import com.tokopedia.play.broadcaster.analytic.PlayBroadcastAnalytic
import com.tokopedia.play.broadcaster.data.datastore.PlayBroadcastDataStore
import com.tokopedia.play.broadcaster.databinding.BottomSheetPlayBroSetupCoverBinding
import com.tokopedia.play.broadcaster.setup.cover.PlayBroSetupCoverViewModel
import com.tokopedia.play.broadcaster.setup.product.viewmodel.ViewModelFactoryProvider
import com.tokopedia.play.broadcaster.view.fragment.setup.cover.PlayBroadcastSetupAutoGeneratedCoverFragment
import com.tokopedia.play.broadcaster.view.fragment.setup.cover.PlayBroadcastSetupCoverUploadImageFragment
import com.tokopedia.play_common.util.extension.commit
import com.tokopedia.unifycomponents.BottomSheetUnify
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import javax.inject.Inject

/**
 * Created by fachrizalmrsln on 11/01/23
 */
@Suppress("LateinitUsage")
class PlayBroadcastSetupCoverBottomSheet @Inject constructor(
    private val playBroSetupCoverViewModelFactory: PlayBroSetupCoverViewModel.Factory,
    private val analytic: PlayBroadcastAnalytic,
    private val dispatchers: CoroutineDispatchers,
) : BottomSheetUnify(), ViewModelFactoryProvider {

    private lateinit var coverSetupViewModelProviderFactory: ViewModelProvider.Factory

    private var _binding: BottomSheetPlayBroSetupCoverBinding? = null
    private val binding: BottomSheetPlayBroSetupCoverBinding
        get() = _binding!!

    private var mListener: Listener? = null
    private var mDataSource: DataSource? = null
    private var coachMark: CoachMark2? = null

    private var isShowCoachMark = false

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setupBottomSheet()
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        setupView()
    }

    override fun onAttachFragment(childFragment: Fragment) {
        super.onAttachFragment(childFragment)
        when (childFragment) {
            is PlayBroadcastSetupCoverUploadImageFragment -> {
                childFragment.setupData(listener = mListener)
            }
            is PlayBroadcastSetupAutoGeneratedCoverFragment -> {
                coachMark?.dismissCoachMark()
                childFragment.setupData(
                    listener = mListener,
                    entryPoint = mDataSource?.getEntryPoint().orEmpty(),
                )
            }
        }
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
        mListener = null
        mDataSource = null
        coachMark = null
    }

    private fun setupBottomSheet() {
        _binding = BottomSheetPlayBroSetupCoverBinding.inflate(
            LayoutInflater.from(requireContext())
        )
        clearContentPadding = true
        setChild(binding.root)
    }

    private fun setupView() = with(binding) {
        mListener?.onOpenCoverForm()
        setTitle(getString(R.string.play_bro_setup_cover_title))
        setCloseClickListener {
            mListener?.onCloseCoverForm()
            analytic.clickCloseCoverBottomSheet(mDataSource?.getEntryPoint().orEmpty())
            dismiss()
        }
        binding.root.layoutParams = binding.root.layoutParams.apply {
            height = (getScreenHeight() * SHEET_HEIGHT_PERCENT).toInt()
        }

        selectedContent(TAB_UPLOAD_IMAGE)
        csuSetupCover.setOnCheckedChangeListener { _, isChecked ->
            selectedContent(if (isChecked) TAB_AUTO_GENERATED else TAB_UPLOAD_IMAGE)
        }

        setupCoachMark()

        if (isShowCoachMark) showCoachMark()
    }

    private fun selectedContent(selectedTab: Int) = with(binding) {
        childFragmentManager.commit {
            replace(
                fragmentContainerSetupCover.id,
                if (selectedTab == TAB_AUTO_GENERATED) {
                    analytic.clickCoverTab(getString(R.string.play_bro_cover_setup_choose_template), mDataSource?.getEntryPoint().orEmpty())
                    getSetupCoverChooseTemplateFragment()
                } else {
                    analytic.clickCoverTab(getString(R.string.play_bro_cover_setup_upload_image), mDataSource?.getEntryPoint().orEmpty())
                    getSetupCoverUploadImageFragment()
                },
                null
            )
        }
    }

    fun show(fragmentManager: FragmentManager) {
        if (!isAdded) show(fragmentManager, TAG)
    }

    fun setupListener(listener: Listener) {
        mListener = listener
    }

    fun setupDataSource(dataSource: DataSource) {
        mDataSource = dataSource
    }

    private fun getSetupCoverUploadImageFragment() =
        PlayBroadcastSetupCoverUploadImageFragment.getFragment(
            childFragmentManager,
            requireActivity().classLoader
        )

    private fun getSetupCoverChooseTemplateFragment() =
        PlayBroadcastSetupAutoGeneratedCoverFragment.getFragment(
            childFragmentManager,
            requireActivity().classLoader
        )

    private fun setupCoachMark() {
        coachMark = CoachMark2(requireContext())
        coachMark?.setOnDismissListener {
            analytic.clickCloseTemplateTabCoachMark()
        }
    }

    fun needToShowCoachMark(showCoachMark: Boolean) {
        isShowCoachMark = showCoachMark
    }

    private fun showCoachMark() {
        if (coachMark != null && coachMark?.isShowing == true) return
        viewLifecycleOwner.lifecycleScope.launch(dispatchers.main) {
            delay(COACH_MARK_DELAY)
            coachMark?.showCoachMark(
                arrayListOf(
                    CoachMark2Item(
                        binding.viewContainerCoachMarkAutoGeneratedCover,
                        requireContext().getString(R.string.play_setup_cover_auto_generated_cover_coach_mark_title),
                        requireContext().getString(R.string.play_setup_cover_auto_generated_cover_coach_mark_description),
                        CoachMark2.POSITION_BOTTOM
                    )
                )
            )
        }
    }

    override fun getFactory(): ViewModelProvider.Factory {
        coverSetupViewModelProviderFactory = object : AbstractSavedStateViewModelFactory(
            this,
            arguments
        ) {
            override fun <T : ViewModel?> create(
                key: String,
                modelClass: Class<T>,
                handle: SavedStateHandle
            ): T {
                return mDataSource?.getDataStore()?.let { dataStore ->
                    playBroSetupCoverViewModelFactory.create(
                        channelTitle = mDataSource?.getChannelTitle().orEmpty(),
                        channelId = mDataSource?.getChannelId().orEmpty(),
                        contentAccount = mDataSource?.getContentAccount() ?: ContentAccountUiModel.Empty,
                        dataStore = dataStore,
                        entryPoint = mDataSource?.getEntryPoint().orEmpty(),
                    )
                } as T
            }
        }
        return coverSetupViewModelProviderFactory
    }

    companion object {
        const val TAG = "PlayBroadcastSetupCoverBottomSheet"
        private const val SHEET_HEIGHT_PERCENT = 0.85f
        private const val COACH_MARK_DELAY = 2000L
        const val TAB_UPLOAD_IMAGE = 1
        const val TAB_AUTO_GENERATED = 2

        fun getFragment(
            fragmentManager: FragmentManager,
            classLoader: ClassLoader,
        ): PlayBroadcastSetupCoverBottomSheet? {
            val oldInstance =
                fragmentManager.findFragmentByTag(TAG) as? PlayBroadcastSetupCoverBottomSheet
            return oldInstance ?: fragmentManager.fragmentFactory.instantiate(
                classLoader,
                PlayBroadcastSetupCoverBottomSheet::class.java.name
            ) as? PlayBroadcastSetupCoverBottomSheet
        }
    }

    interface Listener {
        fun onOpenCoverForm() {}
        fun onCloseCoverForm() {}
        fun onClickSelectCoverOnCoverForm() {}
        fun dismissSetupCover(source: Int)
        fun setupCoverProductClicked() {}
        fun onUploadCoverSuccess() {}
        fun onDeleteAutoGeneratedCover() {}
    }

    interface DataSource {
        fun getEntryPoint(): String
        fun getContentAccount(): ContentAccountUiModel
        fun getChannelId(): String
        fun getChannelTitle(): String
        fun getDataStore(): PlayBroadcastDataStore
    }

}
