package com.tokopedia.shop.flash_sale.domain.entity

data class Campaign(
    val bitmaskIsSet: Boolean,
    val campaignId: Long,
    val campaignName: String,
    val campaignTypeId: Int,
    val campaignTypeName: String,
    val coverImg: String,
    val endDate: Long,
    val etalasePrefix: String,
    val finishedWidgetTime: Long,
    val finishedWidgetTimeInMins: Int,
    val isCampaignRelation: Boolean,
    val isCampaignRuleSubmit: Boolean,
    val isCancellable: Boolean,
    val isShareable: Boolean,
    val isUniqueBuyer: Boolean,
    val maxProductSubmission: Int,
    val notifyMeCount: Int,
    val paymentType: Int,
    val redirectUrl: String,
    val redirectUrlApp: String,
    val reviewEndDate: Long,
    val reviewStartDate: Long,
    val startDate: Long,
    val statusDetail: String,
    val statusId: Int,
    val statusText: String,
    val submissionEndDate: Long,
    val submissionStartDate: Long,
    val thematicParticipation: Boolean,
    val useUpcomingWidget: Boolean
)
