package com.tokopedia.statistic.analytics

/**
 * Created By @ilhamsuaib on 22/07/20
 */

object TrackingConstant {

    //key
    const val EVENT = "event"
    const val EVENT_CATEGORY = "eventCategory"
    const val EVENT_ACTION = "eventAction"
    const val EVENT_LABEL = "eventLabel"
    const val ECOMMERCE = "ecommerce"
    const val ID = "id"
    const val NAME = "name"
    const val CREATIVE = "creative"
    const val CREATIVE_URL = "creative_url"
    const val CATEGORY = "category"
    const val PROMO_ID = "promo_id"
    const val PROMO_CODE = "promo_code"
    const val POSITION = "position"
    const val PROMOTIONS = "promotions"
    const val USER_ID = "userId"
    const val BUSINESS_UNIT = "businessUnit"
    const val CURRENT_SITE = "currentSite"

    //event
    const val VIEW_SELLER_WIDGET = "viewSellerWidget"
    const val CLICK_SHOP_INSIGHT = "clickShopInsight"
    const val PROMO_VIEW = "promoView"
    const val PROMO_CLICK = "promoClick"
    const val VIEW_STATISTIC_IRIS = "viewStatistikIris"
    const val VIEW_HOMEPAGE_IRIS = "viewHomepageIris"
    const val VIEW_PG_IRIS = "viewPGIris"
    const val CLICK_PG = "clickPG"
    const val CLICK_STATISTIC = "clickStatistik"
    const val VIEW_PRODUCT_INSIGHT_IRIS = "viewProductInsightIris"
    const val CLICK_PRODUCT_INSIGHT = "clickProductInsight"
    const val CLICK_HOMEPAGE = "clickHomepage"

    //category
    const val SHOP_INSIGHT = "shop insight"
    const val SELLER_APP = "seller app"
    const val SELLER_APP_STATISTIC = "seller app - statistik"
    const val SELLER_APP_SHOP_INSIGHT = "seller app - wawasan toko"
    const val SELLER_APP_BUYER_INSIGHT = "seller app - wawasan pembeli"
    const val SELLER_APP_PRODUCT_INSIGHT = "seller app - wawasan produk"
    const val STATISTIC_FIREWALL = "statistics firewall"

    //action
    const val CLICK_WIDGET_CARD = "click widget card"
    const val CLICK_WIDGET_LINE_GRAPH = "click widget trend line"
    const val CLICK_WIDGET_DESCRIPTION = "click widget description"
    const val CLICK_WIDGET_PROGRESS_BAR = "click widget progress bar"
    const val CLICK_WIDGET_POST = "click widget post"
    const val CLICK_WIDGET_BANNER = "click widget banner"
    const val CLICK_DATE_FILTER = "click date filter"
    const val CLICK_SELECT_ON_DATE_FILTER = "click select on date filter"
    const val CLICK_INFO_ICON = "click info icon"
    const val CLICK_MENU_TAB = "click - tab menu"
    const val CLICK_MENU_CALENDAR = "click- %s - calendar"
    const val CLICK_MENU_3_DOT = "click - 3 dot"
    const val CLICK_MENU_MENU_LAINNYA = "click - %s - menu lainnya"
    const val CLICK_TABLE_WIDGET_FILTER = "click table widget - filter"
    const val CLICK_WIDGET_BAR_CHART = "click widget bar chart"
    const val CLICK_WIDGET_PIE_CHART = "click widget pie chart"
    const val CLICK_PAYWALL_CTA = "click paywall date filter - upgrade toko"
    const val CLICK_DISMISS_DATE_FILTER = "click paywall filter - close"
    const val CLICK_TICKER_CTA = "click pelajari selengkapnya"
    const val CLICK_TRAFFIC_COACH_MARK_CTA = "click onboarding popup - complete"
    const val CLICK_TOP_ADS_CROSS_SELLING = "click topads cross selling"
    const val CLICK_TABLE_WIDGET_SORT = "click widget accordion table - sort"
    const val IMPRESSION_WIDGET_CARD = "impression widget card"
    const val IMPRESSION_WIDGET_LINE_GRAPH = "impression widget trend line"
    const val IMPRESSION_WIDGET_DESCRIPTION = "impression widget description"
    const val IMPRESSION_WIDGET_PROGRESS_BAR = "impression widget progress bar"
    const val IMPRESSION_WIDGET_POST = "impression widget post"
    const val IMPRESSION_WIDGET_BANNER = "impression widget banner"
    const val IMPRESSION_WIDGET_TABLE_FILTER = "impression table widget - filter"
    const val IMPRESSION_WIDGET_SIMPLE_TABLE = "impression widget simple table"
    const val IMPRESSION_WIDGET_PIE_CHART = "impression widget pie chart"
    const val IMPRESSION_WIDGET_BAR_CHART = "impression widget bar chart"
    const val IMPRESSION_MENU_TAB = "impression - tab menu"
    const val IMPRESSION_CALENDAR = "impression date filter"
    const val IMPRESSION_3_DOT = "impression - 3 dot"
    const val IMPRESSION_MENU_LAINNYA = "impression - %s - menu lainnya"
    const val IMPRESSION_PAYWALL_DATE_FILTER = "impression paywall date filter"
    const val IMPRESSION_EXCLUSIVE_FEATURE = "impression exclusive identifier - date filter"
    const val IMPRESSION_WIDGET_MULTI_TREND_LINE = "impression widget multi trend line"
    const val IMPRESSION_LEARN_MORE = "impression pelajari selengkapnya"
    const val IMPRESSION_TRAFFIC_COACH_MARK = "impression onboarding popup"
    const val IMPRESSION_TOP_ADS_CROSS_SELLING = "impression topads cross selling"
    const val IMPRESSION_EXPLANATION_TOOLTIP = "impression explanation tooltip"
    const val SLIDE_TABLE_WIDGET = "slide table widget"
    const val SEE_MORE = "see more"

    //other
    const val SELLER_WIDGET = "/seller widget"
    const val NONE = "none"
    const val EMPTY = "empty"
    const val NOT_EMPTY = "not empty"
    const val SHOP_OS = "OS"
    const val SHOP_PM = "PM"
    const val SHOP_RM = "RM"
    const val WIDGET_SIMPLE_TABLE = "widget simple table"
    const val WIDGET_CARD = "widget card"
    const val WIDGET_TREND_LINE = "widget trend line"
    const val WIDGET_PIE_CHART = "widget pie chart"
    const val WIDGET_BAR_CHART = "widget bar chart"
    const val PHYSICAL_GOODS = "physicalgoods"
    const val TOKOPEDIASELLER = "tokopediaseller"
}