package com.tokopedia.salam.umrah.common.analytics

val UMRAH_CLICK_EVENT = "clickUmroh"
val UMRAH_CLICK_CATEGORY_ORDER_DETAIL = "order detail page umroh"
val UMRAH_CLICK_ACTION_INVOICE = "click invoice"
val UMRAH_CLICK_ACTION_ORDER_DETAIL = "click lihat detail"
val UMRAH_CLICK_ACTION_ORDER_DETAIL_WIDGET_UMROH_SAYA = "click lihat detail widget umroh saya"
val UMRAH_CLICK_ACTION_ORDER_DETAIL_PDP = "click lihat detail pdp"
val UMRAH_CLICK_ACTION_ORDER_DETAIL_E_VOUCHER = "click e voucher"
val UMRAH_CLICK_ACTION_ORDER_DETAIL_KEBIJAKAN_PEMBATALAN = "click kebijakan pembatalan"
val UMRAH_CLICK_ACTION_ORDER_DETAIL_BATALKAN_PESANAN = "click batalkan pesanan"
val UMRAH_CLICK_ACTION_ORDER_DETAIL_BANTUAN = "click bantuan"
val UMRAH_CLICK_ACTION_ORDER_DETAIL_BACK = "click back"

val UMRAH_EVENT_CLICK_UMROH = "clickUmroh"
val UMRAH_EVENT_PROMO_CLICK = "promoClick"
val UMRAH_EVENT_PROMO_VIEW = "promoView"
val UMRAH_EVENT_PRODUCT_VIEW = "productView"
val UMRAH_EVENT_PRODUCT_CLICK = "productClick"


val UMRAH_CATEGORY_HOME_PAGE = "homepage umroh"

val UMRAH_CLICK_SEARCH_PACKET_UMRAH = "click cari paket umroh"
val UMRAH_IMPRESSION_WIDGET_MY_UMRAH = "impression widget umroh saya"
val UMRAH_CLICK_WIDGET_MY_UMRAH = "click widget umroh saya"
val UMRAH_IMPRESSION_CATEGORY = "impression kategori"
val UMRAH_CLICK_CATEGORY = "click kategori"
val UMRAH_IMPRESSION_DYNAMIC_CONTENT = "impression dynamic content"
val UMRAH_CLICK_DYNAMIC_CONTENT= "click dynamic content"
val UMRAH_IMPRESSION_DREAM_FUND= "impression dana impian umroh"
val UMRAH_CLICK_DREAM_FUND= "click dana impian umroh"


val UMRAH_CLICK_CHECKOUT_CATEGORY = "checkout page umroh"
val UMRAH_CLICK_CHECKOUT_LIST_DETAIL_PILGRIMS = "click lihat detail daftar jamaah"
val UMRAH_CLICK_CHECKOUT_CUSTOMER_CONTACT = "click kontak pemesan"
val UMRAH_CLICK_CHECKOUT_LIST_PILGRIMS = "click lihat daftar jamaah"
val UMRAH_CLICK_CHECKOUT_PAYMENT_TYPE = "click pilih tipe pembayaran"
val UMRAH_CLICK_CHECKOUT_INSTALLMENT_TYPE = "click pilih tipe cicilan"
val UMRAH_CLICK_CHECKOUT_CHOOSE_PAYMENT = "click pilih pembayaran"
val UMRAH_CLICK_BACK = "click back"


val ECOMMERCE_LABEL = "ecommerce"
val PRODUCTS_LABEL = "products"
val PROMOTIONS_LABEL = "promotions"

val ID = "id"
val NAME = "name"
val CREATIVE = "creative"
val POSITION = "position"
val WIDGET_MY_UMRAH = "widget umroh saya"
val KATEGORI = "kategori"
val DYNAMIC_CONTENT = "dynamic content"
val CLICK = "click"
val ACTION_FIELD = "actionField"
val CURRENCY_CODE = "currencyCode"
val CURRENCY = "IDR"
val IMPRESSION = "impression"
val PRICE = "price"
val CATEGORY = "category"
val PRODUCTS = "products"
val LIST = "list"
val DEPART_MONTH = "bulan keberangkatan:"
val PRICE_TRACKING = "_harga:"
val DEPART_CITY = "_kota keberangkatan:"
val DREAM_FUND = "dana impian"
val POSITION_DEFAULT = 1
val CHECKOUT = "checkout"
val STEP = "step"
val OPTION = "option"
val QUANTITY = "quantity"


