package com.tokopedia.salam.umrah.common.analytics

const val UMRAH_CLICK_EVENT = "clickUmroh"
const val UMRAH_CLICK_CATEGORY_ORDER_DETAIL = "order detail page umroh"
const val UMRAH_CLICK_ACTION_INVOICE = "click invoice"
const val UMRAH_CLICK_ACTION_ORDER_DETAIL = "click lihat detail"
const val UMRAH_CLICK_ACTION_ORDER_DETAIL_WIDGET_UMROH_SAYA = "click lihat detail widget umroh saya"
const val UMRAH_CLICK_ACTION_ORDER_DETAIL_PDP = "click lihat detail pdp"
const val UMRAH_CLICK_ACTION_ORDER_DETAIL_E_VOUCHER = "click e voucher"
const val UMRAH_CLICK_ACTION_ORDER_DETAIL_KEBIJAKAN_PEMBATALAN = "click kebijakan pembatalan"
const val UMRAH_CLICK_ACTION_ORDER_DETAIL_BATALKAN_PESANAN = "click batalkan pesanan"
const val UMRAH_CLICK_ACTION_ORDER_DETAIL_BANTUAN = "click bantuan"
const val UMRAH_CLICK_ACTION_ORDER_DETAIL_BACK = "click back"

const val UMRAH_EVENT_CLICK_UMROH = "clickUmroh"
const val UMRAH_EVENT_PROMO_CLICK = "promoClick"
const val UMRAH_EVENT_PROMO_VIEW = "promoView"
const val UMRAH_EVENT_PRODUCT_VIEW = "productView"
const val UMRAH_EVENT_PRODUCT_CLICK = "productClick"


const val UMRAH_CATEGORY_HOME_PAGE = "homepage umroh"

const val UMRAH_CLICK_SEARCH_PACKET_UMRAH = "click cari paket umroh"
const val UMRAH_IMPRESSION_WIDGET_MY_UMRAH = "impression widget umroh saya"
const val UMRAH_CLICK_WIDGET_MY_UMRAH = "click widget umroh saya"
const val UMRAH_IMPRESSION_CATEGORY = "impression kategori"
const val UMRAH_CLICK_CATEGORY = "click kategori"
const val UMRAH_IMPRESSION_DYNAMIC_CONTENT = "impression dynamic content"
const val UMRAH_CLICK_DYNAMIC_CONTENT = "click dynamic content"
const val UMRAH_IMPRESSION_DREAM_FUND = "impression dana impian umroh"
const val UMRAH_CLICK_DREAM_FUND = "click dana impian umroh"
const val UMRAH_IMPRESSION_BANNER = "impression slider banner"
const val UMRAH_CLICK_BANNER = "click slider banner"


const val UMRAH_CLICK_CHECKOUT_CATEGORY = "checkout page umroh"
const val UMRAH_CLICK_CHECKOUT_LIST_DETAIL_PILGRIMS = "click lihat detail daftar jamaah"
const val UMRAH_CLICK_CHECKOUT_CUSTOMER_CONTACT = "click kontak pemesan"
const val UMRAH_CLICK_CHECKOUT_LIST_PILGRIMS = "click daftar jamaah"
const val UMRAH_CLICK_CHECKOUT_PAYMENT_TYPE = "click pilih tipe pembayaran"
const val UMRAH_CLICK_CHECKOUT_INSTALLMENT_TYPE = "click pilih tipe cicilan"
const val UMRAH_CLICK_CHECKOUT_CHOOSE_PAYMENT = "click pilih pembayaran"
const val UMRAH_CLICK_BACK = "click back"

const val ECOMMERCE_LABEL = "ecommerce"
const val PRODUCTS_LABEL = "products"
const val PROMOTIONS_LABEL = "promotions"

const val CREATIVE = "creative"
const val WIDGET_MY_UMRAH = "widget umroh saya"
const val KATEGORI = "kategori"
const val DYNAMIC_CONTENT = "dynamic content"
const val CURRENCY = "IDR"
const val IMPRESSION = "impression"
const val DEPART_MONTH = "bulan keberangkatan:"
const val PRICE_TRACKING = "_harga:"
const val DEPART_CITY = "_kota keberangkatan:"
const val DREAM_FUND = "dana impian"
const val POSITION_DEFAULT = 1
const val CHECKOUT = "checkout"
const val STEP = "step"
const val OPTION = "option"


const val EMPTY = ""
const val PRODUCT_VIEW = "productView"
const val SEARCH_RESULT_PAGE_UMROH = "search result page umroh"
const val IMPRESSION_PRODUCT = "impression product"
const val ECOMMERCE = "ecommerce"
const val CURRENCY_CODE = "currencyCode"
const val IDR = "IDR"
const val IMPRESSIONS = "impressions"
const val NAME = "name"
const val ID = "id"
const val PRICE = "price"
const val CATEGORY = "category"
const val LIST = "list"
const val POSITION = "position"
const val DIMENSION110 = "dimension110"
const val PRODUCT_CLICK = "productClick"
const val CLICK_PRODUCT = "click product"
const val CLICK = "click"
const val ACTION_FIELD = "actionField"
const val PRODUCTS = "products"
const val CLICK_UMROH = "clickUmroh"
const val CLICK_SORT = "click sort"
const val CLICK_FILTER = "click filter"
const val CLICK_BACK_CONST = "click back"
const val CATEGORY_RESULT_PAGE_UMROH = "category result page umroh"
const val PRODUCT_DETAIL_PAGE_UMROH = "product detail page umroh"
const val CLICK_FOTO_PRODUK = "click foto produk"
const val CLICK_PLIH_KAMAR = "click plih kamar"
const val CLICK_BELI = "click beli"
const val SCROLL_HOTEL = "scroll hotel"
const val CLICK_FOTO_HOTEL = "click foto hotel"
const val SCROLL_PENERBANGAN = "scroll penerbangan"
const val CLICK_BACA_ITINERARY_SELENGKAPNYA = "click baca itinerary selengkapnya"
const val CLICK_LIHAT_SEMUA_FASILITAS = "click lihat semua fasilitas"
const val SCROLL_FAQ_CONST = "scroll faq"
const val CLICK_LIHAT_SEMUA_FAQ = "click lihat semua faq"
const val CLICK_FAQ_CONST = "click faq"
const val ADD_TO_CART = "addToCart"
const val CLICK_LANJUTKAN_BELI_PAKET = "click lanjutkan beli paket"
const val ADD = "add"
const val VARIANT = "variant"
const val QUANTITY = "quantity"
const val SHOP_ID = "shop_id"
const val SHOP_NAME = "shop_name"
const val CATEGORY_ID = "category_id"
const val SORT = "sort"
const val FILTER = "filter"
const val BULAN_KEBERANGKATAN = "bulan keberangkatan"
const val KOTA_KEBERANGKATAN = "kota keberangkatan"
const val DURASI_PERJALANAN = "durasi perjalanan"
const val HARGA_PAKET = "harga paket"
const val SLIDER_BANNER = "slider banner"

const val MY_UMRAH_AND_DREAM_FUND_CREATIVE = "https://images.tokopedia.net/assets-tokopedia-lite/v2/firdaus/kratos/a61bc722.png"

const val UMRAH_TRAVEL_PAGE_CATEGORY = "travel page umroh"
const val UMRAH_TRAVEL_PAGE_GALERY_CATEGORY = "travel galeri page umroh"
const val UMRAH_TRAVEL_PAGE_INFO_CATEGORY = "travel info page umroh"
const val UMRAH_TRAVEL_CLICK_INFO = "click info"
const val UMRAH_TRAVEL_CLICK_MORE = "click selengkapnya"
const val UMRAH_TRAVEL_CLICK_PACKET = "click paket umroh"
const val UMRAH_TRAVEL_CLICK_NUMBER_REGISTRATION = "click number registration"
const val UMRAH_TRAVEL_CLICK_HUBUNGI = "click hubungi travel"
const val UMRAH_TRAVEL_CLICK_GALERI = "click galeri"
const val UMRAH_TRAVEL_CLICK_CLOSE_VERIFICATION = "click tutup verifikasi"
const val UMRAH_TRAVEL_CLICK_ACTION_THREE_DOTS = "click three dot"
const val UMRAH_TRAVEL_THREE_DOT_HELP = "bantuan"
const val UMRAH_TRAVEL_THREE_DOT_SALAM = "salam"
const val UMRAH_TRAVEL_THREE_DOT_SHARE = "share"

const val UMRAH_TRAVEL_PACKET_UMROH = "paket umroh"
const val UMRAH_IMPRESSION_CONTENT = "impression content"
const val UMRAH_CLICK_CONTENT = "click content"
const val UMRAH_IMPRESSION_TRAVEL_AGENT =  "impression travel agent"
const val UMRAH_CLICK_TRAVEL_AGENT =  "click travel agent"
const val UMRAH_TRAVEL_AGENT = "travel agent"

const val UMRAH_TRAVEL_LIST_UMROH = "travel list page umroh"
const val UMRAH_IMPRESSION_TRAVEL_LIST = "impression travel agent"
const val UMRAH_CLICK_TRAVEL_LIST = "click travel agent"

