package com.tokopedia.flight.common.constant_kotlin

/**
 * @author by furqan on 07/06/2021
 */
enum class FlightErrorConstant(val value: Int) {
    INVALID_JSON(1),
    INVALID_USER_ID(2),
    DUPLICATE_IDEMPOTENCY_KEY(3),
    GET_RESULT(4),
    CONNECT_REDIS(5),
    MISSING_REQUIRED_PARAM(6),
    INVALID_DATE(7),
    ADD_TO_CART(8),
    SAVE_CART(9),
    METHOD_NOT_ALLOWED(10),
    FLIGHT_SOLD_OUT(56),
    FLIGHT_EXPIRED(83),
    FLIGHT_ROUTE_NOT_FOUND(81),
    FAILED_ADD_FACILITY(108),
    ERROR_PROMO_CODE(28),
    FLIGHT_DUPLICATE_BOOKING(86),
    FLIGHT_STILL_IN_PROCESS(44),
    FLIGHT_INVALID_USER(22),
    FLIGHT_DUPLICATE_USER_NAME(62),
    FLIGHT_ERROR_GET_CART_EXCEED_MAX_RETRY(1335),
    FLIGHT_ERROR_VERIFY_EXCEED_MAX_RETRY(1337),
    FLIGHT_ERROR_ON_CHECKOUT_GENERAL(1339)
}