package com.tokopedia.tokopedianow.common.analytics

object TokoNowCommonAnalyticConstants {

    object EVENT{
        const val EVENT_VIEW_CONTENT_IRIS = "viewContentIris"
        const val EVENT_CLICK_CONTENT = "clickContent"
        const val EVENT_VIEW_TOKONOW_IRIS = "viewTokoNowIris"
        const val EVENT_CLICK_TOKONOW = "clickTokoNow"
        const val EVENT_CLICK_PG = "clickPG"
        const val EVENT_SELECT_CONTENT = "select_content"
        const val EVENT_VIEW_ITEM = "view_item"
        const val EVENT_VIEW_ITEM_LIST = "view_item_list"
        const val EVENT_PRODUCT_VIEW = "productView"
        const val EVENT_PRODUCT_CLICK = "productClick"
        const val EVENT_ATC = "addToCart"
        const val EVENT_ADD_TO_CART = "add_to_cart"
        const val EVENT_REMOVE_FROM_CART = "remove_from_cart"
        const val EVENT_OPEN_SCREEN = "openScreen"
        const val EVENT_VIEW_PG_IRIS = "viewPGIris"
        const val EVENT_VIEW_GROWTH_IRIS = "viewGrowthIris"
        const val EVENT_CLICK_GROWTH = "clickGrowth"
        const val EVENT_CLICK_COMMUNICATION = "clickCommunication"
        const val EVENT_CAMPAIGN_CODE = "campaignCode"
        const val EVENT_WAREHOUSE_ID = "warehouseId"
        const val EVENT_PROMO_VIEW = "promoView"
        const val EVENT_PROMO_CLICK = "promoClick"
        const val EVENT_VIEW_IRIS = "viewIris"
        const val EVENT_CLICK = "click"
    }

    object CATEGORY{
        const val EVENT_CATEGORY_TOP_NAV = "tokonow - top nav"
        const val EVENT_CATEGORY_TOKOPEDIA_NOW = "tokopedia now"
        const val EVENT_CATEGORY_TOP_NAV_TOKOPEDIA_NOW = "top nav - tokopedia now"
        const val EVENT_CATEGORY_TOKONOW_HOMEPAGE = "tokonow - homepage"
    }

    object KEY {
        const val KEY_AFFINITY_LABEL = "affinityLabel"
        const val KEY_CURRENT_SITE = "currentSite"
        const val KEY_BUSINESS_UNIT = "businessUnit"
        const val KEY_PROMOTIONS = "promotions"
        const val KEY_CREATIVE_NAME = "creative_name"
        const val KEY_CREATIVE_SLOT = "creative_slot"
        const val KEY_DIMENSION_104 = "dimension104"
        const val KEY_DIMENSION_38 = "dimension38"
        const val KEY_DIMENSION_79 = "dimension79"
        const val KEY_DIMENSION_82 = "dimension82"
        const val KEY_DIMENSION_49 = "dimension49"
        const val KEY_DIMENSION_40 = "dimension40"
        const val KEY_DIMENSION_45 = "dimension45"
        const val KEY_DIMENSION_90 = "dimension90"
        const val KEY_QUANTITY = "quantity"
        const val KEY_SHOP_ID = "shop_id"
        const val KEY_SHOP_NAME = "shop_name"
        const val KEY_SHOP_TYPE = "shop_type"
        const val KEY_USER_ID = "userId"
        const val KEY_PRODUCT_ID = "productId"
        const val KEY_CATEGORY_ID = "category_id"
        const val KEY_CHANNEL_ID = "channelId"
        const val KEY_CAMPAIGN_CODE = "campaignCode"
        const val KEY_PAGE_SOURCE = "pageSource"
        const val KEY_INDEX = "index"
        const val KEY_ITEMS = "items"
        const val KEY_ITEM_ID = "item_id"
        const val KEY_ITEM_NAME = "item_name"
        const val KEY_ITEM_LIST = "item_list"
        const val KEY_ITEM_VARIANT = "item_variant"
        const val KEY_ITEM_BRAND = "item_brand"
        const val KEY_ITEM_CATEGORY = "item_category"
        const val KEY_PRICE = "price"
        const val KEY_IS_LOGGED_IN_STATUS = "isLoggedInStatus"
        const val KEY_WAREHOUSE_ID = "warehouseId"
        const val KEY_TRACKER_ID = "trackerId"
    }

    object VALUE {
        const val CURRENT_SITE_TOKOPEDIA_MARKET_PLACE = "tokopediamarketplace"
        const val BUSINESS_UNIT_TOKOPEDIA_MARKET_PLACE = "tokopediamarketplace"
        const val BUSINESS_UNIT_PHYSICAL_GOODS = "Physical Goods"
        const val BUSINESS_UNIT_SHARING_EXPERIENCE = "sharingexperience"
        const val BUSINESS_UNIT_PLAY = "play"
        const val SCREEN_NAME_TOKONOW_OOC = "tokonow ooc - "
        const val PAGE_NAME_TOKOPEDIA_NOW = "tokopedia now"
        const val DEFAULT_NULL_VALUE = "null"
        const val DEFAULT_CATEGORY_ID = "0"
        const val DEFAULT_EMPTY_VALUE = ""
    }

    object ACTION{
        const val EVENT_ACTION_CLICK_CHANGE_ADDRESS_ON_OOC = "click change address on ooc"
        const val EVENT_ACTION_CLICK_SHOP_ON_TOKOPEDIA = "click belanja di tokopedia on ooc"
        const val EVENT_ACTION_CLICK_SHARE_WIDGET_BUTTON = "click - share button"
        const val EVENT_ACTION_CLICK_ACCESS_PHOTO_MEDIA_FILES = "click - access photo media and files"
        const val EVENT_ACTION_CLICK_CHANNEL_SHARE_BOTTOM_SHEET_SCREENSHOT = "click - channel share bottom sheet - screenshot"
        const val EVENT_ACTION_CLICK_CLOSE_SCREENSHOT_SHARE_BOTTOM_SHEET = "click - close screenshot share bottom sheet"
        const val EVENT_ACTION_IMPRESSION_CHANNEL_SHARE_BOTTOM_SHEET_SCREENSHOT = "view - screenshot share bottom sheet"
        const val EVENT_ACTION_IMPRESSION_SHARING_CHANNEL = "view on sharing channel"
        const val EVENT_ACTION_CLICK_SHARING_CHANNEL = "click - sharing channel"
        const val EVENT_ACTION_CLICK_CLOSE_SHARE_BOTTOM_SHEET  = "click - close share bottom sheet"
    }
}
