package com.tokopedia.shop.flashsale.domain.entity.enums

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

const val CAMPAIGN_STATUS_ID_DRAFT = 2
const val CAMPAIGN_STATUS_ID_IN_SUBMISSION = 4
const val CAMPAIGN_STATUS_ID_IN_REVIEW = 5
const val CAMPAIGN_STATUS_ID_READY = 6
const val CAMPAIGN_STATUS_ID_ONGOING = 7
const val CAMPAIGN_STATUS_ID_UPCOMING = 14


const val CAMPAIGN_STATUS_ID_FINISHED = 8
const val CAMPAIGN_STATUS_ID_ONGOING_CANCELLATION = 13
const val CAMPAIGN_STATUS_ID_CANCELLED = 15

@Parcelize
enum class CampaignStatus(val id: Int) : Parcelable {
    DRAFT(CAMPAIGN_STATUS_ID_DRAFT),

    IN_SUBMISSION(CAMPAIGN_STATUS_ID_IN_SUBMISSION),
    IN_REVIEW(CAMPAIGN_STATUS_ID_IN_REVIEW),
    READY(CAMPAIGN_STATUS_ID_READY),
    UPCOMING(CAMPAIGN_STATUS_ID_UPCOMING),
    ONGOING(CAMPAIGN_STATUS_ID_ONGOING),

    FINISHED(CAMPAIGN_STATUS_ID_FINISHED),
    ONGOING_CANCELLATION(CAMPAIGN_STATUS_ID_ONGOING_CANCELLATION),
    CANCELLED(CAMPAIGN_STATUS_ID_CANCELLED)
}