package com.tokopedia.shop.score.common.analytics

object ShopScoreTrackingConstant {
    const val SHOP_TYPE_RM = "RM"
    const val SHOP_TYPE_PM = "PM"
    const val SHOP_TYPE_OS = "OS"

    const val PHYSICAL_GOODS = "physical goods"
    const val TOKOPEDIA_SELLER = "tokopediaseller"
    const val BUSSINESS_UNIT = "businessUnit"
    const val CURRENT_SITE = "currentSite"
    const val USER_ID = "userId"

    const val COMMUNICATION_PERIOD_OLD_SHOP_SCORE = "communication period - old shop score page"
    const val TRANSITION_PERIOD_SHOP_SCORE = "transition period - shop score page"
    const val SHOP_SCORE_PAGE = "shop score page"
    const val TRANSITION_PERIOD_PENALTY_PAGE = "transition period - penalty page"
    const val CLICK_SHOP_SCORE = "clickShopScore"
    const val CLICK_SEE_DETAIL_PENALTY = "click - lihat detail penalti disini"
    const val CLICK_CHECK_PENALTY = "click - cek penalti"
    const val CLICK_COMPLETE_INFO = "click info lengkap"
    const val CLICK_YOUR_SHOP_GET_PM = "click - tokomu dapat power merchant"
    const val CLICK_SEE_ALL_BENEFIT = "click - lihat semua keuntungannya"
    const val CLICK_MERCHANT_TOOLS = "click - merchant tools"
    const val CLICK_WATCH_VIDEO = "click - tonton video"
    const val CLICK_LEARN_SHOP_PERFORMANCE = "click - pelajari performa toko"
    const val NEW_SELLER = "new seller -"
    const val MERCHANT_VOUCHER = "merchant voucher"
    const val FREE_SHIPPING = "bebas ongkir"
    const val BROADCAST_CHAT = "broadcast chat"

    const val OLD_PERFORMA_TOKO_PAGE = "old performa toko page"
    const val CLICK_LEARN_MORE = "click - pelajari selengkapnya"
    const val CLICK_CONTACT_HELP_CENTER = "click - pusat bantuan"
    const val CLICK_HELP_CENTER = "click - pusat bantuan"
    const val VIEW_SHOP_SCORE_IRIS = "viewShopScoreIris"
    const val IMPRESSION_LEARN_MORE = "impression - pelajari selengkapnya"
    const val IMPRESSION_SEE_PENALTY_DETAIL = "impression - lihat detail penalti disini"
    const val IMPRESSION_CHECK_PENALTY = "impression - cek penalti"
    const val IMPRESSION_COMPLETE_INFO = "impression - info lengkap"
    const val IMPRESSION_GET_PM = "impression - tokomu dapat power merchant"
    const val IMPRESSION_SEE_ALL_BENEFIT = "impression - lihat semua keuntungannya"
    const val IMPRESSION_MERCHANT_TOOLS = "impression - merchant tools"
    const val IMPRESSION_CALL_HELP_CENTER = "impression - pusat bantuan"
    const val IMPRESSION_WATCH_VIDEO = "impression - tonton video"
    const val IMPRESSION_LEARN_SHOP_PERFORMANCE = "impression - pelajari performa toko"
    const val IMPRESSION_HELP_CENTER = "impression - pusat bantuan"

    const val FREE_SHIPPING_IDENTIFIER = "bebas_ongkir_recommendation"
    const val VOUCHER_RECOMMENDATION_IDENTIFIER = "voucher_recommendation"
    const val BROADCAST_CHAT_IDENTIFIER = "broadcast_chat_recommendation"

}