package com.tokopedia.url

/**
 * @author okasurya on 4/9/19.
 */

internal val live = Url(
        TYPE = Env.LIVE,
        WS = "https://ws.tokopedia.com/",
        API = "https://api.tokopedia.com/",
        WEB = "https://www.tokopedia.com/",
        MOBILEWEB = "https://m.tokopedia.com/",
        ACE = "https://ace.tokopedia.com/",
        TOME = "https://tome.tokopedia.com/",
        TA = "https://ta.tokopedia.com/",
        MOJITO = "https://mojito.tokopedia.com/",
        HADES = "https://hades.tokopedia.com/",
        MERLIN = "https://merlin.tokopedia.com/",
        ACCOUNTS = "https://accounts.tokopedia.com/",
        INBOX = "https://inbox.tokopedia.com/",
        CHAT = "https://chat.tokopedia.com",
        WS_CHAT = "wss://chat.tokopedia.com",
        GROUPCHAT = "https://groupchat.tokopedia.com",
        WS_GROUPCHAT = "wss://groupchat.tokopedia.com",
        JS = "https://js.tokopedia.com/",
        KERO = "https://kero.tokopedia.com/",
        JAHE = "https://jahe.tokopedia.com/",
        GOLDMERCHANT = "https://goldmerchant.tokopedia.com/",
        PULSA = "https://pulsa.tokopedia.com/",
        PULSA_API = "https://pulsa-api.tokopedia.com/",
        PAY_ID = "https://pay.tokopedia.id/",
        PAY = "https://pay.tokopedia.com",
        PAYMENT = "https://payment.tokopedia.com/",
        GQL = "https://gql.tokopedia.com/",
        GW = "https://gw.tokopedia.com/",
        GALADRIEL = "https://galadriel.tokopedia.com/",
        FS = "https://fs.tokopedia.net/",
        TOKOCASH = "https://www.tokocash.com/",
        OMSCART = "https://omscart.tokopedia.com/",
        BOOKING = "https://booking.tokopedia.com/",
        TIKET = "https://tiket.tokopedia.com/",
        IMT = "https://imt.tokopedia.com/",
        LAKU6 = "https://www.laku6.com",
        SELLER = "https://seller.tokopedia.com/",
        PLAY = "https://chat.tokopedia.com",
        WS_PLAY = "wss://groupchat.tokopedia.com",
        HUB = "https://hub.tokopedia.com/",
        PCIDSS_CREDIT_CARD = "https://pay.tokopedia.id/",
        GOJEK_OTP = "https://accounts.gojek.com/",
        GOPAY_PIN = "https://merchants-gws-app.gopayapi.com/",
        SSE = "https://sse.tokopedia.com/",
        ONE_TRUST = "https://app-apac.onetrust.com/",
        TOKOCHAT = "https://chat.tokopedia.com/tokochat/"
)
