package com.tokopedia.url

/**
 * @author okasurya on 4/9/19.
 */

internal val staging = Url(
        TYPE = Env.STAGING,
        WS = "https://ws-staging.tokopedia.com/",
        API = "https://api-staging.tokopedia.com/",
        WEB = "https://staging.tokopedia.com/",
        MOBILEWEB = "https://m-staging.tokopedia.com/",
        ACE = "https://ace-staging.tokopedia.com/",
        TOME = "https://tome-staging.tokopedia.com/",
        TA = "https://ta-staging.tokopedia.com/",
        MOJITO = "https://mojito-staging.tokopedia.com/",
        HADES = "https://hades-staging.tokopedia.com/",
        MERLIN = "https://merlin-staging.tokopedia.com/",
        ACCOUNTS = "https://accounts-staging.tokopedia.com/",
        INBOX = "https://inbox-staging.tokopedia.com/",
        CHAT = "https://chat-staging.tokopedia.com",
        WS_CHAT = "wss://chat-staging.tokopedia.com",
        GROUPCHAT = "https://groupchat-staging.tokopedia.com",
        WS_GROUPCHAT = "wss://groupchat-staging.tokopedia.com",
        JS = "https://js-staging.tokopedia.com/",
        KERO = "https://kero-staging.tokopedia.com/",
        JAHE = "https://jahe-staging.tokopedia.com/",
        GOLDMERCHANT = "https://goldmerchant-staging.tokopedia.com/",
        PULSA = "https://pulsa-staging.tokopedia.com/",
        PULSA_API = "https://pulsa-api-staging.tokopedia.com/",
        PAY_ID = "https://pay-staging.tokopedia.id/",
        PAY = "https://pay-staging.tokopedia.com",
        PAYMENT = "https://payment-staging.tokopedia.com/",
        GQL = "https://gql-staging.tokopedia.com/",
        GW = "https://gw-staging.tokopedia.com/",
        GALADRIEL = "https://galadriel-staging.tokopedia.com/",
        FS = "https://fs-staging.tokopedia.net/",
        TOKOCASH = "https://www.tokocash.com/",
        OMSCART = "https://omscart-staging.tokopedia.com/",
        BOOKING = "https://booking-staging.tokopedia.com/",
        TIKET = "https://tiket-staging.tokopedia.com/",
        IMT = "https://imt-staging.tokopedia.com/",
        LAKU6 = "http://wst.laku6.com",
        SELLER = "https://seller-staging.tokopedia.com/",
        PLAY = "https://groupchat-staging.tokopedia.com",
        WS_PLAY = "wss://groupchat-staging.tokopedia.com",
        HUB = "https://hub-staging.tokopedia.com/",
        PCIDSS_CREDIT_CARD = "https://pulsa-staging.tokopedia.id/",
        GOJEK_OTP = "https://accounts-integration.gojek.com/",
        GOPAY_PIN = "https://integration-gws-app.gopayapi.com/",
        SSE = "https://sse-staging.tokopedia.com/",
        ONE_TRUST = "https://uat-de.onetrust.com/",
        TOKOCHAT = "https://chat-staging.tokopedia.com/tokochat/"
)
