package com.tokopedia.url

/**
 * @author okasurya on 4/8/19.
 */

data class Url(
    val TYPE: Env,
    val WS: String,
    val API: String,
    val WEB: String,
    val MOBILEWEB: String,
    val ACE: String,
    val TOME: String,
    val TA: String,
    val MOJITO: String,
    val HADES: String,
    val MERLIN: String,
    val ACCOUNTS: String,
    val INBOX: String,
    val CHAT: String,
    val WS_CHAT: String,
    val GROUPCHAT: String,
    val WS_GROUPCHAT: String,
    val JS: String,
    val KERO: String,
    val JAHE: String,
    val GOLDMERCHANT: String,
    val PULSA: String,
    val PULSA_API: String,
    val PAY_ID: String,
    val PAY: String,
    val PAYMENT: String,
    val GQL: String,
    val GW: String,
    val GALADRIEL: String,
    val FS: String,
    val TOKOCASH: String,
    val OMSCART: String,
    val BOOKING: String,
    val TIKET: String,
    val IMT: String,
    val LAKU6: String,
    val SELLER: String,
    val PLAY: String,
    val WS_PLAY: String,
    val HUB: String,
    val PCIDSS_CREDIT_CARD: String,
    val GOJEK_OTP: String,
    val GOPAY_PIN: String,
    val SSE: String,
    val ONE_TRUST: String,
    val TOKOCHAT: String,
    val AFFILIATE: String,
    val ONE_KYC_CLICKSTREAM: String
)
