package com.tokopedia.moneyin

object MoneyInGTMConstants {
    const val CEK_FISIK = "cek fisik"
    const val CLICK_SALIN = "click salin"
    const val CLICK_SOCIAL_SHARE = "click social share"
    const val CEK_FISIK_MONEY_IN = "cek fisik money in"
    const val CEK_FUNGSI_TRADE_IN = "cek fungsi trade in"
    const val CEK_FUNGSI_MONEY_IN = "cek fungsi money in"
    const val CEK_FISIK_RESULT_TRADE_IN = "cek fisik result trade in"
    const val CEK_FISIK_RESULT_MONEY_IN = "cek fisik result money in"
    const val ACTION_VIEW_MONEYIN = "viewMoneyIn"
    const val ACTION_CLICK_MONEYIN = "clickMoneyIn"
    const val ACTION_LAKU6_GTM = "laku6-gtm"
    const val ACTION_KEMBALI_KE_DETAIL_PRODUK = "click kembali ke detail produk"
    const val ACTION_CLICK_MULAI_FUNGSI = "click mulai cek fungsi"
    const val ACTION_VIEW_HARGA_FINAL = "view harga final"
    const val ACTION_CLICK_BATAL_BUTTON = "click batal button"
    const val ACTION_CLICK_KEMBALI_BUTTON = "click kembali button"
    const val ACTION_CLICK_SETUJU_BUTTON = "click setuju button"
    const val ACTION_CLICK_ICON_TNC = "click icon syarat dan ketentuan"
    const val ACTION_VIEW_CHECKOUT_PAGE = "view checkout page money in"
    const val ACTION_CLICK_PILIH_KURIR = "click pilih kurir"
    const val ACTION_CLICK_PILIH_WAKTU_PANGAMBILAN = "click pilih waktu pengambilan"
    const val ACTION_CLICK_PILIH = "click pilih"
    const val ACTION_CLICK_PILIH_PEMBAYARAN = "click pilih pembayaran"
    const val ACTION_CLICK_UBAH_KURIR = "click ubah kurir button"
    const val ACTION_CLICK_UBAH_WAKTU = "click ubah waktu button"
    const val VIEW_PRICE_RANGE_PAGE = "view price range page"
    const val BERI_IZIN_PENG_HP = "beri izin pengecekan hp"
    const val ACTION = "action"
    const val PAGE = "page"
    const val VALUE = "value"
    const val SUCCESS = "success"
    const val FAILURE = "failure"
    const val CATEGORY_TRADEIN_START_PAGE = "trade in start page"
    const val CATEGORY_TRADEIN_HARGA_FINAL = "harga final trade in"
    const val CATEGORY_MONEYIN_HARGA_FINAL = "harga final money in"
    const val CATEGORY_MONEYIN_PRICERANGE_PAGE = "money in price range page"
    const val CATEGORY_MONEYIN_COURIER_SELECTION = "courier selection money in"
    const val CATEGORY_MONEYIN_COURIER_SELECTION_DROP = "courier selection money in-drop"
    const val KEY_CURRENT_SITE = "currentSite"
}