package com.tokopedia.play.broadcaster.view.adapter.delegate

import android.view.View
import android.view.ViewGroup
import com.tokopedia.adapterdelegate.TypedAdapterDelegate
import com.tokopedia.play.broadcaster.ui.viewholder.setup.PlayAutoGeneratedCoverViewHolder
import com.tokopedia.play.broadcaster.view.adapter.PlayAutoGeneratedCoverAdapter
import com.tokopedia.play.broadcaster.R

internal class PlayAutoGeneratedCoverAdapterDelegate {

    internal class PlayAutoGeneratedCover: TypedAdapterDelegate<
        PlayAutoGeneratedCoverAdapter.Model.PlayAutoGeneratedCoverModel,
        PlayAutoGeneratedCoverAdapter.Model,
        PlayAutoGeneratedCoverViewHolder>(R.layout.item_setup_cover_auto_generated) {

        override fun onBindViewHolder(
            item: PlayAutoGeneratedCoverAdapter.Model.PlayAutoGeneratedCoverModel,
            holder: PlayAutoGeneratedCoverViewHolder
        ) {
            holder.bind(item.data)
        }

        override fun onCreateViewHolder(
            parent: ViewGroup,
            basicView: View
        ): PlayAutoGeneratedCoverViewHolder {
            return PlayAutoGeneratedCoverViewHolder.create(parent)
        }
    }

}
