package com.tokopedia.play.broadcaster.view.adapter.delegate

import android.view.View
import android.view.ViewGroup
import com.tokopedia.adapterdelegate.TypedAdapterDelegate
import com.tokopedia.play.broadcaster.ui.viewholder.setup.PlayAutoGeneratedCoverViewHolder
import com.tokopedia.play.broadcaster.view.adapter.PlayAutoGeneratedCoverAdapter
import com.tokopedia.play_common.R as playCommonR

/**
 * Created by fachrizalmrsln on 16/01/23
 */
internal class PlayAutoGeneratedCoverAdapterDelegate {

    internal class PlayAutoGeneratedCover(
        private val listener: PlayAutoGeneratedCoverAdapter.Listener
    ): TypedAdapterDelegate<
        PlayAutoGeneratedCoverAdapter.Model.PlayAutoGeneratedCoverModel,
        PlayAutoGeneratedCoverAdapter.Model,
        PlayAutoGeneratedCoverViewHolder>(playCommonR.layout.view_play_empty) {

        override fun onBindViewHolder(
            item: PlayAutoGeneratedCoverAdapter.Model.PlayAutoGeneratedCoverModel,
            holder: PlayAutoGeneratedCoverViewHolder
        ) {
            holder.bind(item.data)
        }

        override fun onCreateViewHolder(
            parent: ViewGroup,
            basicView: View
        ): PlayAutoGeneratedCoverViewHolder {
            return PlayAutoGeneratedCoverViewHolder.create(listener, parent)
        }
    }

}
