package com.tokopedia.campaign.usecase


import com.tokopedia.campaign.data.request.GetTargetedTickerRequest
import com.tokopedia.campaign.data.response.GetTargetedTickerResponse
import com.tokopedia.campaign.entity.RemoteTicker
import com.tokopedia.campaign.mapper.GetTargetedTickerMapper
import com.tokopedia.gql_query_annotation.GqlQueryInterface
import com.tokopedia.graphql.coroutines.data.extensions.getSuccessData
import com.tokopedia.graphql.coroutines.domain.interactor.GraphqlUseCase
import com.tokopedia.graphql.coroutines.domain.repository.GraphqlRepository
import com.tokopedia.graphql.data.model.CacheType
import com.tokopedia.graphql.data.model.GraphqlCacheStrategy
import com.tokopedia.graphql.data.model.GraphqlRequest
import javax.inject.Inject

/**
 * Generated by Tokopedia GQL UseCase Generator plugins version 1.0
 */
class GetTargetedTickerUseCase @Inject constructor(
    private val repository: GraphqlRepository,
    private val mapper: GetTargetedTickerMapper
) : GraphqlUseCase<List<RemoteTicker>>(repository) {

    init {
        setCacheStrategy(GraphqlCacheStrategy.Builder(CacheType.ALWAYS_CLOUD).build())
    }


    private val query = object : GqlQueryInterface {
        private val OPERATION_NAME = "GetTargetedTicker"
        private val QUERY = """query GetTargetedTicker(${'$'}input: GetTargetedTickerRequest!) {
  GetTargetedTicker(input: ${'$'}input) {
    List {
      Action {
        Type
        AppURL
        Label
        WebURL
      }
      Type
      Content
      Priority
      Title
      ID
    }
  }
}
"""

        override fun getOperationNameList(): List<String> = listOf(OPERATION_NAME)
        override fun getQuery(): String = QUERY
        override fun getTopOperationName(): String = OPERATION_NAME
    }


    suspend fun execute(param: Param): List<RemoteTicker> {
        val request = buildRequest(param)
        val response = repository.response(listOf(request))
        return mapper.map(response.getSuccessData())
    }

    private fun buildRequest(param: Param): GraphqlRequest {
        val targets = param.targets.map {
            GetTargetedTickerRequest.Target(it.type, it.values)
        }

        val payload = GetTargetedTickerRequest(param.page, targets)

        val params = mapOf("input" to payload)

        return GraphqlRequest(
            query,
            GetTargetedTickerResponse::class.java,
            params
        )
    }

    data class Param(val page: String, val targets: List<Target> = emptyList()) {
        data class Target(val type: String, val values: List<String>)
    }

    companion object {
        const val KEY_TYPE_ROLLENCE_NAME = "rollence_name"
    }

}
