package com.tokopedia.autocomplete.suggestion

const val SUGGESTION_HEADER = "header"
const val SUGGESTION_SINGLE_LINE = "list_single_line"
const val SUGGESTION_DOUBLE_LINE = "list_double_line"
const val SUGGESTION_DOUBLE_LINE_WITHOUT_IMAGE = "list_double_line_without_image"
const val SUGGESTION_TOP_SHOP_WIDGET = "top_shop_widget"
const val SUGGESTION_TOP_SHOP = "top_shop"
const val SUGGESTION_TOP_SHOP_SEE_MORE = "top_shop_all"
const val SUGGESTION_PRODUCT_LINE = "list_product_line"
const val TYPE_KEYWORD = "keyword"
const val TYPE_RECENT_KEYWORD = "recent_keyword"
const val TYPE_CURATED = "curated"
const val TYPE_SHOP = "shop"
const val TYPE_PROFILE = "profile"
const val TYPE_LOCAL = "local"
const val TYPE_GLOBAL = "global"
const val TYPE_PRODUCT = "product"