// Generated by dagger.internal.codegen.ComponentProcessor (https://google.github.io/dagger).
package com.tokopedia.logisticaddaddress.features.district_recommendation.shopsettings;

import com.tokopedia.logisticaddaddress.domain.usecase.GetShopAddressUseCase;
import com.tokopedia.user.session.UserSessionInterface;
import dagger.MembersInjector;
import javax.inject.Provider;

public final class DistrictRecommendationShopSettingsActivity_MembersInjector
    implements MembersInjector<DistrictRecommendationShopSettingsActivity> {
  private final Provider<GetShopAddressUseCase> getShopAddressUseCaseProvider;

  private final Provider<UserSessionInterface> userSessionProvider;

  public DistrictRecommendationShopSettingsActivity_MembersInjector(
      Provider<GetShopAddressUseCase> getShopAddressUseCaseProvider,
      Provider<UserSessionInterface> userSessionProvider) {
    assert getShopAddressUseCaseProvider != null;
    this.getShopAddressUseCaseProvider = getShopAddressUseCaseProvider;
    assert userSessionProvider != null;
    this.userSessionProvider = userSessionProvider;
  }

  public static MembersInjector<DistrictRecommendationShopSettingsActivity> create(
      Provider<GetShopAddressUseCase> getShopAddressUseCaseProvider,
      Provider<UserSessionInterface> userSessionProvider) {
    return new DistrictRecommendationShopSettingsActivity_MembersInjector(
        getShopAddressUseCaseProvider, userSessionProvider);
  }

  @Override
  public void injectMembers(DistrictRecommendationShopSettingsActivity instance) {
    if (instance == null) {
      throw new NullPointerException("Cannot inject members into a null reference");
    }
    instance.getShopAddressUseCase = getShopAddressUseCaseProvider.get();
    instance.userSession = userSessionProvider.get();
  }

  public static void injectGetShopAddressUseCase(
      DistrictRecommendationShopSettingsActivity instance,
      Provider<GetShopAddressUseCase> getShopAddressUseCaseProvider) {
    instance.getShopAddressUseCase = getShopAddressUseCaseProvider.get();
  }

  public static void injectUserSession(
      DistrictRecommendationShopSettingsActivity instance,
      Provider<UserSessionInterface> userSessionProvider) {
    instance.userSession = userSessionProvider.get();
  }
}
