package com.tokopedia.product.manage.feature.list.constant

import com.tokopedia.imageassets.ImageUrl

object ProductManageUrl {
    const val ILLUSTRATION_ADD_FEATURED_PRODUCT_DOMAIN = ImageUrl.ILLUSTRATION_ADD_FEATURED_PRODUCT_DOMAIN
    const val ILLUSTRATION_MAX_FEATURED_PRODUCT_DOMAIN = ImageUrl.ILLUSTRATION_MAX_FEATURED_PRODUCT_DOMAIN
    const val ILLUSTRATION_SPECIAL_FEATURED_PRODUCT_DOMAIN = ImageUrl.ILLUSTRATION_SPECIAL_FEATURED_PRODUCT_DOMAIN
    const val PRODUCT_MANAGE_SEARCH_EMPTY_STATE = ImageUrl.BRAND_NOT_FOUND
    const val PRODUCT_MANAGE_LIST_EMPTY_STATE = ImageUrl.PRODUCT_MANAGE_LIST_EMPTY_STATE
    const val ILLUSTRATION_STOCK_LOCATION = ImageUrl.ILLUSTRATION_STOCK_LOCATION
    const val ILLUSTRATION_NO_ACCESS = ImageUrl.ILLUSTRATION_NO_ACCESS

    const val PRODUCT_VIOLATION_HELP_URL = "https://www.tokopedia.com/help/article/produk-yang-saya-jual-dalam-pengawasan"

}
