package com.tokopedia.usercomponents.userconsent.common

object UserConsentUiTestCons {
    const val TNC_SINGLE_OPTIONAL = "TNC_SINGLE_OPTIONAL"
    const val TNC_SINGLE_MANDATORY = "TNC_SINGLE_MANDATORY"
    const val TNC_POLICY_SINGLE_OPTIONAL = "TNC_POLICY_SINGLE_OPTIONAL"
    const val TNC_POLICY_SINGLE_MANDATORY = "TNC_POLICY_SINGLE_MANDATORY"
    const val TNC_MULTIPLE_SOME_ARE_OPTIONAL = "TNC_MULTIPLE_SOME_ARE_OPTIONAL"
    const val TNC_POLICY_MULTIPLE_SOME_ARE_OPTIONAL = "TNC_POLICY_MULTIPLE_SOME_ARE_OPTIONAL"
}