package com.tokopedia.product.detail.view.viewmodel.product_detail

import com.tokopedia.product.detail.common.buttons_byte_io_tracker.ICartRedirectionButtonsByteIOTrackerViewModel
import com.tokopedia.product.detail.view.viewmodel.product_detail.mediator.GetProductDetailDataMediator

interface ICartRedirectionButtonsByteIOTrackerSubViewModel: ICartRedirectionButtonsByteIOTrackerViewModel {
    fun registerCartRedirectionButtonsByteIOTrackerSubViewModel(mediator: GetProductDetailDataMediator)
}
