package com.tokopedia.catalog.analytics

object CatalogTrackerConstant {
    const val KEY_EVENT = "event"
    const val KEY_EVENT_ACTION = "eventAction"
    const val KEY_EVENT_CATEGORY = "eventCategory"
    const val KEY_EVENT_LABEL = "eventLabel"
    const val KEY_BUSINESS_UNIT = "businessUnit"
    const val KEY_CURRENT_SITE = "currentSite"
    const val KEY_TRACKER_ID = "trackerId"
    const val KEY_ITEM_LIST = "item_list"
    const val KEY_ITEMS = "items"
    const val KEY_DIMENSION40 = "dimension40"
    const val KEY_DIMENSION61 = "dimension61"
    const val KEY_DIMENSION52 = "dimension52"
    const val KEY_INDEX = "index"
    const val KEY_ITEM_BRAND = "item_brand"
    const val KEY_ITEM_CATEGORY = "item_category"
    const val KEY_ITEM_ID = "item_id"
    const val KEY_ITEM_NAME = "item_name"
    const val KEY_ITEM_VARIANT = "item_variant"
    const val KEY_PRICE = "price"
    const val KEY_USER_ID = "userId"
    const val KEY_ECOMMERCE = "ecommerce"
    const val KEY_PROMOTIONS = "promotions"
    const val KEY_CREATIVE_NAME = "creative_name"
    const val KEY_CREATIVE_SLOT = "creative_slot"
    const val KEY_IS_LOGIN = "isLoggedInStatus"
    const val KEY_SCREEN_NAME = "screenName"

    const val EVENT_VIEW_ITEM = "view_item"
    const val EVENT_VIEW_PG_IRIS = "viewPGIris"
    const val EVENT_VIEW_CLICK_PG = "clickPG"
    const val EVENT_NAME_PRODUCT_CLICK = "productClick"
    const val EVENT_NAME_PRODUCT_VIEW = "productView"
    const val EVENT_OPEN_SCREEN = "openScreen"

    const val EVENT_ACTION_IMPRESSION_HERO_IMAGE = "impress hero image"
    const val EVENT_ACTION_IMPRESSION_TRUSTMAKER = "impress trustmaker"
    const val EVENT_ACTION_IMPRESSION_TOP_FEATURE = "impress top feature"
    const val EVENT_ACTION_IMPRESSION_EXPERT_REVIEW = "impress expert review"
    const val EVENT_ACTION_IMPRESSION_NAVIGATION = "impress navigation"
    const val EVENT_ACTION_CLICK_NAVIGATION = "click navigation"
    const val EVENT_ACTION_CLICK_SEE_MORE_SPECIFICATION = "click lihat semua on specification"

    const val EVENT_ACTION_IMPRESSION_BANNER = "impress banner"
    const val EVENT_ACTION_IMPRESSION_TEXT_DESCRIPTION = "impress text description"
    const val EVENT_ACTION_CLICK_VIDEO_EXPERT_REVIEW = "click tonton review on expert review"
    const val EVENT_ACTION_IMPRESSION_FAQ = "impress faq"
    const val EVENT_ACTION_CLICK_FAQ = "click faq"
    const val EVENT_ACTION_IMPRESSION_DOUBLE_BANNER = "impress double banner"
    const val EVENT_ACTION_IMPRESSION_PRICE_BOTTOM_SHEET = "impress price bottomsheet"
    const val EVENT_ACTION_SEE_OPTIONS = "click lihat pilihan on price bottomsheet"
    const val EVENT_ACTION_CLICK_BACK_BUTTON = "click back button"
    const val EVENT_ACTION_CLICK_QUICK_FILTER = "click quick filter"
    const val EVENT_ACTION_CLICK_FILTER = "click filter"
    const val EVENT_ACTION_CLICK_PRODUCT = "click product"
    const val EVENT_ACTION_CLICK_ADD_TO_CART = "click keranjang"
    const val EVENT_ACTION_IMPRESSION_PRODUCT = "impress product"
    const val EVENT_IMAGE_BANNER_IMPRESSION = "image banner impression"
    const val EVENT_TRUSTMAKER_IMPRESSION = "trustmaker banner impression"
    const val EVENT_TOP_FEATURE_IMPRESSION = "top feature banner impression"
    const val EVENT_REVIEW_BANNER_IMPRESSION = "expert review banner impression"
    const val EVENT_IMPRESSION_COMPARISON = "impress comparison"
    const val EVENT_CLICK_SEE_MORE_COMPARISON = "click lihat semua on comparison"
    const val EVENT_CLICK_CHANGE_COMPARISON = "click change catalog on comparison"
    const val EVENT_CLICK_SEARCH_COMPARISON = "click search bar on comparison"
    const val EVENT_CLICK_COMPARE_ON_COMPARISON = "click bandingkan on comparison"
    const val EVENT_IMPRESSION_COMPARISON_DETAIL = "impress catalog comparison"
    const val EVENT_CLICK_CHANGE_COMPARISON_DETAIL = "click change catalog"
    const val EVENT_IMPRESSION_VIDEO_WIDGET = "impression video widget"
    const val EVENT_IMPRESSION_VIDEO_BANNER_WIDGET = "video banner impression"
    const val EVENT_IMPRESSION_COLUMN_INFO_WIDGET = "impression specification"
    const val EVENT_IMPRESSION_COLUMN_INFO_BANNER_WIDGET = "specification banner impression"
    const val EVENT_CLICK_CLOSE_ON_IMAGE_REVIEW = "click close on image review"
    const val EVENT_CLICK_ON_IMAGE_REVIEW_BS = "click image on list review"
    const val EVENT_CLICK_ON_IMAGE_REVIEW = "click image on review"
    const val EVENT_CLICK_ON_SELENGKAPNYA_REVIEW = "click selengkapnya on review"
    const val EVENT_IMPRESSION_REVIEW_WIDGET = "impression review widget"

    const val EVENT_CATEGORY_CATALOG_PAGE = "catalog page"
    const val EVENT_CATEGORY_CATALOG_PAGE_REIMAGINE = "catalog page reimagined - main page"
    const val EVENT_CATEGORY_CATALOG_PAGE_REIMAGINE_PRODUCT_LIST = "catalog page reimagined - product list"
    const val EVENT_CATEGORY_CATALOG_PAGE_REIMAGINE_COMPARISON = "catalog page reimagined - comparison page"

    const val SCREEN_NAME_CATALOG_DETAIL_PAGE = "Browse Catalog - Reimagined Main Page"
    const val SCREEN_NAME_CATALOG_PRODUCT_LIST_PAGE = "Browse Catalog - Reimagined Product List"
    const val SCREEN_NAME_CATALOG_COMPARISON_PAGE = "Browse Catalog - Reimagined Comparison Page"

    const val TRACKER_ID_IMPRESSION_HERO_BANNER = "46964"
    const val TRACKER_ID_IMPRESSION_TRUSTMAKER = "46966"
    const val TRACKER_ID_IMPRESSION_TOP_FEATURE = "46968"
    const val TRACKER_ID_IMPRESSION_NAVIGATION = "46970"
    const val TRACKER_ID_CLICK_NAVIGATION = "46971"
    const val TRACKER_ID_IMPRESSION_BANNER_THREE_BY_FOUR = "46972"
    const val TRACKER_ID_IMPRESSION_TEXT_DESCRIPTION = "46974"
    const val TRACKER_ID_IMPRESSION_BANNER_TWO_BY_ONE = "46976"
    const val TRACKER_ID_IMPRESSION_EXPERT_REVIEW = "46978"
    const val TRACKER_ID_IMPRESSION_BANNER_ONE_BY_ONE = "46986"
    const val TRACKER_ID_CLICK_VIDEO_EXPERT = "46980"
    const val TRACKER_ID_IMPRESSION_FAQ = "46984"
    const val TRACKER_ID_CLICK_FAQ = "46985"
    const val TRACKER_ID_IMPRESSION_DOUBLE_BANNER = "46988"
    const val TRACKER_ID_IMPRESSION_PRICE = "46990"
    const val TRACKER_ID_CLICK_BUTTON_CHOOSE = "46991"
    const val TRACKER_ID_BACK_BUTTON_CATALOG_PRODUCT_LIST = "47195"
    const val TRACKER_ID_QUICK_FILTER_CATALOG_PRODUCT_LIST = "47194"
    const val TRACKER_ID_FILTER_CATALOG_PRODUCT_LIST = "47193"
    const val TRACKER_ID_CLICK_CATALOG_PRODUCT_LIST = "46992"
    const val TRACKER_ID_CLICK_ADD_TO_CART_CATALOG_PRODUCT_LIST = "46993"
    const val TRACKER_ID_IMPRESSION_PRODUCT = "46994"
    const val TRACKER_ID_IMPRESSION_VIDEO = "30119"
    const val TRACKER_ID_CLICK_SEE_MORE_COLUMN_INFO = "46983"

    const val TRACKER_ID_IMPRESSION_COLUMN_INFO = "46981"

    const val TRACKER_ID_CLICK_SEE_MORE_COMPARISON = "47977"
    const val TRACKER_ID_IMPRESSION_COMPARISON = "47715"
    const val TRACKER_ID_CHANGE_COMPARISON = "48041"
    const val TRACKER_ID_CHANGE_COMPARISON_IN_COMPARISON_DETAIL = "48042"
    const val TRACKER_ID_SEARCH_COMPARISON = "47978"
    const val TRACKER_ID_CLICK_COMPARE_COMPARISON = "47979"
    const val TRACKER_ID_IMPRESSION_COMPARISON_DETAIL = "47980"

    const val TRACKER_ID_OPEN_PAGE_CATALOG_DETAIL = "48753"
    const val TRACKER_ID_OPEN_PAGE_CATALOG_PRODUCT_LIST = "48754"
    const val TRACKER_ID_OPEN_PAGE_CATALOG_COMPARISON = "48752"

    const val TRACKER_ID_CLICK_CLOSE_ON_IMAGE_REVIEW = "26906"
    const val TRACKER_ID_CLICK_ON_IMAGE_REVIEW_BS = "26899"
    const val TRACKER_ID_CLICK_ON_IMAGE_REVIEW = "26901"
    const val TRACKER_ID_CLICK_ON_SELENGKAPNYA_REVIEW = "26894"
    const val TRACKER_ID_IMPRESSION_REVIEW_WIDGET = "30117"

    const val BUSINESS_UNITS = "Physical Goods"
    const val CURRENT_SITE = "tokopediamarketplace"
}
