package com.tokopedia.productcard.utils

internal const val LIGHT_GREY = "lightGrey"
internal const val LIGHT_BLUE = "lightBlue"
internal const val LIGHT_GREEN = "lightGreen"
internal const val LIGHT_RED = "lightRed"
internal const val LIGHT_ORANGE = "lightOrange"
internal const val DARK_GREY = "darkGrey"
internal const val DARK_BLUE = "darkBlue"
internal const val DARK_GREEN = "darkGreen"
internal const val DARK_RED = "darkRed"
internal const val DARK_ORANGE = "darkOrange"

internal const val LABEL_PRODUCT_STATUS = "status"
internal const val LABEL_PRICE = "price"
internal const val LABEL_GIMMICK = "gimmick"
internal const val LABEL_CREDIBILITY = "credibility"
internal const val LABEL_SHIPPING = "shipping"

internal const val HEADING_1 = "heading_1"
internal const val HEADING_2 = "heading_2"
internal const val HEADING_3 = "heading_3"
internal const val HEADING_4 = "heading_4"
internal const val HEADING_5 = "heading_5"
internal const val HEADING_6 = "heading_6"
internal const val BODY_1 = "body_1"
internal const val BODY_2 = "body_2"
internal const val BODY_3 = "body_3"
internal const val SMALL = "small"
internal const val REGULAR = "regular"
internal const val BOLD = "bold"