query OrderListQuery($orderCategory: OrderCategory, $Page: Int!, $PerPage: Int!, $ID: Int!, $OrderStatus: Int!, $Search: String, $StartDate: String, $EndDate: String) {
  orders(orderCategory: $orderCategory, Page: $Page, PerPage: $PerPage, ID: $ID, OrderStatus: $OrderStatus, Search: $Search, StartDate: $StartDate, EndDate: $EndDate){
    metaData {
      label
      value
      textColor
      backgroundColor
      __typename
    }
    paymentData {
      imageUrl
      label
      value
      textColor
      backgroundColor
      __typename
    }
    conditionalInfo {
      text
      color {
        border
        background
        __typename
      }
      __typename
    }
    title
    categoryName
    category
    upstream
    id
    createdAt
    status
    statusStr
    statusColor
    invoiceRefNum
    title
    dotMenu {
      name
      uri
      __typename
    }
    actionButtons {
      label
      buttonType
      uri
      uriWeb
      mappingUri
      weight
      popup {
        title
        popuptext
        __typename
      }
      __typename
    }
    totalInvoices
    items {
      imageUrl
      name
      __typename
    }
    beforeOrderId
    __typename
  }
}