query ($device_id: Int!, $category_ids: String, $mp_category_ids: [Int]) {\n  rechargeFavoriteRecommendationList(device_id: $device_id, category_ids: $category_ids, mp_category_ids: $mp_category_ids) {\n    title\n    recommendations {\n      iconUrl\n      title\n      clientNumber\n      appLink\n      webLink\n      type\n      position\n      categoryId\n      categoryName\n      productId\n      productName\n      productPrice\n      isATC\n      operatorName\n      operatorID\n      tag\n      tagType\n      description\n    }\n  }\n}\n