query OrderTickers($input:OrderTickersArgs!) {
orderTickers(input:$input) {
   user_id
       request_by
       client
       total
       tickers {
     id
     body
     is_active
     short_desc
   }
 }
}