-keep class com.tokopedia.common.payment.model.PaymentPassData
-keep class com.tokopedia.loyalty.common.PopUpNotif
-keep class com.tokopedia.loyalty.common.TokoPointDrawerData
-keep class androidx.startup.AppInitializer
-keep class * extends androidx.startup.Initializer