package com.tokopedia.imagepicker.editor.analytics

object ImageEditorTrackingConstant {
    const val EVENT_KEY = "event"
    const val ACTION_KEY = "eventAction"
    const val CATEGORY_KEY = "eventCategory"
    const val LABEL_KEY = "eventLabel"
    const val BUSINESS_UNIT_KEY = "businessUnit"
    const val CURRENT_SITE_KEY = "currentSite"
    const val USER_ID_KEY = "userId"
    const val PAGE_TYPE_KEY = "pageType"
    const val EVENT = "clickImageEditor"
    const val EVENT_CATEGORY = "image editor"
    const val EVENT_ACTION = "click on simpan button"
    const val BUSINESS_UNIT = "media"
    const val CURRENT_SITE = "tokopediamarketplace"
    const val LABEL_BRIGHTNESS = "brightness"
    const val LABEL_CONTRAST = "contrast"
    const val LABEL_CROP = "crop"
    const val LABEL_ROTATION = "rotation"
    const val LABEL_WATERMARK_DESIGN_ONE = "watermark - design1"
    const val LABEL_WATERMARK_DESGIN_TWO = "watermark - design2"
    const val LABEL_REMOVE_BACKGROUND_NORMAL = "removebg - original"
    const val LABEL_REMOVE_BACKGROUND_WHITE = "removebg - putih"
    const val LABEL_REMOVE_BACKGROUND_GREY = "removebg - kelabu"
}