package com.tokopedia.seller_migration_common.presentation.fragment

import com.tokopedia.seller_migration_common.presentation.SellerFeatureChatStaticDataProvider

class SellerFeatureChatTabFragment : BaseSellerFeatureTabFragment(SellerFeatureChatStaticDataProvider)