package com.tokopedia.seller_migration_common.presentation.fragment

import com.tokopedia.seller_migration_common.presentation.SellerFeatureFinancialServicesStaticDataProvider

class SellerFeatureFinancialServicesTabFragment: BaseSellerFeatureTabFragment(SellerFeatureFinancialServicesStaticDataProvider)