package com.tokopedia.seller_migration_common.presentation.fragment

import com.tokopedia.seller_migration_common.presentation.SellerFeatureProductStaticDataProvider

class SellerFeatureProductTabFragment(recyclerViewListener: SellerMigrationFragment) : BaseSellerFeatureTabFragment(recyclerViewListener, SellerFeatureProductStaticDataProvider)