package com.tokopedia.seller_migration_common.presentation.fragment

import com.tokopedia.seller_migration_common.presentation.SellerFeatureReviewStaticDataProvider

class SellerFeatureReviewTabFragment : BaseSellerFeatureTabFragment(SellerFeatureReviewStaticDataProvider)