package com.tokopedia.shop.campaign.domain.usecase

import com.tokopedia.gql_query_annotation.GqlQueryInterface
import com.tokopedia.graphql.coroutines.data.extensions.getSuccessData
import com.tokopedia.graphql.coroutines.domain.interactor.GraphqlUseCase
import com.tokopedia.graphql.coroutines.domain.repository.GraphqlRepository
import com.tokopedia.graphql.data.model.CacheType
import com.tokopedia.graphql.data.model.GraphqlCacheStrategy
import com.tokopedia.graphql.data.model.GraphqlRequest
import com.tokopedia.shop.campaign.data.response.UsePromoVoucherResponse
import javax.inject.Inject

/**
 * Generated by Tokopedia GQL UseCase Generator plugins version 1.0
 */
class UsePromoVoucherUseCase @Inject constructor(
    private val repository: GraphqlRepository
) : GraphqlUseCase<Boolean>(repository) {

    companion object {
        private const val REQUEST_PARAM_KEY_PROMO_CODE= "promoCode"
    }

    init {
        setCacheStrategy(GraphqlCacheStrategy.Builder(CacheType.ALWAYS_CLOUD).build())
    }


    private val mutation = object : GqlQueryInterface {
        private val OPERATION_NAME = "save_cache_auto_apply"
        private val MUTATION =
            """mutation save_cache_auto_apply(${'$'}promoCode: String) {
  save_cache_auto_apply(promoCode: ${'$'}promoCode) {
    Success
  }
}
"""

        override fun getOperationNameList(): List<String> = listOf(OPERATION_NAME)
        override fun getQuery(): String = MUTATION
        override fun getTopOperationName(): String = OPERATION_NAME
    }


    suspend fun execute(promoCode: String): Boolean {
        val request = buildRequest(promoCode)
        val response = repository.response(listOf(request))
        val data = response.getSuccessData<UsePromoVoucherResponse>()
        return data.saveCacheAutoReply.success
    }

    private fun buildRequest(promoCode: String): GraphqlRequest {
        val params = mapOf(REQUEST_PARAM_KEY_PROMO_CODE to promoCode)

        return GraphqlRequest(
            mutation,
            UsePromoVoucherResponse::class.java,
            params
        )
    }



}
