package com.tokopedia.shop.campaign.domain.usecase

import com.tokopedia.gql_query_annotation.GqlQueryInterface
import com.tokopedia.graphql.coroutines.data.extensions.getSuccessData
import com.tokopedia.graphql.coroutines.domain.interactor.GraphqlUseCase
import com.tokopedia.graphql.coroutines.domain.repository.GraphqlRepository
import com.tokopedia.graphql.data.model.CacheType
import com.tokopedia.graphql.data.model.GraphqlCacheStrategy
import com.tokopedia.graphql.data.model.GraphqlRequest
import com.tokopedia.kotlin.extensions.view.toIntOrZero
import com.tokopedia.shop.campaign.data.response.UsePromoVoucherResponse
import javax.inject.Inject

/**
 * Generated by Tokopedia GQL UseCase Generator plugins version 1.0
 */
class UsePromoVoucherUseCase @Inject constructor(
    private val repository: GraphqlRepository
) : GraphqlUseCase<Boolean>(repository) {

    companion object {
        private const val REQUEST_PARAM_KEY_SERVICE_ID = "serviceID"
        private const val REQUEST_PARAM_KEY_PROMO_CODE = "promoCode"
        private const val REQUEST_PARAM_KEY_SHOP_ID = "shopID"
        private const val PHYSICAL_GOODS_SERVICE_ID = "marketplace"
    }

    init {
        setCacheStrategy(GraphqlCacheStrategy.Builder(CacheType.ALWAYS_CLOUD).build())
    }


    private val mutation = object : GqlQueryInterface {
        private val OPERATION_NAME = "saveCacheAutoApplyStack"
        private val MUTATION =
            """mutation saveCacheAutoApplyStack(${'$'}serviceID: String!, ${'$'}promoCode: String!, ${'$'}shopID: Int!) {
  saveCacheAutoApplyStack(serviceID: ${'$'}serviceID, promoCode: ${'$'}promoCode, shopID: ${'$'}shopID) {
    Success
  }
}
"""

        override fun getOperationNameList(): List<String> = listOf(OPERATION_NAME)
        override fun getQuery(): String = MUTATION
        override fun getTopOperationName(): String = OPERATION_NAME
    }


    suspend fun execute(param: Param): Boolean {
        val request = buildRequest(param)
        val response = repository.response(listOf(request))
        val data = response.getSuccessData<UsePromoVoucherResponse>()
        return data.saveCacheAutoApplyStack.success
    }

    private fun buildRequest(param: Param): GraphqlRequest {
        val params = mapOf(
            REQUEST_PARAM_KEY_SERVICE_ID to PHYSICAL_GOODS_SERVICE_ID,
            REQUEST_PARAM_KEY_PROMO_CODE to param.promoCode,
            REQUEST_PARAM_KEY_SHOP_ID to param.shopId.toIntOrZero()
        )

        return GraphqlRequest(
            mutation,
            UsePromoVoucherResponse::class.java,
            params
        )
    }

    data class Param(val shopId: String, val promoCode: String)

}
