package com.tokopedia.topads.edit.utils

object Constants {

    const val SELECTED_DATA = "selectedData"
    const val PRODUCT_ID = "product"
    const val MIN_SUGGESTION = "minSuggestedBid"
    const val GROUP_ID = "groupId"
    const val SELECTED_KEYWORD = "selectKeywords"
    const val RESTORED_DATA = "restoreData"
    const val CURRENTLIST = "currentKeywords"
    const val RESULT_PRICE = "resultPrice"
    const val RESULT_PROUCT = "resultProduct"
    const val RESULT_NAME = "resultName"
    const val RESULT_IMAGE = "resultImage"
    const val ALL = "all"
    const val ROW = 50
    const val EXISTING_IDS = "ExistingIds"
    const val POSITION0 = 0
    const val POSITION1 = 1
    const val POSITIVE_CREATE = "createdPositiveKeyword"
    const val POSITIVE_DELETE = "deletedPositiveKeyword"
    const val POSITIVE_EDIT = "editedPositiveKeyword"
    const val POSITIVE_KEYWORD_ALL = "editedAllPositiveKeyword"
    const val NEGATIVE_KEYWORD_ALL = "editedAllNegativeKeyword"
    const val NEGATIVE_KEYWORDS_ADDED = "negative_keywords_added"
    const val NEGATIVE_KEYWORDS_DELETED = "negative_keywords_deleted"
    const val STRATEGIES = "strategies"
    const val GROUP_NAME = "group_name"
    const val PRICE_BID = "price_bid"
    const val DAILY_BUDGET = "daily_budget"
    const val NAME_EDIT = "isNameEdit"
    const val MULTIPLIER = 40
    const val MAXIMUM_LIMIT = "10.000.000"
    const val PRODUCT = "product"
    const val BUDGET_LIMITED = "isBudgetLimited"
    const val KEYWORD_EXISTS = 1
    const val KEYWORD_TYPE_PHRASE = 11
    const val KEYWORD_TYPE_EXACT = 21
    const val KEYWORD_TYPE_NEGATIVE_PHRASE = 12
    const val KEYWORD_TYPE_NEGATIVE_EXACT = 22
    const val REQUEST_OK = 1
    const val ADDED_PRODUCTS = "addedProducts"
    const val DELETED_PRODUCTS = "deletedProducts"
    const val EDIT_SOURCE = "dashboard_edit_group_app"
    const val ACTION_EDIT = "edit"
    const val ACTION_ADD = "add"
    const val ACTION_REMOVE = "remove"
    const val ACTION_CREATE = "create"
    const val ACTION_DELETE = "delete"
    const val PUBLISHED = "published"
    const val POSITIVE_PHRASE = "positive_phrase"
    const val POSITIVE_SPECIFIC = "positive_exact"
    const val NEGATIVE_PHRASE = "negative_phrase"
    const val NEGATIVE_SPECIFIC = "negative_exact"
    const val ACTIVE = "active"
    const val KEYWORD_SOURCE = "es"
    const val INPUT = "input"
    const val DEBOUNCE_CONST: Long = 200
    const val MULTIPLY_CONST = "50"
    const val groupId = "groupId"
    const val priceBid = "price_bid"
    const val groupName = "groupName"
    const val TAB_POSITION = "tab_position"
    const val MAX_BID = "max"
    const val MIN_BID = "min"
    const val SUGGESTION_BID = "suggest"
    const val KEYWORD_NAME = "keywordName"
    const val FROM_EDIT = "fromEdit"
    const val CURRENT_KEY_TYPE = "currentKeyType"
    const val ITEM_POSITION = "pos"
    const val KEYWORD_ID = "keywordId"
    const val KEYWORD_TYPE = "keywordType"
    const val IS_DATA_CHANGE = "dataChange"
    const val PRODUK_NAME = " Produk"
    const val KATA_KUNCI = " Kata Kunci"
    const val ATUR_NAME = " Atur"

}
