package com.tokopedia.common_epharmacy

const val EPHARMACY_UPLOAD_REQUEST_CODE = 10021
const val EPHARMACY_CHOOSER_REQUEST_CODE = 10022
const val EPHARMACY_MINI_CONSULTATION_REQUEST_CODE = 10023
const val EPHARMACY_CEK_RESEP_REQUEST_CODE = 10024

const val EPHARMACY_REDIRECT_CHECKOUT_RESULT_CODE = 10031
const val EPHARMACY_REDIRECT_CART_RESULT_CODE = 10032

const val EPHARMACY_CONSULTATION_RESULT_EXTRA = "epharmacy_consultation_result_extra"

const val EPHARMACY_CONSULTATION_STATUS_APPROVED = 2
const val EPHARMACY_CONSULTATION_STATUS_REJECTED = 4
