{
  kero_get_shipping_editor(userid:1234) {
    status
    config
    server_process_time
    data {
        whitelist
        activated_shipping
        shippers_v2 {
          shipping_conventional {
            shipper_id
            shipper_name
            shipper_code
            shipper_desc
            shipper_weight
            logo
            available
            services {
              service_type
              service_id
              service_name
              service_code
              service_desc
              type
              type_name
              minimum_weight
              maximum_weight
              available
              ui_hidden
            }
          }
          shipping_ondemand {
            shipper_id
            shipper_name
            shipper_code
            shipper_desc
            shipper_weight
            logo
            available
            services {
              service_type
              service_id
              service_name
              service_code
              service_desc
              type
              type_name
              minimum_weight
              maximum_weight
              available
              ui_hidden
            }
          }
        }
        activated_sp_v2
        address {
          address_1
          postal_code
          district
          district_name
          latitude
          longitude
          is_corner
        }
        is_official_shop
        eligible_add_custom
        csrf_token
        custom_shipping_url
        gmaps_key
        kero_url
        district_boundary_token {
          validate_token
          get_boundary_token
          date
        }
        district_recommendation_token {
          token
          date
          path
        }
        district_details_token {
          token
          date
          path
        }
        shipper_group_token {
          token
          date
          path
        }
        market_place_url
        gw_url
        status_op
        status_cod
        shipment_op
        shipment_cod
        whitelist_cod
        datahub_url
        gtm_id
        gtm_switch
    } 
  }
}