package com.tokopedia.shop.review.analytic

/**
 * Created by zulfikarrahman on 3/13/18.
 */
object ReputationTrackingConstant {
    //Event
    const val CLICK_OFFICIAL_STORE = "clickOfficialStore"
    const val CLICK_PDP = "clickPDP"
    const val CLICK_REVIEW_OLD = "clickReview"
    const val VIEW_REVIEW = "viewReviewIris"
    //Category
    const val OFFICIAL_STORE_SHOP_PAGE_BUYER = "official store shop page - buyer"
    const val OFFICIAL_STORE_SHOP_PAGE_BRAND = "official store shop page - brand"
    const val PRODUCT_DETAIL_PAGE = "product detail page"
    const val REVIEW_PAGE = "ulasan page"
    const val SELLER_FEEDBACK_PAGE = "seller feedback page"
    const val FILTER_INVOICE_PAGE = "filter invoice review"
    const val WAITING_REVIEWED = "menunggu diulas"
    const val INVOICE = "invoice"
    const val REVIEW_DETAIL_PAGE = "product review detail page"
    //Action
    const val TOP_CONTENT_CLICK = " - top content - click"
    const val TOP_CONTENT_THREE_DOTTED_CLICK = " - top content - three dotted menu - click"
    const val TOP_CONTENT_PAGE_CLICK = "%1\$s - top content - %2\$s page - click"
    const val TOP_CONTENT_PAGE_DOTTED_MENU_CLICK = "%1\$s - top content - %2\$s page - three dotted menu - click"
    const val BOTTOM_NAVIGATION_CLICK = " - bottom navigation - click"
    const val TOP_CONTENT_REVIEW_PAGE_CLICK = " - top content - review page - click"
    const val BACK_PRESSED_REVIEW = "click - back button "
    const val CLICK_MY_REVIEW_TAB = "click - ulasan saya tab"
    const val VIEW_MY_REVIEW_TAB = "view - ulasan saya tab"
    const val CLICK_WAITING_REVIEW_TAB = "click - menunggu diulas tab"
    const val VIEW_WAITING_REVIEW_TAB = "view - menunggu diulas tab"
    const val CLICK_REVIEW_SEARCH = "click - search bar on "
    const val CLICK_FILTER_REVIEW = "click - filter on "
    const val CLICK_SELECT_FILTER_REVIEW = "click - select filter from "
    const val VIEW_FILTER_PAGE = "view - filter invoice review on "
    const val CLICK_APPLY_FILTER_REVIEW = "click - apply filter from "
    const val CLICK_BACK_BUTTON_FILTER_REVIEW = "click - back button on filter from "
    const val CLICK_BACK_BUTTON_SELLER_FEEDBACK = "click - back button on seller feedback page"
    const val CLICK_RESET_BUTTON_FILTER_REVIEW = "click - reset button on filter from "
    const val VIEW_SELLER_FEEDBACK = "view - seller feedback page"
    const val SCROLL_REVIEW = "scroll - ulasan page on "
    const val CLICK_SMILEY = "click - smiley "
    const val CLICK_FOLLOW_BUTTON = "click - follow button - "
    const val CLICK_GIVE_REVIEW = "click - ulas produk"
    const val CLICK_OVERFLOW_MENU = "click - three dots menu on product review"
    const val CLICK_OVERFLOW_MENU_EDIT = "click - ubah on three dots menu"
    const val CLICK_OVERFLOW_MENU_SHARE = "click - bagikan on three dots menu"
    const val CLICK_SEE_REPLY_TEXT = "click - lihat balasan on product"
    const val VIEW_OVO_INCENTIVES_TICKER = "view - ovo incentives ticker"
    const val CLICK_READ_SK_OVO_INCENTIVES_TICKER = "click - baca s&k on ovo incentives ticker"
    const val CLICK_DISMISS_OVO_INCENTIVES_TICKER = "click - dismiss ovo incentives ticker"
    const val CLICK_DISMISS_OVO_INCENTIVES_BOTTOMSHEET = "click - dismiss ovo incentives s&k bottomsheet"
    const val CLICK_CONTINUE_SEND_REVIEW_0N_OVO_INCENTIVES = "click - lanjut kirim ulasan on ovo incentives s&k bottomsheet"
    //Label
    const val CLICK_REVIEW = "click review -"
    const val CLICK_GIVE_REVIEW_FROM = "click - beri ulasan on "
    const val CLICK_SEE_ALL_REVIEW_FROM = "click - lihat semua ulasan on "
    const val NEUTRAL = "neutral"
    const val HELPING = "helping"
    const val CLICK_PRODUCT_PICTURE_OR_NAME = "click product picture or name - "
    const val CLICK_USER_ACCOUNT = "click user account - "
    const val CLICK_THREE_DOTTED = "click three dotted menu - "
    const val DELETE = "delete"
    const val REPORT = "report review"
    const val CLICK_SEE_REPLIES = "click see replies - "
    const val REVIEW = "review"
    const val CLICK_SEE_MORE = "click see more"
    const val CLICK_ON_WHITESPACE = "click on whitespace"
    const val CLICK_ON_TEXT_REVIEW = "click on beri ulasan"
    const val MESSAGE = "message:"
    const val REVIEW_DETAIL_PAGE_SCREEN = "review detail page - report abuse"
    //key
    const val SHOP_ID = "shop_id"
    const val PRODUCT_ID = "product_id"
    const val EVENT = "event"
    const val EVENT_CATEGORY = "eventCategory"
    const val EVENT_ACTION = "eventAction"
    const val EVENT_LABEL = "eventLabel"
    const val SCREEN_NAME = "screenName"
}