package com.tokopedia.tradein

object TradeInGTMConstants {
    const val ACTION_CLICK_TRADEIN = "clickTradeIn"
    const val ACTION_VIEW_TRADEIN_IRIS = "viewTradeInIris"
    const val ACTION_CLICK = "click"
    const val ACTION_POP_UP = "pop up"
    const val OPEN_SCREEN = "openScreen"
    const val EVENT = "event"
    const val EVENT_CATEGORY = "eventCategory"
    const val EVENT_ACTION = "eventAction"
    const val EVENT_LABEL = "eventLabel"
    const val PRODUCT_ID = "productId"
    const val KEY_SCREEN_NAME = "screenName"
    const val KEY_CURRENT_SITE = "currentSite"
    const val KEY_USER_ID = "userId"
    const val KEY_BUSINESS_UNIT = "businessUnit"
    const val KEY_LOGGED_IN = "isLoggedInStatus"
    const val KEY_PROMOTIONS = "promotions"
    const val KEY_ECOMMERCE_EVENT = "ecommerce"
    const val KEY_PROMO_CLICK = "promoClick"
    const val KEY_PROMO_VIEW = "promoView"
    const val KEY_CREATIVE_NAME = "creative_name"
    const val KEY_ITEM_NAME = "item_name"
    const val CURRENT_SITE = "tokopediamarketplace"
    const val BUSINESS_UNIT = "trade-in"
    const val KEY_PAGE_PATH = "pagePath"
    const val CLICK_PG = "clickPG"
    const val EVENT_VIEW_ITEM = "view_item"
    const val EVENT_SELECT_CONTENT = "select_content"
    const val TRADE_IN_IMEI_IMPRESSION = "input IMEI - impression"
    const val TRADE_IN_IMEI_ATTEMPT = "input IMEI - attempt"
    const val TRADE_IN_IMEI_SUCCESS = "input IMEI - click lanjut tes fungsi"
    const val TRADE_IN_EDUCATIONAL_PAGE = "trade in educational page"
    const val TRADE_IN_CLICK_EDUCATIONAL_PAGE_BUTTON = "click educational page button"
    const val TRADE_IN_CLICK_DROPDOWN = "click lihat rincian harga"
    const val TRADE_IN_ERROR_PAGE = "trade in - error page"
    const val TRADE_IN_ERROR_PAGE_IMPRESSION = "impression error page"
    const val TRADE_IN_COVERAGE_PAGE = "trade in coverage area check"
    const val TRADE_IN_START_PAGE = "trade in start page"
    const val TRADE_IN_ERROR_PAGE_EVENT = "trade in error page"
    const val TRADE_IN_CLICK_EDUCATIONAL_PAGE = "click - tukar tambah sekarang"
    const val TRADE_IN_INITIAL_WITHOUT_IMEI = "trade in - initial price range - without IMEI"
    const val START_TRADE_IN = "start trade in"
}