
enum class SettingUiType {
    TICKER_SHOP_SCORE,
    DIVIDER,
    MENU_ITEM,
    SETTING_TITLE,
    INDENTED_SETTING_TITLE,
    SETTING_TITLE_MENU,
    SHOP_INFO,
    SHOP_ORDER,
    SHOP_PRODUCT,
    SECTION_TITLE
}