package com.tokopedia.autocompletecomponent.suggestion

const val GET_SUGGESTION_USE_CASE = "get_suggestion_use_case"
const val SUGGESTION_TRACKER_USE_CASE = "suggestion_tracker_use_case"

const val SUGGESTION_HEADER = "header"
const val SUGGESTION_SINGLE_LINE = "list_single_line"
const val SUGGESTION_DOUBLE_LINE = "list_double_line"
const val SUGGESTION_DOUBLE_LINE_SHOP_ADS = "list_double_line_shop_ads"
const val SUGGESTION_DOUBLE_LINE_WITHOUT_IMAGE = "list_double_line_without_image"
const val SUGGESTION_TOP_SHOP_WIDGET = "top_shop_widget"
const val SUGGESTION_TOP_SHOP = "top_shop"
const val SUGGESTION_TOP_SHOP_SEE_MORE = "top_shop_all"
const val SUGGESTION_PRODUCT_LINE = "list_product_line"
const val SUGGESTION_CHIP_WIDGET = "list_chips"
const val TYPE_KEYWORD = "keyword"
const val TYPE_RECENT_KEYWORD = "recent_keyword"
const val TYPE_CURATED = "curated"
const val TYPE_SHOP = "shop"
const val TYPE_PROFILE = "profile"
const val TYPE_LOCAL = "local"
const val TYPE_GLOBAL = "global"
const val TYPE_PRODUCT = "product"
const val TYPE_LIGHT = "light"
const val TYPE_BOLD_SQUARE = "bold_square"